version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  django:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/server
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true
  react:
    build:
      context: ./client
    volumes:
      - ./client/:/code
    ports:
      - 3000:3000
    depends_on:
      - django
    tty: true

volumes:
  pgdata: