TEAM_NAMES = {
 'Wet Favre',
 'Weterans Day Parade',
 'I can\'t believe it\'s not wetter',
 'Wetter off dead',
 'A nice cashmere wetter',
 'The lord\'s sprayer',
 'MFers forgot about spray',
 'Macy\'s Spray Parade',
 'Spray\'Quan Smith',
 'Spray Rice',
 'I\'m Asprayed Not',
 'Sean McSpray',
 'The Sprayed Deadline',
 'Wes Sprayven',
 'Every Kiss Begins With Spray',
 'Horton\'s Piercin Through',
 'The Swiss Miss',
 'Mr. Ls',
 'Chyaaannis Antetokoumpo',
 'Chyaaanathan Taylor',
 'Sebastian Chyaaanikowski',
 'Thinbelina',
 'A minor thindrance',
 'My cousin thinny',
 'Packed Thinnebago',
 'The President of Thinbabwe',
 'The Vice President of Thinbabwe',
 'Hope Thicks',
 'Thick Rick',
 'Thick at Nite',
 'Mike Gethicki',
 'Thiqqy Martin',
 'The Flea Thicker',
 'Thick Gutkus',
 'I can\'t believe it\'s not gutter',
 'Gutter Island',
 'The Gutting Green',
 'Pizza Gut',
 'Nutter Gutter',
 'Albert Puholes',
 'The South Hole',
 'Super Hole Ads',
 'Hole Blart',
 'Holed Dahl',
 'Fortune Favors the Holed',
 'The Tennessee Holenteers',
 'Holed English',
 'The Denver Gronkhos',
 'Spillbo Baggins',
 'Spill Wayne',
 'Spill.i.am.',
 'Women and spilldren first',
 'Spillionaire Boys Club',
 'Dr. Fill',
 'Danny Woundhead',
 'Cellars Market',
 'Fuego maradona',
 'Jason Pitten',
 'Ryan Pitzmagic',
 'Larry Pitzgerald',
 'Drew Febreeze',
 'Brian Schottgunheimer',
 'TJ Shotgunson',
 'Pepper Shots',
 'Watson and Jetsam',
 'Henry Rubbs',
 'Henry Tuggs',
 'Justin Tugger',
 'The Tug Report',
 'Tug Flutie',
 'Amanda Tugandkiss',
 'Louisville Tugger',
 'Dexter McForty',
 'Forty Nelson',
 'Thick and Forty',
 'Fortyroy pants',
 'Double barrel henderson',
 'Woody "Double" Barrelson',
 'Montrezl "Double" Barrel',
 'The Miami Allthins',
 'The Seattle Needcocks',
 'Oops! All Thins',
 'Welcome to the Thinderdome',
 'Thindie Newton',
 'Original Thin',
 'Thinbad',
 'Candlethicc Park',
 'SSX Thiqqy',
 'Thiqqy Mouse',
 'Thinnie Mouse',
 'A Hefty Muffaletta',
 'Henry Ford Bronco',
 'Lil Stain',
 'Ciggy Smalls',
 'The Big Ripper',
 'Rip Service',
 'Lil Drip Jr',
 'Ken Drippey Jr',
 'Flex-Mex',
 'Tyrannosaurus Flex',
 'Flex Luther',
 'Ruth Bader Thinsburg',
 'Flexter\'s Laboratory',
 'Flex Ed',
 'Saltergeist',
 'Insalt to Injury',
 'The San Andreas Salt',
 'Conestoga Swaggin',
 'Swags to Riches',
 'Rupaul\'s Swag Race',
 'Tyler YaBoyd',
 'Salter Sprayton Manning',
 'Tugboat Spilly',
 "the antonio brown debacle",
 "gauzy the bear",
 "alfred morris wang",
 "demaryius mas bleach",
 "mayhem december",
 "stanford jumpman jumpman jumpman",
 "gooooooo dick",
 "philip lindsay buckingham",
 "fuck andre johnson night",
 "the old eiffel tower",
 "offseason mixon",
 "a lloyd center halloween",
 "a sunday bj",
 "my pal jesus christo",
 "parris genevieve",
 "senor golloday inn express",
 "mr week 1 thick dick",
 "mister dick",
 "mister tonight today",
 "that dick/thiqq/hole/throat",
 "big yachty",
 "lil sticky",
 "Xandersnatch Jenkins",
 "This Xand is My Xand",
 "Green and Yellow Purple Spills",
 "Porous Jenkins",
 "Pourous Grant",
 "Marcus Pourous",
 "A Porous of Angels",
 "Chuck Pourous",
 "The 2020 Ford Porous",
 "Porous Burke",
 "Gaseous Clay",
 'Matt Gasselbeck',
 'Puff Puff Gas',
 'Hakeem Thiccs',
 'Thiqq Six',
 'Mr Thiqq Ass',
 'rafael naval 😡',
 'Stabernet Sauvignon',
 'Dexter\'s Staboratory',
 'Stab n Go',
 'Stab Calloway',
 'Gashed Potatoes',
 'pencil gimignano'
}