TEAM_NAMES = {
    'spillip seymour hoffman',
    'albert puholes',
    'wes sprayven',
    'fantachyaaa 2000 (theatrical release)',
    'being john malkothicch',
    'the manchurian xanddidate',
    'boris chyaaaw',
    'who framed roger stabbbit?',
    'hole blart',
    'thiqqy martin',
    'porous jenkins',
    'his dark materials: the holeden compass',
    'louisville tugger',
    'the imaginarium of doctor pargashus',
    'bridge to terstabbithia',
    'the lost world: jugashsic park',
    'thick gutkus',
    'thiccky davis',
    'holed dahl',
    'sean mcspray',
    'friday after flexxt',
    'about a yaboy',
    'suchyaata gaines',
    'pencil gimignano',
    'et: the flextra-terrestrial',
    'aflexxis ajinca',
    'spilllverado',
    'nutter gutter',
    'stabbricio oberto',
    'lottery thiccket',
    'the flexorcism of emily rose',
    'spillllion dollar baby',
    'talladega nights: the ballad of thiccky bobby',
    'thicccken little',
    'the wedding gashers',
    'jack thiccholson',
    'matt gasselbeck',
    "the lord's sprayer",
    'the south hole',
    '102 dalmachyaaans',
    "dexter's staboratory",
    'xanddy moore',
    'the flexxican',
    'the flea thicker',
    'mike gethicki',
    'joel spillzybilla',
    'saving spilllverman',
    'spillionaire boys club',
    'the tug report',
    'manu ginospillli',
    'spillla kunis',
    'ten things i hate stabout you',
    'susan saxanddon',
    'spill wayne',
    'jason xandders',
    'coyote tuggly',
    'holed dominion monarchs',
    'stabout schmidt',
    'the stabyss',
    'pourous grant',
    'chyaaamonds are forever',
    'porouss peterson',
    'steve gashh',
    'ruth bader thinsburg',
    'the spills have eyes ii',
    'inchyaaianapolis colts',
    'darko spilllicic',
    'lurkk nowitzki',
    'flex ed',
    'michael gashsbender',
    'chyaaami vice',
    "lemony thicccket's a series of unfortunate events",
    'forty nelson',
    'dr. fill',
    'tyreek spillll',
    'tugggrats go wild',
    'spilliladelphia',
    'women and spilldren first',
    "rupaul's stab race",
    'holed english',
    'riding in cars with yaboys',
    'gashton kutcher',
    'xanddra bullock',
    'danny woundhead',
    'thicck tracy',
    'chyaan mckellen',
    '3 ninjas thicck back',
    'out holedd',
    'cameron chyaaaz',
    'fuego maradona',
    'idaho xanddals',
    'james xanddolfini',
    'holedfinger',
    'the iron chyaaant',
    'jamie fleece curtis',
    'ken drippey jr',
    'luke saltton',
    "spray'quan smith",
    'spilllbert arenas',
    'thindie newton',
    'hope thicks',
    'moby thicck',
    'porous burke',
    'thiqqy mouse',
    'candlethicc park',
    'chyaaanathan taylor',
    'jimmy neutron: yaboy genius',
    'denzel gashhington',
    'the 40 year holed virgin',
    'castabblanca',
    'stabbin fever',
    "spillll & ted's flexcellent adventure",
    'zombiexandd',
    'chyaaannis antetokoumpo',
    'notting spillll',
    'thiccky cristina barcelona',
    'thicccken run',
    'paul spillllsap',
    'xanddy bullock',
    'unbreastabble',
    'gashed potatoes',
    "i can't believe it's not wetter",
    'bruce spillllis',
    'the flexorcist',
    'gashhington football team',
    'the chyaaanist',
    'sebastian chyaaanikowski',
    'gashius clay',
    'hakeem thiccs',
    'chyaaami dolphins',
    'watson and jetsam',
    'the spechyaaalist',
    'the itachyaaan job',
    'tugboat spilly',
    'tommy fleece jones',
    'xandderbilt commodores',
    'paul chyaaamatti',
    'troop beverly spilllls',
    'lil sticky',
    'thicck chubb',
    'edward scissorxands',
    'a porous of angels',
    'xandin cooks',
    'miss congeniality 2: armed and stabbulous',
    'reno 911!: chyaaami',
    'welcome to the thinderdome',
    'mr. smith goes to gashhington',
    'gashho nesterovic',
    'zooxandder',
    'saltergeist',
    'earl yaboykins',
    'gash of the titans',
    'spillbo baggins',
    "get thicch or die tryin'",
    'gashha vujacic',
    'carl xanddry',
    'gashlon jeffery',
    "bridget jones's chyaaary",
    'stabo sefolosha',
    'holeddeneye',
    'fantachyaaa 2000 (imax)',
    'to spillll a mockingbird',
    'double barrel henderson',
    'no country for holed men',
    'marcus pourous',
    'bad yaboys',
    'porous yeltsin',
    'drew febreeze',
    'gwyneth salttrow',
    'spilllliam shatner',
    'thicck nolte',
    'thick rick',
    'beverly spilllls cop ii',
    'henry chuggs iii',
    'the miami allthins',
    'zydrunas spilllgauskas',
    'xanddy foye',
    'the vice president of thinbabwe',
    'the greatest story ever holedd',
    'stabout a boy',
    'adam xanddler',
    'xantastic four: rise of the spilllver surfer',
    'whoopi holeddberg',
    'the amityspille horror',
    'gashheed wallace',
    'once upon a time in flexxico',
    'thicck-ass',
    'prince of persia: xandds of time',
    "cirque du freak: the vampire's gashistant",
    'tyler yaboyd',
    'chyaaami (oh) redhawks',
    "you've got maspill",
    'dexandre jordan',
    'blood chyaaamond',
    'adam porousson',
    'the san andreas salt',
    'xanderson varejao',
    'ssx thiqqy',
    'tugggrats in paris',
    'chyaaam neeson',
    'the gashsion of the christ',
    'stab calloway',
    'fortune favors the holed',
    'the president of thinbabwe',
    'scott spilllgrim vs. the world',
    'mark xandrews',
    'gashheem stabeet',
    'tango & gashh',
    'stabernet sauvignon',
    'white thicccks',
    'the spilllusionist',
    'omri gashspi',
    'thicckey blue eyes',
    "what's eating spilllbert grape",
    'the princess chyaaaries 2: royal engagement',
    'justin tugger',
    'thick at nite',
    'shia stabbeouf',
    'spill.i.am.',
    'robby xanderson',
    'russell spilllson',
    'dressed to spillll',
    'wetter off dead',
    'bill belithiccck',
    'this xand is my xand',
    'flexecutive decision',
    'arachnophochyaaa',
    'chrischyaan mccaffrey',
    "fool's holedd",
    'the xandd before time',
    'xandrew bogut',
    'chuck pourous',
    'thiccking and screaming',
    'julie xandrews',
    'last man xanding',
    'the tuggly truth',
    'xandrei kirspilllenko',
    'elton xandnd',
    'eric chyaaatkowski',
    'dominique spilllkins',
    'stabbari parker',
    'thicck fox',
    'lurkk hinrich',
    'aflexxey shved',
    "shaquspillle o'neal",
    'kareem stabdul-jabbar',
    'thicck barry',
    'thicck van flexel',
    'mahmoud stabdul-rauf',
    'flexx chapman',
    'kiki xanddeweghe',
    'rod thiccickland',
    'arvydas stabbonis',
    'saltt williams',
    'tom tugggliotta',
    'wally szczechyaaiak',
    'pooh thicchardson',
    'shareef stabdur-rahim',
    'jamal gashhburn',
    'dan thicckau',
    'leoholedd i of belgium',
    'dizzy spillllespie',
    'xandrew lloyd webber',
    'saint thiccholas',
    'denzel gashhington',
    'thiccholas i of ruchyaa',
    'pope thiccholas iv',
    'inkrid bergman',
    'george iv of the united inkdom',
    'whoopi holedberg',
    'spillliam faulkner',
    'ayn xandd',
    'andre agashsi',
    'xandy warhol',
    'princess chyaana',
}