TEAM_NAMES = {
    "i can't believe it's not gutter",
    'spillip seymour hoffman',
    "macy's spray parade",
    'albert puholes',
    'wes sprayven',
    'fortyroy pants',
    'fantachyaaa 2000 (theatrical release)',
    'being john malkothicch',
    'the manchurian xanddidate',
    'boris chyaaaw',
    'who framed roger stabbbit?',
    'hole blart',
    'thiqqy martin',
    'flexxas longhorns',
    'porous jenkins',
    'his dark materials: the holeden compass',
    'forgot about spray',
    'louisville tugger',
    'the imaginarium of doctor pargashus',
    'bridge to terstabbithia',
    'the lost world: jugashsic park',
    'thick gutkus',
    'thiccky davis',
    'holed dahl',
    'sean mcspray',
    'friday after flexxt',
    'about a yaboy',
    'suchyaata gaines',
    'pencil gimignano',
    'et: the flextra-terrestrial',
    'aflexxis ajinca',
    'spilllverado',
    'nutter gutter',
    'stabbricio oberto',
    'lottery thiccket',
    'the flexorcism of emily rose',
    'spillllion dollar baby',
    'talladega nights: the ballad of thiccky bobby',
    'thicccken little',
    'the wedding gashers',
    'jack thiccholson',
    'matt gasselbeck',
    "the lord's sprayer",
    'the south hole',
    '102 dalmachyaaans',
    "dexter's staboratory",
    'xanddy moore',
    'the flexxican',
    'the flea thicker',
    'mike gethicki',
    'rip service',
    'joel spillzybilla',
    'saving spilllverman',
    'spillionaire boys club',
    'the tug report',
    'manu ginospillli',
    'spillla kunis',
    'ten things i hate stabout you',
    'susan saxanddon',
    'mayhem december',
    'houston flexxans',
    'spill wayne',
    'jason xandders',
    'coyote tuggly',
    'holed dominion monarchs',
    "angela's gashes",
    'dexter mcforty',
    'thinnie mouse',
    'stabout schmidt',
    'the stabyss',
    'pourous grant',
    'chyaaamonds are forever',
    'porouss peterson',
    'steve gashh',
    'ruth bader thinsburg',
    'the spills have eyes ii',
    'inchyaaianapolis colts',
    'darko spilllicic',
    'lurkk nowitzki',
    'flex ed',
    'michael gashsbender',
    'chyaaami vice',
    "lemony thicccket's a series of unfortunate events",
    'forty nelson',
    'dr. fill',
    'tyreek spillll',
    'tugggrats go wild',
    'thinbad',
    'spilliladelphia',
    'thinbelina',
    'brian scastabrine',
    'appalachyaaian state mountaineers',
    'women and spilldren first',
    "rupaul's stab race",
    'holed english',
    'gashsachusetts minutemen',
    'riding in cars with yaboys',
    'gashton kutcher', 'xanddra bullock',
    'danny woundhead',
    'thicck tracy',
    'chyaan mckellen',
    '3 ninjas thicck back',
    'out holedd',
    'cameron chyaaaz',
    'fuego maradona',
    'idaho xanddals',
    'james xanddolfini',
    'holedfinger',
    'the iron chyaaant',
    'jamie fleece curtis',
    'ken drippey jr',
    'luke saltton',
    'jason pitten',
    "spray'quan smith",
    'spilllbert arenas',
    'thindie newton',
    'hope thicks',
    'henry tuggs',
    'moby thicck',
    'porous burke',
    'thiqqy mouse',
    'candlethicc park',
    'chyaaanathan taylor',
    'harry potter and the prisoner of astababan',
    'jimmy neutron: yaboy genius',
    'denzel gashhington',
    'the 40 year holed virgin',
    'castabblanca',
    'wet favre',
    'stabbin fever',
    "spillll & ted's flexcellent adventure",
    'zombiexandd',
    'chyaaannis antetokoumpo',
    'notting spillll',
    'thiccky cristina barcelona',
    'thicccken run',
    'brian schottgunheimer',
    "my stabby's daddy",
    'paul spillllsap',
    'xanddy bullock',
    'unbreastabble',
    'gashed potatoes',
    "i can't believe it's not wetter",
    'bruce spillllis',
    'the flexorcist',
    'gashhington football team',
    'the chyaaanist',
    'sebastian chyaaanikowski',
    'my cousin thinny',
    'gashius clay',
    'hakeem thiccs',
    'chyaaami dolphins',
    'watson and jetsam',
    'the spechyaaalist',
    'the itachyaaan job',
    'tugboat spilly',
    'tommy fleece jones',
    'xandderbilt commodores',
    'paul chyaaamatti',
    'troop beverly spilllls',
    'lil sticky',
    'thicck chubb',
    'edward scissorxands',
    'a porous of angels',
    'xandin cooks',
    'miss congeniality 2: armed and stabbulous',
    'reno 911!: chyaaami',
    'welcome to the thinderdome',
    'mr. smith goes to gashhington',
    'gashho nesterovic',
    'zooxandder',
    'saltergeist',
    'earl yaboykins',
    'gash of the titans',
    'spillbo baggins',
    "get thicch or die tryin'",
    'gashha vujacic',
    'carl xanddry',
    'gashlon jeffery',
    "bridget jones's chyaaary",
    'stabo sefolosha',
    'holeddeneye',
    'fantachyaaa 2000 (imax)',
    'to spillll a mockingbird',
    'double barrel henderson',
    'no country for holed men',
    'marcus pourous',
    'bad yaboys',
    'porous yeltsin',
    'drew febreeze',
    'stabby geniuses',
    'gwyneth salttrow',
    'spilllliam shatner',
    'thicck nolte',
    'thick rick',
    'beverly spilllls cop ii',
    'spray rice', 'henry rubbs',
    'the miami allthins',
    'zydrunas spillgauskas',
    'xanddy foye',
    'the vice president of thinbabwe',
    'the greatest story ever holedd',
    'stabout a boy',
    'adam xanddler',
    'fantastic four: rise of the spilllver surfer',
    'yi chyaaanlian',
    'whoopi holeddberg',
    'the amityspille horror',
    'gashheed wallace',
    'steve gash',
    'once upon a time in flexxico',
    'thicck-ass',
    'prince of persia: xandds of time',
    "cirque du freak: the vampire's gashistant",
    'tyler yaboyd',
    'chyaaami (oh) redhawks',
    "you've got maspill",
    'thiqq six',
    'dexandre jordan',
    'blood chyaaamond',
    'adam porousson',
    'the san andreas salt',
    'xanderson varejao',
    'ssx thiqqy',
    'tugggrats in paris',
    'chyaaam neeson',
    'the gashsion of the christ',
    'stab calloway',
    'fortune favors the holed',
    'the flexxas chainsaw massacre',
    'the president of thinbabwe',
    'super stabbies: baby geniuses 2',
    'scott spilllgrim vs. the world',
    'mark xandrews',
    'gashheem stabeet',
    'tango & gashh',
    'stabernet sauvignon',
    'white thicccks',
    'the spilllusionist',
    'omri gashspi',
    'thicckey blue eyes',
    "what's eating spilllbert grape",
    'the princess chyaaaries 2: royal engagement',
    'justin tugger',
    'thick at nite',
    'shia stabbeouf',
    'spill.i.am.',
    'robby xanderson',
    'russell spilllson',
    'dressed to spillll',
    'wetter off dead',
    'bill belithiccck',
    'this xand is my xand',
    'flexecutive decision',
    'arachnophochyaaa',
    'chrischyaan mccaffrey',
    "fool's holedd",
    'the xandd before time',
    'xandrew bogut',
    'chuck pourous',
    'thiccking and screaming',
    'butch gashsidy and the sundance kid',
    'julie xandrews',
    'orxandndo bloom',
    'last man xanding',
    'the tuggly truth'
}