# Generated by Django 2.2.15 on 2020-08-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontarget',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productiontarget',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productiontargetincrement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productiontargetincrement',
            name='overall_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='production.ProductionTarget'),
        ),
    ]
