# Generated by Django 2.2.15 on 2020-08-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
