# Generated by Django 2.2.15 on 2020-08-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_workorder_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['priority']},
        ),
    ]
