# Generated by Django 2.2.15 on 2020-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200828_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='color',
            field=models.CharField(default='#28a745', max_length=7),
        ),
    ]
