# Generated by Django 2.2.15 on 2020-08-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200827_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontarget',
            name='commitment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productiontarget',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
