# Generated by Django 2.2.15 on 2020-08-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20200827_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTargetCheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal', models.IntegerField(default=0)),
                ('overall_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='production.ProductionTarget')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionTargetIncrement',
        ),
    ]
