# Generated by Django 2.2.15 on 2020-08-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_workorder_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='brand',
        ),
    ]
