# Generated by Django 2.2.15 on 2020-08-28 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200828_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productiontarget',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='productiontarget',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productiontarget',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand'),
        ),
    ]
