# Generated by Django 2.2.15 on 2020-08-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20200829_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='qad',
            field=models.IntegerField(default=0, verbose_name="QA'd"),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='stocked',
            field=models.IntegerField(default=0),
        ),
    ]
