# Generated by Django 2.2.15 on 2020-08-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20200829_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='qad',
        ),
        migrations.AddField(
            model_name='workorder',
            name='merch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='qa',
            field=models.IntegerField(default=0),
        ),
    ]
