# Generated by Django 2.2.15 on 2020-09-16 00:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20200908_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 0, 0, 49, 16097, tzinfo=utc)),
        ),
    ]
