# Generated by Django 2.2.15 on 2020-08-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20200829_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='merch',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='qa',
        ),
        migrations.AddField(
            model_name='workorder',
            name='qad',
            field=models.IntegerField(default=0, verbose_name="QA'd"),
        ),
    ]
