# Generated by Django 2.2.15 on 2020-08-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20200829_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='color',
        ),
    ]
