YESES = [
    'yea',
    'yes',
    'yeah',
    'yaw',
    'hell yea',
    'fuck yea',
    'for sure',
    'definitely',
    'absolutely',
    'actually',
    'um yea',
    'uh yea',
    'uh ya',
    'um of course',
    'lol hell yea',
    'lol yup',
    'lmao yup',
    'yea',
    'yea',
    'ok',
    'okay',
    'alright',
    'sounds good',
    'right on',
    'of course',
    'fucking right',
    'yupp',
    'yup',
]