PAST_ACTIONS = [
    'ran train',
    'drove drunk',
    'smoked dank',
    'smoked crack',
    'dranka fodie',
    'shotgunned',
    'shotgunned a tallboy',
    'blitzed my ass',
    'waxed that ass',
    'waxed',
    'fucked me',
    'fucked everyone',
    'fucked',
    'queefed',
    'mock drafted',
    'whipped ass',
    'jacked off',
    'ripped ass',
    'macked',
    'sacked up',
    'did a strikeout',
    'ate my ass',
    'ate everyone\'s ass',
    'was salty',
    'ate some splashed potatoes',
    'wrecked shop',
    'bet a benjamin on his matchup',
    'drank bb juice',
    'got pierced',
    'walked all the way home',
    'blacked out',
    'drenched my ass',
    'knocked my ass out',
    'fucking fleeced me',
    'liked his own comment',
    'autodrafted',
    'got dropped',
    'dropped my ass',
    'threw me in an uber',
    'ordered breakfast burritos',
    'trolled my ass in pong',
    'canceled red zone',
    'got back on tinder',
    'needed pics',
    'was being a bish',
]

ONGOING_ACTIONS = [
    'is running train',
    'is driving drunk',
    'is smoking',
    'is drinking a fodie',
    'is shotgunning',
    'is shotgunning',
    'is shotgunning tallboys'
    'is blitzing my ass',
    'is waxing',
    'is fucking',
    'is shitting',
    'is mixing',
    'is queefing',
    'is mock drafting',
    'is eating my ass',
    'is eating everyone\'s ass',
    'is whipping ass',
    'is cutting lines',
    'is jacking off',
    'is prepping a strikeout',
    'is ripping ass',
    'is macking',
    'is sacking up',
    'is being salty',
    'is eating splashed potatoes',
    'is wrecking shop',
    'is talking trades',
    'is betting a benjamin on his matchup',
    'is drinking bb juice',
    'is getting pierced',
    'is walking all the way home',
    'is getting blacked',
    'is drenching my ass',
    'is fucking fleecing me',
    'is liking his own comment',
    'is autodrafting',
    'is straight waxing',
    'is getting dropped everywhere',
    'is dropping my ass',
    'is throwing zingers my way',
    'is tossing me in an uber',
    'is ordering breakfast burritos',
    'is trolling my ass in pong',
    'is canceling red zone',
    'is back on tinder',
    'is being a bish',
    'is drinkin fodies',
    'is broke af',
    'is super thiqqy stupid thiqqy',
    'is whipping my ass up and down main street',
    'is dead',
    'is getting pierced',
    'is getting his nipple pierced',
    'is on espn',
    'is being too thiqq',
    'is being thiqq af',
    'is sucking ass',
    'is vetoing my ass',
    'is being a good botch',
    'is pulling out all the stops',
    'is winning a global award',
    'is the asian homie at lloyd',
    'is fully tucked',
    'is catching a ride from eugene',
    'is clam stew',
    'is in the middle of a 4 mickey monday',
    'is literally being a topic',
    'is being so weak',
    'is acting wild',
    'is being stretchemmm x2',
    'is being chedddy 🧀 🧀 🧀',
    'is taking them drapes for a walk',
    'is mud wrestling a stripper',
    'is down for nipple piercings next year instead of belly',
    'is trying to accommodate everyone',
    'is a category 5 coming your way',
    'is doin me dirty',
    'is taking vegas',
    'is at the titty bar with walsh',
    'is firing my ass',
    'is giving shoutouts to the whole squad',
    'is getting injured again',
    'is vetoing everything',
    'is loving the production',
    'is hot af',
    'is pretty fucking salty',
    'is trash',
    'is complete trash',
    'is absolute trash',
    'is getting fingerbanged',
    'is hittin rock bottom',
    'is chilling in the pit',
    'is in the pit as we speak',
    'is like squirmit the frog',
    'is not playoffs level',
    'is squirting away in the chat',
    'is lost in the pit',
    'is getting tatted',
    'is in my ass',
    'is shotgunning in the pit',
    'needs pics'
]

INFINITIVE_ACTIONS = [
    'run wild',
    'run train',
    'drive drunk',
    'blitz my ass',
    'smoke crack',
    'smoke dank',
    'drink a fodie',
    'shotgun',
    'shotgun a tall boy',
    'wax my ass',
    'wax',
    'wax ass',
    'fuck me',
    'fuck everyone',
    'shit everywhere',
    'mix',
    'queef',
    'mock draft',
    'eat my ass',
    'eat everyone\'s ass',
    'whip all kinds of ass',
    'cut lines',

]