PAST_ACTIONS = [
    'ran train',
    'drove drunk',
    'smoked dank',
    'smoked crack',
    'dranka fodie',
    'shotgunned',
    'shotgunned a tallboy',
    'blitzed my ass',
    'waxed that ass',
    'waxed',
    'fucked me',
    'fucked everyone',
    'fucked',
    'queefed',
    'mock drafted',
    'whipped ass',
    'jacked off',
    'ripped ass',
    'macked',
    'sacked up',
    'did a strikeout',
    'ate my ass',
    'ate everyone\'s ass',
    'was salty',
    'ate some splashed potatoes',
    'wrecked shop',
    'bet a benjamin on his matchup',
    'drank bb juice',
    'got pierced',
    'walked home',
    'blacked out',
    'drenched my ass',
    'knocked my ass out',
    'fucking fleeced me',
    'liked his own comment',
    'autodrafted',
    'got dropped',
    'dropped my ass',
    'threw me in an uber',
]

ONGOING_ACTIONS = [
    'is running train',
    'is driving drunk',
    'is smoking',
    'is drinking a fodie',
    'is shotgunning',
    'is shotgunning',
    'is shotgunning tallboys'
    'is blitzing my ass',
    'is waxing',
    'is fucking',
    'is shitting',
    'is mixing',
    'is queefing',
    'is mock drafting',
    'is eating my ass',
    'is eating everyone\'s ass',
    'is whipping ass',
    'is cutting lines',
    'jacking off',
    'prepping a strikeout',
    'is ripping ass',
    'is macking',
    'is sacking up',
    'is being salty',
    'is eating splashed potatoes',
    'is wrecking shop',
    'is talking trades',
    'is betting a benjamin on his matchup',
    'drinking bb juice',
    'is getting pierced',
    'is walking home',
    'is getting blacked',
    'drenching my ass',
    'is fucking fleecing me',
    'is liking his own comment',
    'is autodrafting',
    'is straight waxing',
    'is getting dropped everywhere',
    'is dropping my ass',
    'throwing zingers my way',
    'tossing me in an uber',
]

INFINITIVE_ACTIONS = [
    'run wild',
    'run train',
    'drive drunk',
    'blitz my ass',
    'smoke crack',
    'smoke dank',
    'drink a fodie',
    'shotgun',
    'shotgun a tall boy',
    'wax my ass',
    'wax',
    'wax ass',
    'fuck me',
    'fuck everyone',
    'shit everywhere',
    'mix',
    'queef',
    'mock draft',
    'eat my ass',
    'eat everyone\'s ass',
    'whip all kinds of ass',
    'cut lines',
    'jack off',
    'rip ass',
    'spit game',
    'sack up',
    'throw hands',
    'do a strikeout',
    'be salty',
    'eat splashed potatoes',
    'wreck shop',
    'talk trades',
    'bet a benjamin on his matchup',
    'drink bb juice',
    'get pierced',
    'disappear',
    'walk home',
    'black out',
    'drench my ass',
    'knock my ass out',
    'fucking fleeced me',
    'like his own comment',
    'autodraft',
    'drop my ass',
    'throw zingers my way',
    'throw me in an uber',
]