JOKES = {'a.j. green': ['a.j. brown'],
 'aaron rodgers': ['errant rodgers'],
 'adam thielen': ['madam thielen', 'adam reelin'],
 'adrian peterson': ['adrian beaterson',
                     'adrian peterfather'],
 'alexander mattison': ['alexander mad',
                        'alexorer mattison'],
 'allen robinson': ['allen slobinson', 'gallon robinson'],
 'amari cooper': ['amari pooper', 'amari booper'],
 'antonio gibson': ['antonio fender', 'antonio gibfather', 'antonio gibfather'],
 'austin ekeler': ['austin heckler'],
 'austin hooper': ['austin pooper', 'austin super'],
 'ben roethlisberger': ['hen roethlisberger'],
 'brandin cooks': ['brandin cleans', 'brandin eats'],
 'calvin ridley': ['calvin pidley'],
 'cam newton': ['cam tootin', 'cramp newton', 'cramp newton'],
 'ceedee lamb': ['greedy lamb', 'ceedee baby sheep', 'ceedee baby sheep'],
 'chase claypool': ['face slayghoul', 'faced claypool', 'faced claypool'],
 'chase edmonds': ['face edmonds', 'faced edmonds', 'faced edmonds'],
 'chris carson': ['chris bikeson', 'miss marson'],
 'chris godwin': ['chris devilwin', 'miss godwin', 'miss godwin'],
 'christian mccaffrey': ['catholic mccaffrey',
                         'muslim mccaffrey'],
 'clyde edwards-helaire': ['hide edwards-helaire',
                           'clydesdale edwards-helaire'],
 'cooper kupp': ['super kupp', 'couper kupp', ],
 "d'andre swift": ['taylor swift', "d'andrew slow", "d'andrew slow"],
 "d'ernest johnson": ["d'ernest goes to camp",
                      "d'ernest johnfather"],
 'dalvin cook': ['calvin dook', 'dalvin eat', 'dalvin eat'],
 'damien harris': ['damien embarrass', 'damien hairless'],
 'darius slayton': ['darius hatin', 'truthius slayton', 'truthius slayton'],
 'darrell henderson jr.': ['barrell henderson jr',
                           'darrell henderfather'],
 'darren waller': ['darren faller', 'barren waller'],
 'davante adams': ['davande eves', 'davante madams', 'davante madams'],
 'deandre hopkins': ['deandre jumpkins', 'deandre hiphopkins'],
 'deebo samuel': ['dooby samuel', 'deebone samuel', 'deebone samuel'],
 'derrick henry': ['derelict henry', 'derrick roosterry'],
 'deshaun watson': ['deshaun flotsam', 'deshaun whyson', 'deshaun whyson'],
 'devante parker': ['devante driver'],
 'devin singletary': ['diggin singletary',
                      'devin doubletary'],
 'devonta freeman': ['devonta freewoman', 'devonta freelady'],
 'dj chark jr.': ['dj choke jr', 'bj chark jr', 'bj chark jr'],
 'dj moore': ['dj less'],
 'dk metcalf': ['dk metshin', 'donkey kong metcalf'],
 'eric ebron': ['eric lebron', 'eric ebron'],
 'evan engram': ['kevin engram', 'evan engsheep'],
 'ezekiel elliott': ['ezekiel idiot', 'ezekibell bellyot', 'ezekibell bellyot'],
 'gardner minshew ii': ['gardner maxshew', 'garnder maxshew'],
 'george kittle': ['george kettle bell', 'george little'],
 'greg zuerlein': ['beg zuerlein'],
 'henry ruggs iii': ['henry tuggs', 'henry druggs'],
 'j.d. mckissic': ['j.d. mckissmyass', 'j.d. mchugic'],
 'jamaal williams': ['jamall of america williams',
                     'jamaal spilliams'],
 'james conner': ['lame conner', 'James con artist', 'James con artist'],
 'james white': ['james black', 'james shite', 'james shite'],
 'jamison crowder': ['lamison crowder', 'jamison grounder'],
 'jarvis landry': ['jarvis pantry', 'jarvis lanwet'],
 'jason myers': ['chasin fires', 'jason tires'],
 'jason sanders': ['jason handhurts', 'chasin ganders', 'chasin ganders'],
 'jerick mckinnon': ['kate mckinnon'],
 'jerry jeudy': ['jerry booty', 'ferry feudy'],
 'jimmy graham': ['kimmy graham', 'jimmy grapork'],
 'joe mixon': ['joe blenderin', 'coffee mixon'],
 'john brown': ['john ground', 'gone brown'],
 'jonathan taylor': ['johnathan mailer',
                     'johnathan failure'],
 'jonnu smith': ['ebronnu smith', 'jonnu smith'],
 'josh jacobs': ['gosh jacobs', 'gosh jacobs', 'gosh jacobs'],
 'joshua kelley': ['joshua belley', 'goshua kelley'],
 'juju smith-schuster': ['pupu smith-schuster'],
 'julian edelman': ['choo choolian edelman', 'julian headelman'],
 'julio jones': ['julio drones', 'julio jeans', 'julio jeans'],
 'justin herbert': ['justin goat', 'justin goat', 'justin goat'],
 'justin jefferson': ['justin heiferson',
                      'justin jefferfather'],
 'justin tucker': ['justin tugger', 'justin fucker', 'justin fucker'],
 'kareem hunt': ['kareem gather', 'kareem cunt'],
 'keenan allen': ['keenan talon', 'meanan allen'],
 'kenny golladay': ['kenny on holiday', 'barbie golladay'],
 'kenyan drake': ['nigerian drake', 'canadian drake', 'canadian drake'],
 "la'mical perine": ['la-michal urine'],
 'lamar jackson': ['kumar jackson', 'lamar wackson', 'lamar wackson'],
 'latavius murray': ['latavius curry', 'lacravius murray'],
 'laviska shenault jr.': ['cant process!'],
 'leonard fournette': ['leonard threenette', 'leonard fivenette'],
 'mark andrews': ['fart andrews', 'mark handrews', 'mark handrews'],
 'mark ingram ii': ['dark ingram', 'mark inounce', 'mark inounce'],
 'mason crosby': ['mason crosby stills nash and young', 'facin crosby'],
 'matt ryan': ['fat ryan'],
 'matthew stafford': ['matthew laugherd',
                      'matthew stafchevy'],
 'melvin gordon iii': ['melvin boredom', 'melvin gordone'],
 'michael thomas': ['michael bombass', 'michael train', 'michael train'],
 'mike davis': ['mike davis', 'dike davis'],
 'mike evans': ['dike evans', 'mike ecars', 'mike ecars'],
 'myles gaskin': ['myles oilkin', 'kilometres gaskin'],
 'nick chubb': ['dick rub', 'slick chubb', 'slick chubb'],
 'noah fant': ['noah faint', 'noah fanta'],
 'nyheim hines': ['nyheim hines', 'nyheim hinds', 'nyheim hinds'],
 'odell beckham jr.': ['odell dickham jr'],
 'patrick mahomes': ['patrick mahouses', 'patreat mahomes', 'patreat mahomes'],
 'phillip lindsay': ['philip flimsy', 'phillip phillip', 'phillip phillip'],
 'raheem mostert': ['maheem leastert', 'raheem mosturd'],
 'randy bullock': ['randy bullshit', 'horny bullock', 'horny bullock'],
 'robbie gould': ['robbie silver', 'robbie mold', 'robbie mold'],
 'robby anderson': ['dobby anderson', 'robby handerson', 'robby handerson'],
 'robert tonyan': ['robert canyon', 'robert poundyan', 'robert poundyan'],
 'robert woods': ['bobbert woods', 'robert goods', 'robert goods'],
 'rodrigo blankenship': ['rodrigo tankenship',
                         'rodrigo bankenship'],
 'ronald jones': ['mcdonald jones', 'ronald drones', 'ronald drones'],
 'russell gage': ['russell rage', 'muscle gage', 'muscle gage'],
 'russell wilson': ['russell wilfather', 'muscle wilson', 'muscle wilson'],
 'sammy watkins': ['tammy watkins', 'mammy watkins', 'mammy watkins'],
 'scotty miller': ['scotty killer', 'body miller'],
 'sony michel': ['toshiba michel', 'jvc michel'],
 'stefon diggs': ['stefon climbs', 'stefon dicks', 'stefon dicks'],
 'sterling shepard': ['sterling sheep', 'silver shepard', 'silver shepard'],
 't.j. hockenson': ['d.j. talkinson', 't.j. hackenson', 't.j. hackenson'],
 't.y. hilton': ['thank you hilton', 't.y. milton', 't.y. milton'],
 'tee higgins': ['t-shirt higgins', 'tee higtonics'],
 'terry mclaurin': ['gary mclaurin', 'merry mclaurin'],
 'todd gurley ii': ['odd gurley', 'todd pearly', 'todd pearly'],
 'tom brady': ['tom lady', 'bomb trady'],
 'travis fulgham': ['travis fullcum', 'lavish fulgham', 'lavish fulgham'],
 'travis kelce': ['travis kelsey hightower', 'travis belchy', 'travis belchy'],
 'tyler boyd': ['tyler girld'],
 'tyreek hill': ['tyreek smells', 'one tree hill'],
 'will fuller v': ['will emptier', 'fill fuller'],
 'younghoe koo': ['bunghole poo', 'dunghoe koo'],
 'zack moss': ['zack loss', 'zack ivy']
}