NFL_TEAMS = [
    'Arizona Cardinals',
    'Atlanta Falcons',
    'Baltimore Ravens',
    'Buffalo Bills',
    'Carolina Panthers',
    'Chicago Bears',
    'Cincinatti Bengals',
    'Cleveland Browns',
    'Dallas Cowboys',
    'Denver Broncos',
    'Detroit Lions',
    'Green Bay Packers',
    'Houston Texans',
    'Indianapolis Colts',
    'Jacksonville Jaguars',
    'Kansas City Chiefs',
    'Las Vegas Raiders',
    'Los Angeles Chargers',
    'Los Angeles Rams',
    'New Orleans Saints',
    'Miami Dolphins',
    'Minnesota Vikings',
    'New England Patriots',
    'New York Giants',
    'New York Jets',
    'Philadelphia Eagles',
    'Pittsburgh Stellers',
    'San Francisco 49ers',
    'Seattle Seahawks',
    'Tampa Bay Buccaneers',
    'Tennesse Titans',
    'Washington Football Team'
]

COLLEGE_TEAMS = [
 'Cincinnati Bearcats',
 'Connecticut Huskies',
 'East Carolina Pirates',
 'Houston Cougars',
 'Memphis Tigers',
 'Navy Midshipmen',
 'SMU Mustangs',
 'South Florida Bulls',
 'Temple Owls',
 'Tulane Green Wave',
 'Tulsa Golden Hurricane',
 'UCF Knights',
 'Boston College Eagles',
 'Clemson Tigers',
 'Duke Blue Devils',
 'Florida State Seminoles',
 'Georgia Tech Yellow Jackets',
 'Louisville Cardinals',
 'Miami Hurricanes',
 'NC State Wolfpack',
 'North Carolina Tar Heels',
 'Pittsburgh Panthers',
 'Syracuse Orange',
 'Virginia Cavaliers',
 'Virginia Tech Hokies',
 'Wake Forest Demon Deacons',
 'Baylor Bears',
 'Iowa State Cyclones',
 'Kansas Jayhawks',
 'Kansas State Wildcats',
 'Oklahoma Sooners',
 'Oklahoma State Cowboys',
 'TCU Horned Frogs',
 'Texas Longhorns',
 'Texas Tech Red Raiders',
 'West Virginia Mountaineers',
 'Illinois Fighting Illini',
 'Indiana Hoosiers',
 'Iowa Hawkeyes',
 'Maryland terrapins',
 'Michigan Wolverines',
 'Michigan State Spartans',
 'Minnesota Golden Gophers',
 'Nebraska cornhuskers',
 'Northwestern Wildcats',
 'Ohio State Buckeyes',
 'Penn State Nittany Lions',
 'Purdue Boilermakers',
 'Rutgers Scarlet Knights',
 'Wisconsin Badgers',
 'Charlotte 49ers',
 'Florida Atlantic Owls',
 'Florida Intl Golden Panthers',
 'Louisiana Tech Bulldogs',
 'Marshall Thundering Herd',
 'Middle Tennessee Blue Raiders',
 'North Texas Mean Green',
 'Old Dominion Monarchs',
 'Rice Owls',
 'Southern Mississippi Golden Eagles',
 'Texas San Antonio Roadrunners',
 'UAB Blazers',
 'UTEP Miners',
 'Western Kentucky Hilltoppers',
 'Army Black Knights',
 'BYU Cougars',
 'Notre Dame Fighting Irish',
 'Akron Zips',
 'Ball State Cardinals',
 'Bowling Green Falcons',
 'Buffalo Bulls',
 'Central Michigan Chippewas',
 'Eastern Michigan Eagles',
 'Kent State Golden Flashes',
 'Massachusetts Minutemen',
 'Miami (OH) Redhawks',
 'Northern Illinois huskies',
 'Ohio Bobcats',
 'Toledo Rockets',
 'Western Michigan Broncos',
 'Air Force Falcons',
 'Boise State Broncos',
 'Colorado State Rams',
 'Fresno State Bulldogs',
 'Hawaii Rainbow Warriors',
 'Nevada Wolf Pack',
 'New Mexico Lobos',
 'San Diego State Aztecs',
 'San José State Spartans',
 'UNLV Rebels',
 'Utah State Aggies',
 'Wyoming Cowboys',
 'Arizona Wildcats',
 'Arizona State Sun Devils',
 'California Golden Bears',
 'Colorado Buffaloes',
 'Oregon Ducks',
 'Oregon State Beavers',
 'Stanford Cardinal',
 'UCLA Bruins',
 'USC Trojans',
 'Utah Utes',
 'Washington Huskies',
 'Washington State Cougars',
 'Alabama Crimson Tide',
 'Arkansas Razorbacks',
 'Auburn Tigers',
 'Florida Gators',
 'Georgia Bulldogs',
 'Kentucky Wildcats',
 'LSU Tigers',
 'Mississippi State Bulldogs',
 'Missouri Tigers',
 'Ole Miss Rebels',
 'South Carolina Gamecocks',
 'Tennessee Volunteers',
 'Texas A&M Aggies',
 'Vanderbilt Commodores',
 'Appalachian State Mountaineers',
 'Arkansas State Red Wolves',
 'Georgia Southern Eagles',
 'Georgia State Panthers',
 'Idaho Vandals',
 'Louisiana Lafayette Ragin Cajuns',
 'Louisiana Monroe Warhawks',
 'New Mexico State Aggies',
 'South Alabama Jaguars',
 'Texas State Bobcats',
 'Troy Trojans',
 'Cal Poly Mustangs',
 'Eastern Washington Eagles',
 'Idaho State Bengals',
 'Montana Grizzlies',
 'Montana State Bobcats',
 'North Dakota Fighting Hawks',
 'Northern Arizona Lumberjacks',
 'Northern Colorado Bears',
 'Portland State Vikings',
 'Sacramento State Hornets',
 'Southern Utah Thunderbirds',
 'UC Davis Aggies',
 'Weber State Wildcats',
 'Charleston Southern Buccaneers',
 'Coastal Carolina Chanticleers',
 'Gardner-Webb Bulldogs',
 'Kennesaw State Owls',
 'Liberty Flames',
 'Monmouth Hawks',
 'Presbyterian College Blue Hose',
 'Albany Great Danes',
 'Delaware Blue Hens',
 'Elon Phoenix',
 'James Madison Dukes',
 'Maine Black Bears',
 'New Hampshire Wildcats',
 'Rhode Island Rams',
 'Richmond Spiders',
 'Stony Brook Seawolves',
 'Towson Tigers',
 'Villanova Wildcats',
 'William & Mary Tribe',
 'East Tenn. St. Buccaneers',
 'Brown Bears',
 'Columbia Lions',
 'Cornell Big Red',
 'Dartmouth Big Green',
 'Harvard Crimson',
 'Penn Quakers',
 'Princeton Tigers',
 'Yale Bulldogs',
 'Bethune-Cookman Wildcats',
 'Delaware State Hornets',
 'Florida A&M Rattlers',
 'Hampton Pirates',
 'Howard Bison',
 'Morgan State Bears',
 'Norfolk State Spartans',
 'North Carolina A&T Aggies',
 'North Carolina Central Eagles',
 'Savannah State Tigers',
 'South Carolina State Bulldogs',
 'Illinois State Redbirds',
 'Indiana State Sycamores',
 'Missouri State Bears',
 'North Dakota State Bison',
 'Northern Iowa Panthers',
 'South Dakota Coyotes',
 'South Dakota State Jackrabbits',
 'Southern Illinois Salukis',
 'Western Illinois Leathernecks',
 'Youngstown State Penguins',
 'Bryant Bulldogs',
 'Central Connecticut Blue Devils',
 'Duquesne Dukes',
 'Robert Morris Colonials',
 'Sacred Heart Pioneers',
 'St Francis (PA) Red Flash',
 'Wagner Seahawks',
 'Austin Peay Governors',
 'Eastern Illinois Panthers',
 'Eastern Kentucky Colonels',
 'Jacksonville State Gamecocks',
 'Murray State Racers',
 'Southeast Missouri State Redhawks',
 'Tennessee State Tigers',
 'Tennessee Tech Golden Eagles',
 'Tennessee-Martin Skyhawks',
 'Bucknell Bison',
 'Colgate Raiders',
 'Fordham Rams',
 'Georgetown Hoyas',
 'Holy Cross Crusaders',
 'Lafayette Leopards',
 'Lehigh Mountain Hawks',
 'Butler Bulldogs',
 'Campbell Camels',
 'Davidson Wildcats',
 'Dayton Flyers',
 'Drake Bulldogs',
 'Jacksonville Dolphins',
 'Marist Red Foxes',
 'Morehead State Eagles',
 'San Diego Toreros',
 'Stetson Hatters',
 'Valparaiso Crusaders',
 'Chattanooga Mocs',
 'Furman Paladins',
 'Mercer Bears',
 'Samford Bulldogs',
 'The Citadel Bulldogs',
 'VMI Keydets',
 'Western Carolina Catamounts',
 'Wofford Terriers',
 'Abilene Christian Wildcats',
 'Central Arkansas Bears',
 'Houston Baptist Huskies',
 'Incarnate Word Cardinals',
 'Lamar Cardinals',
 'McNeese State Cowboys',
 'Nicholls State Colonels',
 'Northwestern State Demons',
 'Sam Houston State Bearkats',
 'Southeastern Louisiana Lions',
 'Stephen F Austin Lumberjacks',
 'Alabama A&M Bulldogs',
 'Alabama State Hornets',
 'Alcorn State Braves',
 'Arkansas-Pine Bluff Golde Lions',
 'Grambling State Tigers',
 'Jackson State Tigers',
 'Mississippi Valley State Delta Devils',
 'Prairie View A&M Prairie View',
 'Southern Jaguars',
 'Texas Southern Tigers']


NBA_PLAYERS = [
 'Ben Simmons',
 'Joel Embiid',
 'Jonathan Bender',
 'Cartier Martin',
 'O.J. Mayo',
 'Darrell Arthur',
 'David Andersen',
 'J.R. Smith',
 'Derek Fisher',
 'Andrew Bogut',
 'Mario Chalmers',
 'Chris Kaman',
 'Matt Carroll',
 'Juwan Howard',
 'Devean George',
 'Jameer Nelson',
 'Josh Howard',
 'Mike Wilks',
 'Roger Mason',
 'Josh Smith',
 'Royal Ivey',
 'Joel Przybilla',
 'Sean May',
 'Quentin Richardson',
 'Carl Landry',
 'Anthony Morrow',
 'Jamal Crawford',
 'Antoine Wright',
 'Joe Smith',
 'Brian Cook',
 'Kenny Thomas',
 'Keyon Dooling',
 'Brendan Haywood',
 'Kendrick Perkins',
 'Josh McRoberts',
 'Jodie Meeks',
 'Anderson Varejao',
 'Beno Udrih',
 'Othyus Jeffers',
 'Bill Walker',
 'Reggie Evans',
 'Zydrunas Ilgauskas',
 'Michael Redd',
 'Jordan Farmar',
 'Eduardo Najera',
 'Earl Barron',
 'Sonny Weems',
 'Paul Pierce',
 'Thabo Sefolosha',
 'Luc Mbah a Moute',
 'Austin Daye',
 'Matt Barnes',
 'J.J. Hickson',
 'Dwayne Jones',
 'Danny Granger',
 'Eddie House',
 'Paul Millsap',
 'Raymond Felton',
 'Ersan Ilyasova',
 'Chris Bosh',
 'John Salmons',
 'Oleksiy Pecherov',
 'Brook Lopez',
 'Jason Thompson',
 'Drew Gooden',
 'Manu Ginobili',
 'Fabricio Oberto',
 'Nick Young',
 'Eric Maynor',
 'Chris Andersen',
 'D.J. White',
 'Marcus Williams',
 'Jeff Pendergraph',
 'Shannon Brown',
 'Emeka Okafor',
 'DeAndre Jordan',
 'Jermaine Taylor',
 'JamesOn Curry',
 'Luis Scola',
 'Mikki Moore',
 'Yakhouba Diawara',
 'Russell Westbrook',
 'Brandon Bass',
 'Arron Afflalo',
 'Shane Battier',
 'Desmond Mason',
 'Josh Powell',
 'Kyle Lowry',
 'Bobby Brown',
 'Erick Dampier',
 'Jeff Foster',
 'Peja Stojakovic',
 'Grant Hill',
 'Dirk Nowitzki',
 'A.J. Price',
 'Vladimir Radmanovic',
 'Darnell Jackson',
 'Rasual Butler',
 'C.J. Watson',
 'Spencer Hawes',
 'Marcus Camby',
 'Matt Bonner',
 'Ronnie Brewer',
 'Aaron Gray',
 'Chauncey Billups',
 'Jordan Hill',
 'Mike Harris',
 'Kirk Hinrich',
 'Al Jefferson',
 'Dwyane Wade',
 'Ben Wallace',
 'Rasheed Wallace',
 'Andrea Bargnani',
 'Mike Conley',
 'Danilo Gallinari',
 'Anthony Tolliver',
 'Marcin Gortat',
 'Maurice Evans',
 'Al Harrington',
 'DeShawn Stevenson',
 'Roko Ukic',
 'Brandon Jennings',
 'Shavlik Randolph',
 'T.J. Ford',
 'Samuel Dalembert',
 'Larry Hughes',
 'Carmelo Anthony',
 'Pops Mensah-Bonsu',
 'Richard Jefferson',
 'Al Thornton',
 'Baron Davis',
 'Antawn Jamison',
 'Chase Budinger',
 'Hamed Haddadi',
 'Thaddeus Young',
 'Boris Diaw',
 'Martell Webster',
 'Pau Gasol',
 'Jose Calderon',
 'Eric Gordon',
 'Joe Alexander',
 'Ron Artest',
 'Marreese Speights',
 'Andrew Bynum',
 'Kareem Rush',
 "Shaquille O'Neal",
 'Stephen Curry',
 'Terrence Williams',
 'Craig Smith',
 'James Harden',
 'Tony Parker',
 'Nene Hilario',
 'Marcus Thornton',
 'Tony Battie',
 'Devin Harris',
 'Dan Gadzuric',
 'Marc Gasol',
 'Tyreke Evans',
 'Ronnie Price',
 'Deron Williams',
 'Andres Nocioni',
 'Marco Belinelli',
 'Alonzo Gee',
 'Nathan Jawai',
 'Marcus Banks',
 'D.J. Augustin',
 'Jonny Flynn',
 'Jeff Green',
 'James Singleton',
 'Stephen Graham',
 'Rodney Carney',
 'Anthony Carter',
 'Jason Kidd',
 'Damien Wilkins',
 'Julian Wright',
 'Nazr Mohammed',
 'Shaun Livingston',
 'Brandon Roy',
 'Hasheem Thabeet',
 'Sean Williams',
 'Anthony Johnson',
 'Marcus Haislip',
 'Carlos Arroyo',
 'Wilson Chandler',
 'Travis Outlaw',
 'Chuck Hayes',
 "Patrick O'Bryant",
 'Greg Oden',
 'Gerald Henderson',
 'Willie Green',
 'Derrick Rose',
 'Randolph Morris',
 'Antonio Anderson',
 'DeMar DeRozan',
 'Udonis Haslem',
 'Marvin Williams',
 'Delonte West',
 'Gilbert Arenas',
 'Hakim Warrick',
 'Cedric Jackson',
 "Jermaine O'Neal",
 'Chris Richard',
 'Jarvis Hayes',
 'Joey Graham',
 'Josh Boone',
 'Jarrett Jack',
 'Glen Davis',
 'James Jones',
 'Channing Frye',
 'Tracy McGrady',
 'Byron Mullens',
 'Raja Bell',
 'Francisco Garcia',
 'Chris Hunter',
 'Johan Petro',
 'David West',
 'Tim Thomas',
 'Leon Powe',
 'Steve Novak',
 'Kevin Martin',
 'Brandon Rush',
 'Joe Johnson',
 'Kobe Bryant',
 'Ryan Hollins',
 'Caron Butler',
 'Jared Jeffries',
 'Kevin Ollie',
 'C.J. Miles',
 'Gerald Wallace',
 'Corey Brewer',
 'Othello Hunter',
 'Ray Allen',
 'Andrei Kirilenko',
 'Sam Young',
 'Sundiata Gaines',
 'Ime Udoka',
 'Sasha Vujacic',
 'Daniel Gibson',
 'Rashard Lewis',
 'Taylor Griffin',
 'Jon Brockman',
 'Jarron Collins',
 'Daequan Cook',
 'Allen Iverson',
 'Courtney Lee',
 'Chucky Atkins',
 'Mike Miller',
 'Earl Watson',
 'Rafer Alston',
 'Brian Cardinal',
 'Michael Beasley',
 'Hilton Armstrong',
 'Steven Hunter',
 'Keith Bogans',
 'Jawad Williams',
 'Kurt Thomas',
 'Luke Ridnour',
 'Mardy Collins',
 'Kyrylo Fesenko',
 'Jason Kapono',
 'Jared Dudley',
 'Kenyon Martin',
 'Mike Bibby',
 'Jason Maxiell',
 'Chris Paul',
 'James Johnson',
 'Jerry Stackhouse',
 'Paul Davis',
 'Corey Maggette',
 'Donte Greene',
 'Richard Hamilton',
 'Ronald Murray',
 'Zach Randolph',
 'Andris Biedrins',
 'Jose Barea',
 'Wayne Ellington',
 'Andray Blatche',
 'Amir Johnson',
 'Tony Allen',
 'Will Conroy',
 'Mickael Pietrus',
 'Roy Hibbert',
 'Chris Duhon',
 'Ramon Sessions',
 'Stephen Jackson',
 'Kyle Korver',
 'Dahntay Jones',
 'Taj Gibson',
 'Kyle Weaver',
 'Darko Milicic',
 'Kelenna Azubuike',
 'Sean Marks',
 'Monta Ellis',
 'James Posey',
 'Sun Yue',
 'Luther Head',
 'Tyrus Thomas',
 'Antonio McDyess',
 'Jamaal Tinsley',
 'Devin Brown',
 'Jerryd Bayless',
 'Brad Miller',
 'Dwight Howard',
 'Jannero Pargo',
 'Yi Jianlian',
 'Patrick Mills',
 'Jason Terry',
 'Didier Ilunga-Mbenga',
 'J.J. Redick',
 'Jrue Holiday',
 'Goran Dragic',
 'Theo Ratliff',
 'Dominic McGuire',
 'Steve Blake',
 'Ty Lawson',
 'Wesley Matthews',
 'Malik Hairston',
 'DaJuan Summers',
 'Brian Skinner',
 'Etan Thomas',
 'Nicolas Batum',
 'Kosta Koufos',
 'Michael Finley',
 'Jason Smith',
 'Darren Collison',
 'Jeff Teague',
 'Shawn Marion',
 'Luke Walton',
 'Malik Allen',
 'Adam Morrison',
 'Aaron Brooks',
 'DeJuan Blair',
 'Rasho Nesterovic',
 'Kevin Love',
 'Darius Songaila',
 'Mike James',
 'Trey Gilder',
 'Andre Miller',
 'Sergio Rodriguez',
 'Jamario Moon',
 'Al Horford',
 'Earl Clark',
 'Trevor Ariza',
 'Leandro Barbosa',
 'Luol Deng',
 'Nate Robinson',
 'Anthony Randolph',
 'Reggie Williams',
 'Kevin Garnett',
 'Anthony Parker',
 'Ryan Anderson',
 'Mike Dunleavy',
 'Trenton Hassell',
 'Garrett Temple',
 'Lester Hudson',
 'Ricky Davis',
 'Jason Richardson',
 'Chris Quinn',
 'Tyson Chandler',
 'Rudy Gay',
 'Chris Douglas-Roberts',
 'Rajon Rondo',
 'Rodrigue Beaubois',
 'Vince Carter',
 'Lindsey Hunter',
 'Carlos Boozer',
 'George Hill',
 'Kwame Brown',
 'Renaldo Balkman',
 'Ben Gordon',
 'Bobby Simmons',
 'Tayshaun Prince',
 'Ronny Turiaf',
 'Toney Douglas',
 'Mehmet Okur',
 'Acie Law',
 'DeMarre Carroll',
 'Mario West',
 'Alexis Ajinca',
 'Francisco Elson',
 'Coby Karl',
 'Rodney Stuckey',
 'JaVale McGee',
 'Tyler Hansbrough',
 'Primoz Brezec',
 'Nick Collison',
 'Omri Casspi',
 'Kris Humphries',
 'Earl Boykins',
 'Will Bynum',
 'Joakim Noah',
 'Elton Brand',
 'Andre Iguodala',
 'Mo Williams',
 'Steve Nash',
 'Eddy Curry',
 'Morris Peterson',
 'Joel Anthony',
 'Jason Collins',
 'Dorell Wright',
 'Louis Williams',
 'Serge Ibaka',
 'Derrick Brown',
 'Nenad Krstic',
 'Robin Lopez',
 'Shelden Williams',
 'Ryan Bowen',
 'Amare Stoudemire',
 'Hedo Turkoglu',
 'Marquis Daniels',
 'Jonas Jerebko',
 'Marcus Landry',
 'Troy Murphy',
 'Rudy Fernandez',
 'Jason Williams',
 'Alando Tucker',
 'DeSagana Diop',
 'Travis Diener',
 'Randy Foye',
 'Kevin Durant',
 'Solomon Jones',
 'Charlie Villanueva',
 'Danny Green',
 'Louis Amundson',
 'Charlie Bell',
 'LeBron James',
 'Tim Duncan',
 'Carlos Delfino',
 'Ian Mahinmi',
 'Dante Cunningham',
 'Ryan Gomes',
 'Jason Hart',
 'Oliver Lafayette',
 'David Lee',
 'Lamar Odom',
 'LaMarcus Aldridge',
 'Chris Wilcox',
 'Sasha Pavlovic',
 'J.R. Giddens',
 'Jamaal Magloire',
 'Zaza Pachulia',
 'Quinton Ross',
 'Sebastian Telfair',
 'Joey Dorsey',
 'Brian Scalabrine']


COUNTRIES = [
 'Afghanistan',
 'Åland Islands',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antarctica',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Bouvet Island',
 'Brazil',
 'British Indian Ocean Territory',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Christmas Island',
 'Cocos (Keeling) Islands',
 'Colombia',
 'Comoros',
 'Congo',
 'Congo, The Democratic Republic of the',
 'Cook Islands',
 'Costa Rica',
 "Cote D'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Falkland Islands (Malvinas)',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'French Southern Territories',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heard Island and Mcdonald Islands',
 'Holy See (Vatican City State)',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran, Islamic Republic Of',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 "Korea, Democratic People's Republic of",
 'Korea, Republic of',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People'S Democratic Republic",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libyan Arab Jamahiriya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macao',
 'Macedonia, The Former Yugoslav Republic of',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia, Federated States of',
 'Moldova, Republic of',
 'Monaco',
 'Mongolia',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'Netherlands Antilles',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Norfolk Island',
 'Northern Mariana Islands',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestinian Territory, Occupied',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Pitcairn',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russian Federation',
 'RWANDA',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia and Montenegro',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Georgia and the South Sandwich Islands',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Svalbard and Jan Mayen',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Taiwan, Province of China',
 'Tajikistan',
 'Tanzania, United Republic of',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Minor Outlying Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Viet Nam',
 'Virgin Islands, British',
 'Virgin Islands, U.S.',
 'Wallis and Futuna',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe'
]

US_CITIES = [
 'New York, New York',
 'Los Angeles, California',
 'Chicago, Illinois',
 'Houston, Texas',
 'Philadelphia, Pennsylvania',
 'Phoenix, Arizona',
 'San Antonio, Texas',
 'San Diego, California',
 'Dallas, Texas',
 'San Jose, California',
 'Austin, Texas',
 'Indianapolis, Indiana',
 'Jacksonville, Florida',
 'San Francisco, California',
 'Columbus, Ohio',
 'Charlotte, North Carolina',
 'Fort Worth, Texas',
 'Detroit, Michigan',
 'El Paso, Texas',
 'Memphis, Tennessee',
 'Seattle, Washington',
 'Denver, Colorado',
 'Washington, District of Columbia',
 'Boston, Massachusetts',
 'Nashville-Davidson, Tennessee',
 'Baltimore, Maryland',
 'Oklahoma City, Oklahoma',
 'Louisville/Jefferson County, Kentucky',
 'Portland, Oregon',
 'Las Vegas, Nevada',
 'Milwaukee, Wisconsin',
 'Albuquerque, New Mexico',
 'Tucson, Arizona',
 'Fresno, California',
 'Sacramento, California',
 'Long Beach, California',
 'Kansas City, Missouri',
 'Mesa, Arizona',
 'Virginia Beach, Virginia',
 'Atlanta, Georgia',
 'Colorado Springs, Colorado',
 'Omaha, Nebraska',
 'Raleigh, North Carolina',
 'Miami, Florida',
 'Oakland, California',
 'Minneapolis, Minnesota',
 'Tulsa, Oklahoma',
 'Cleveland, Ohio',
 'Wichita, Kansas',
 'Arlington, Texas',
 'New Orleans, Louisiana',
 'Bakersfield, California',
 'Tampa, Florida',
 'Honolulu, Hawaii',
 'Aurora, Colorado',
 'Anaheim, California',
 'Santa Ana, California',
 'St. Louis, Missouri',
 'Riverside, California',
 'Corpus Christi, Texas',
 'Lexington-Fayette, Kentucky',
 'Pittsburgh, Pennsylvania',
 'Anchorage, Alaska',
 'Stockton, California',
 'Cincinnati, Ohio',
 'St. Paul, Minnesota',
 'Toledo, Ohio',
 'Greensboro, North Carolina',
 'Newark, New Jersey',
 'Plano, Texas',
 'Henderson, Nevada',
 'Lincoln, Nebraska',
 'Buffalo, New York',
 'Jersey City, New Jersey',
 'Chula Vista, California',
 'Fort Wayne, Indiana',
 'Orlando, Florida',
 'St. Petersburg, Florida',
 'Chandler, Arizona',
 'Laredo, Texas',
 'Norfolk, Virginia',
 'Durham, North Carolina',
 'Madison, Wisconsin',
 'Lubbock, Texas',
 'Irvine, California',
 'Winston-Salem, North Carolina',
 'Glendale, Arizona',
 'Garland, Texas',
 'Hialeah, Florida',
 'Reno, Nevada',
 'Chesapeake, Virginia',
 'Gilbert, Arizona',
 'Baton Rouge, Louisiana',
 'Irving, Texas',
 'Scottsdale, Arizona',
 'North Las Vegas, Nevada',
 'Fremont, California',
 'Boise City, Idaho',
 'Richmond, Virginia',
 'San Bernardino, California',
 'Birmingham, Alabama',
 'Spokane, Washington',
 'Rochester, New York',
 'Des Moines, Iowa',
 'Modesto, California',
 'Fayetteville, North Carolina',
 'Tacoma, Washington',
 'Oxnard, California',
 'Fontana, California',
 'Columbus, Georgia',
 'Montgomery, Alabama',
 'Moreno Valley, California',
 'Shreveport, Louisiana',
 'Aurora, Illinois',
 'Yonkers, New York',
 'Akron, Ohio',
 'Huntington Beach, California',
 'Little Rock, Arkansas',
 'Augusta-Richmond County, Georgia',
 'Amarillo, Texas',
 'Glendale, California',
 'Mobile, Alabama',
 'Grand Rapids, Michigan',
 'Salt Lake City, Utah',
 'Tallahassee, Florida',
 'Huntsville, Alabama',
 'Grand Prairie, Texas',
 'Knoxville, Tennessee',
 'Worcester, Massachusetts',
 'Newport News, Virginia',
 'Brownsville, Texas',
 'Overland Park, Kansas',
 'Santa Clarita, California',
 'Providence, Rhode Island',
 'Garden Grove, California',
 'Chattanooga, Tennessee',
 'Oceanside, California',
 'Jackson, Mississippi',
 'Fort Lauderdale, Florida',
 'Santa Rosa, California',
 'Rancho Cucamonga, California',
 'Port St. Lucie, Florida',
 'Tempe, Arizona',
 'Ontario, California',
 'Vancouver, Washington',
 'Cape Coral, Florida',
 'Sioux Falls, South Dakota',
 'Springfield, Missouri',
 'Peoria, Arizona',
 'Pembroke Pines, Florida',
 'Elk Grove, California',
 'Salem, Oregon',
 'Lancaster, California',
 'Corona, California',
 'Eugene, Oregon',
 'Palmdale, California',
 'Salinas, California',
 'Springfield, Massachusetts',
 'Pasadena, Texas',
 'Fort Collins, Colorado',
 'Hayward, California',
 'Pomona, California',
 'Cary, North Carolina',
 'Rockford, Illinois',
 'Alexandria, Virginia',
 'Escondido, California',
 'McKinney, Texas',
 'Kansas City, Kansas',
 'Joliet, Illinois',
 'Sunnyvale, California',
 'Torrance, California',
 'Bridgeport, Connecticut',
 'Lakewood, Colorado',
 'Hollywood, Florida',
 'Paterson, New Jersey',
 'Naperville, Illinois',
 'Syracuse, New York',
 'Mesquite, Texas',
 'Dayton, Ohio',
 'Savannah, Georgia',
 'Clarksville, Tennessee',
 'Orange, California',
 'Pasadena, California',
 'Fullerton, California',
 'Killeen, Texas',
 'Frisco, Texas',
 'Hampton, Virginia',
 'McAllen, Texas',
 'Warren, Michigan',
 'Bellevue, Washington',
 'West Valley City, Utah',
 'Columbia, South Carolina',
 'Olathe, Kansas',
 'Sterling Heights, Michigan',
 'New Haven, Connecticut',
 'Miramar, Florida',
 'Waco, Texas',
 'Thousand Oaks, California',
 'Cedar Rapids, Iowa',
 'Charleston, South Carolina',
 'Visalia, California',
 'Topeka, Kansas',
 'Elizabeth, New Jersey',
 'Gainesville, Florida',
 'Thornton, Colorado',
 'Roseville, California',
 'Carrollton, Texas',
 'Coral Springs, Florida',
 'Stamford, Connecticut',
 'Simi Valley, California',
 'Concord, California',
 'Hartford, Connecticut',
 'Kent, Washington',
 'Lafayette, Louisiana',
 'Midland, Texas',
 'Surprise, Arizona',
 'Denton, Texas',
 'Victorville, California',
 'Evansville, Indiana',
 'Santa Clara, California',
 'Abilene, Texas',
 'Athens-Clarke County, Georgia',
 'Vallejo, California',
 'Allentown, Pennsylvania',
 'Norman, Oklahoma',
 'Beaumont, Texas',
 'Independence, Missouri',
 'Murfreesboro, Tennessee',
 'Ann Arbor, Michigan',
 'Springfield, Illinois',
 'Berkeley, California',
 'Peoria, Illinois',
 'Provo, Utah',
 'El Monte, California',
 'Columbia, Missouri',
 'Lansing, Michigan',
 'Fargo, North Dakota',
 'Downey, California',
 'Costa Mesa, California',
 'Wilmington, North Carolina',
 'Arvada, Colorado',
 'Inglewood, California',
 'Miami Gardens, Florida',
 'Carlsbad, California',
 'Westminster, Colorado',
 'Rochester, Minnesota',
 'Odessa, Texas',
 'Manchester, New Hampshire',
 'Elgin, Illinois',
 'West Jordan, Utah',
 'Round Rock, Texas',
 'Clearwater, Florida',
 'Waterbury, Connecticut',
 'Gresham, Oregon',
 'Fairfield, California',
 'Billings, Montana',
 'Lowell, Massachusetts',
 'San Buenaventura (Ventura), California',
 'Pueblo, Colorado',
 'High Point, North Carolina',
 'West Covina, California',
 'Richmond, California',
 'Murrieta, California',
 'Cambridge, Massachusetts',
 'Antioch, California',
 'Temecula, California',
 'Norwalk, California',
 'Centennial, Colorado',
 'Everett, Washington',
 'Palm Bay, Florida',
 'Wichita Falls, Texas',
 'Green Bay, Wisconsin',
 'Daly City, California',
 'Burbank, California',
 'Richardson, Texas',
 'Pompano Beach, Florida',
 'North Charleston, South Carolina',
 'Broken Arrow, Oklahoma',
 'Boulder, Colorado',
 'West Palm Beach, Florida',
 'Santa Maria, California',
 'El Cajon, California',
 'Davenport, Iowa',
 'Rialto, California',
 'Las Cruces, New Mexico',
 'San Mateo, California',
 'Lewisville, Texas',
 'South Bend, Indiana',
 'Lakeland, Florida',
 'Erie, Pennsylvania',
 'Tyler, Texas',
 'Pearland, Texas',
 'College Station, Texas',
 'Kenosha, Wisconsin',
 'Sandy Springs, Georgia',
 'Clovis, California',
 'Flint, Michigan',
 'Roanoke, Virginia',
 'Albany, New York',
 'Jurupa Valley, California',
 'Compton, California',
 'San Angelo, Texas',
 'Hillsboro, Oregon',
 'Lawton, Oklahoma',
 'Renton, Washington',
 'Vista, California',
 'Davie, Florida',
 'Greeley, Colorado',
 'Mission Viejo, California',
 'Portsmouth, Virginia',
 'Dearborn, Michigan',
 'South Gate, California',
 'Tuscaloosa, Alabama',
 'Livonia, Michigan',
 'New Bedford, Massachusetts',
 'Vacaville, California',
 'Brockton, Massachusetts',
 'Roswell, Georgia',
 'Beaverton, Oregon',
 'Quincy, Massachusetts',
 'Sparks, Nevada',
 'Yakima, Washington',
 "Lee's Summit, Missouri",
 'Federal Way, Washington',
 'Carson, California',
 'Santa Monica, California',
 'Hesperia, California',
 'Allen, Texas',
 'Rio Rancho, New Mexico',
 'Yuma, Arizona',
 'Westminster, California',
 'Orem, Utah',
 'Lynn, Massachusetts',
 'Redding, California',
 'Spokane Valley, Washington',
 'Miami Beach, Florida',
 'League City, Texas',
 'Lawrence, Kansas',
 'Santa Barbara, California',
 'Plantation, Florida',
 'Sandy, Utah',
 'Sunrise, Florida',
 'Macon, Georgia',
 'Longmont, Colorado',
 'Boca Raton, Florida',
 'San Marcos, California',
 'Greenville, North Carolina',
 'Waukegan, Illinois',
 'Fall River, Massachusetts',
 'Chico, California',
 'Newton, Massachusetts',
 'San Leandro, California',
 'Reading, Pennsylvania',
 'Norwalk, Connecticut',
 'Fort Smith, Arkansas',
 'Newport Beach, California',
 'Asheville, North Carolina',
 'Nashua, New Hampshire',
 'Edmond, Oklahoma',
 'Whittier, California',
 'Nampa, Idaho',
 'Bloomington, Minnesota',
 'Deltona, Florida',
 'Hawthorne, California',
 'Duluth, Minnesota',
 'Carmel, Indiana',
 'Suffolk, Virginia',
 'Clifton, New Jersey',
 'Citrus Heights, California',
 'Livermore, California',
 'Tracy, California',
 'Alhambra, California',
 'Kirkland, Washington',
 'Trenton, New Jersey',
 'Ogden, Utah',
 'Hoover, Alabama',
 'Cicero, Illinois',
 'Fishers, Indiana',
 'Sugar Land, Texas',
 'Danbury, Connecticut',
 'Meridian, Idaho',
 'Indio, California',
 'Concord, North Carolina',
 'Menifee, California',
 'Champaign, Illinois',
 'Buena Park, California',
 'Troy, Michigan',
 "O'Fallon, Missouri",
 'Johns Creek, Georgia',
 'Bellingham, Washington',
 'Westland, Michigan',
 'Bloomington, Indiana',
 'Sioux City, Iowa',
 'Warwick, Rhode Island',
 'Hemet, California',
 'Longview, Texas',
 'Farmington Hills, Michigan',
 'Bend, Oregon',
 'Lakewood, California',
 'Merced, California',
 'Mission, Texas',
 'Chino, California',
 'Redwood City, California',
 'Edinburg, Texas',
 'Cranston, Rhode Island',
 'Parma, Ohio',
 'New Rochelle, New York',
 'Lake Forest, California',
 'Napa, California',
 'Hammond, Indiana',
 'Fayetteville, Arkansas',
 'Bloomington, Illinois',
 'Avondale, Arizona',
 'Somerville, Massachusetts',
 'Palm Coast, Florida',
 'Bryan, Texas',
 'Gary, Indiana',
 'Largo, Florida',
 'Brooklyn Park, Minnesota',
 'Tustin, California',
 'Racine, Wisconsin',
 'Deerfield Beach, Florida',
 'Lynchburg, Virginia',
 'Mountain View, California',
 'Medford, Oregon',
 'Lawrence, Massachusetts',
 'Bellflower, California',
 'Melbourne, Florida',
 'St. Joseph, Missouri',
 'Camden, New Jersey',
 'St. George, Utah',
 'Kennewick, Washington',
 'Baldwin Park, California',
 'Chino Hills, California',
 'Alameda, California',
 'Albany, Georgia',
 'Arlington Heights, Illinois',
 'Scranton, Pennsylvania',
 'Evanston, Illinois',
 'Kalamazoo, Michigan',
 'Baytown, Texas',
 'Upland, California',
 'Springdale, Arkansas',
 'Bethlehem, Pennsylvania',
 'Schaumburg, Illinois',
 'Mount Pleasant, South Carolina',
 'Auburn, Washington',
 'Decatur, Illinois',
 'San Ramon, California',
 'Pleasanton, California',
 'Wyoming, Michigan',
 'Lake Charles, Louisiana',
 'Plymouth, Minnesota',
 'Bolingbrook, Illinois',
 'Pharr, Texas',
 'Appleton, Wisconsin',
 'Gastonia, North Carolina',
 'Folsom, California',
 'Southfield, Michigan',
 'Rochester Hills, Michigan',
 'New Britain, Connecticut',
 'Goodyear, Arizona',
 'Canton, Ohio',
 'Warner Robins, Georgia',
 'Union City, California',
 'Perris, California',
 'Manteca, California',
 'Iowa City, Iowa',
 'Jonesboro, Arkansas',
 'Wilmington, Delaware',
 'Lynwood, California',
 'Loveland, Colorado',
 'Pawtucket, Rhode Island',
 'Boynton Beach, Florida',
 'Waukesha, Wisconsin',
 'Gulfport, Mississippi',
 'Apple Valley, California',
 'Passaic, New Jersey',
 'Rapid City, South Dakota',
 'Layton, Utah',
 'Lafayette, Indiana',
 'Turlock, California',
 'Muncie, Indiana',
 'Temple, Texas',
 'Missouri City, Texas',
 'Redlands, California',
 'Santa Fe, New Mexico',
 'Lauderhill, Florida',
 'Milpitas, California',
 'Palatine, Illinois',
 'Missoula, Montana',
 'Rock Hill, South Carolina',
 'Jacksonville, North Carolina',
 'Franklin, Tennessee',
 'Flagstaff, Arizona',
 'Flower Mound, Texas',
 'Weston, Florida',
 'Waterloo, Iowa',
 'Union City, New Jersey',
 'Mount Vernon, New York',
 'Fort Myers, Florida',
 'Dothan, Alabama',
 'Rancho Cordova, California',
 'Redondo Beach, California',
 'Jackson, Tennessee',
 'Pasco, Washington',
 'St. Charles, Missouri',
 'Eau Claire, Wisconsin',
 'North Richland Hills, Texas',
 'Bismarck, North Dakota',
 'Yorba Linda, California',
 'Kenner, Louisiana',
 'Walnut Creek, California',
 'Frederick, Maryland',
 'Oshkosh, Wisconsin',
 'Pittsburg, California',
 'Palo Alto, California',
 'Bossier City, Louisiana',
 'Portland, Maine',
 'St. Cloud, Minnesota',
 'Davis, California',
 'South San Francisco, California',
 'Camarillo, California',
 'North Little Rock, Arkansas',
 'Schenectady, New York',
 'Gaithersburg, Maryland',
 'Harlingen, Texas',
 'Woodbury, Minnesota',
 'Eagan, Minnesota',
 'Yuba City, California',
 'Maple Grove, Minnesota',
 'Youngstown, Ohio',
 'Skokie, Illinois',
 'Kissimmee, Florida',
 'Johnson City, Tennessee',
 'Victoria, Texas',
 'San Clemente, California',
 'Bayonne, New Jersey',
 'Laguna Niguel, California',
 'East Orange, New Jersey',
 'Shawnee, Kansas',
 'Homestead, Florida',
 'Rockville, Maryland',
 'Delray Beach, Florida',
 'Janesville, Wisconsin',
 'Conway, Arkansas',
 'Pico Rivera, California',
 'Lorain, Ohio',
 'Montebello, California',
 'Lodi, California',
 'New Braunfels, Texas',
 'Marysville, Washington',
 'Tamarac, Florida',
 'Madera, California',
 'Conroe, Texas',
 'Santa Cruz, California',
 'Eden Prairie, Minnesota',
 'Cheyenne, Wyoming',
 'Daytona Beach, Florida',
 'Alpharetta, Georgia',
 'Hamilton, Ohio',
 'Waltham, Massachusetts',
 'Coon Rapids, Minnesota',
 'Haverhill, Massachusetts',
 'Council Bluffs, Iowa',
 'Taylor, Michigan',
 'Utica, New York',
 'Ames, Iowa',
 'La Habra, California',
 'Encinitas, California',
 'Bowling Green, Kentucky',
 'Burnsville, Minnesota',
 'Greenville, South Carolina',
 'West Des Moines, Iowa',
 'Cedar Park, Texas',
 'Tulare, California',
 'Monterey Park, California',
 'Vineland, New Jersey',
 'Terre Haute, Indiana',
 'North Miami, Florida',
 'Mansfield, Texas',
 'West Allis, Wisconsin',
 'Bristol, Connecticut',
 'Taylorsville, Utah',
 'Malden, Massachusetts',
 'Meriden, Connecticut',
 'Blaine, Minnesota',
 'Wellington, Florida',
 'Cupertino, California',
 'Springfield, Oregon',
 'Rogers, Arkansas',
 'St. Clair Shores, Michigan',
 'Gardena, California',
 'Pontiac, Michigan',
 'National City, California',
 'Grand Junction, Colorado',
 'Rocklin, California',
 'Chapel Hill, North Carolina',
 'Casper, Wyoming',
 'Broomfield, Colorado',
 'Petaluma, California',
 'South Jordan, Utah',
 'Springfield, Ohio',
 'Great Falls, Montana',
 'Lancaster, Pennsylvania',
 'North Port, Florida',
 'Lakewood, Washington',
 'Marietta, Georgia',
 'San Rafael, California',
 'Royal Oak, Michigan',
 'Des Plaines, Illinois',
 'Huntington Park, California',
 'La Mesa, California',
 'Orland Park, Illinois',
 'Auburn, Alabama',
 'Lakeville, Minnesota',
 'Owensboro, Kentucky',
 'Moore, Oklahoma',
 'Jupiter, Florida',
 'Idaho Falls, Idaho',
 'Dubuque, Iowa',
 'Bartlett, Tennessee',
 'Rowlett, Texas',
 'Novi, Michigan',
 'White Plains, New York',
 'Arcadia, California',
 'Redmond, Washington',
 'Lake Elsinore, California',
 'Ocala, Florida',
 'Tinley Park, Illinois',
 'Port Orange, Florida',
 'Medford, Massachusetts',
 'Oak Lawn, Illinois',
 'Rocky Mount, North Carolina',
 'Kokomo, Indiana',
 'Coconut Creek, Florida',
 'Bowie, Maryland',
 'Berwyn, Illinois',
 'Midwest City, Oklahoma',
 'Fountain Valley, California',
 'Buckeye, Arizona',
 'Dearborn Heights, Michigan',
 'Woodland, California',
 'Noblesville, Indiana',
 'Valdosta, Georgia',
 'Diamond Bar, California',
 'Manhattan, Kansas',
 'Santee, California',
 'Taunton, Massachusetts',
 'Sanford, Florida',
 'Kettering, Ohio',
 'New Brunswick, New Jersey',
 'Decatur, Alabama',
 'Chicopee, Massachusetts',
 'Anderson, Indiana',
 'Margate, Florida',
 'Weymouth Town, Massachusetts',
 'Hempstead, New York',
 'Corvallis, Oregon',
 'Eastvale, California',
 'Porterville, California',
 'West Haven, Connecticut',
 'Brentwood, California',
 'Paramount, California',
 'Grand Forks, North Dakota',
 'Georgetown, Texas',
 'St. Peters, Missouri',
 'Shoreline, Washington',
 'Mount Prospect, Illinois',
 'Hanford, California',
 'Normal, Illinois',
 'Rosemead, California',
 'Lehi, Utah',
 'Pocatello, Idaho',
 'Highland, California',
 'Novato, California',
 'Port Arthur, Texas',
 'Carson City, Nevada',
 'San Marcos, Texas',
 'Hendersonville, Tennessee',
 'Elyria, Ohio',
 'Revere, Massachusetts',
 'Pflugerville, Texas',
 'Greenwood, Indiana',
 'Bellevue, Nebraska',
 'Wheaton, Illinois',
 'Smyrna, Georgia',
 'Sarasota, Florida',
 'Blue Springs, Missouri',
 'Colton, California',
 'Euless, Texas',
 'Castle Rock, Colorado',
 'Cathedral City, California',
 'Kingsport, Tennessee',
 'Lake Havasu City, Arizona',
 'Pensacola, Florida',
 'Hoboken, New Jersey',
 'Yucaipa, California',
 'Watsonville, California',
 'Richland, Washington',
 'Delano, California',
 'Hoffman Estates, Illinois',
 'Florissant, Missouri',
 'Placentia, California',
 'West New York, New Jersey',
 'Dublin, California',
 'Oak Park, Illinois',
 'Peabody, Massachusetts',
 'Perth Amboy, New Jersey',
 'Battle Creek, Michigan',
 'Bradenton, Florida',
 'Gilroy, California',
 'Milford, Connecticut',
 'Albany, Oregon',
 'Ankeny, Iowa',
 'La Crosse, Wisconsin',
 'Burlington, North Carolina',
 'DeSoto, Texas',
 'Harrisonburg, Virginia',
 'Minnetonka, Minnesota',
 'Elkhart, Indiana',
 'Lakewood, Ohio',
 'Glendora, California',
 'Southaven, Mississippi',
 'Charleston, West Virginia',
 'Joplin, Missouri',
 'Enid, Oklahoma',
 'Palm Beach Gardens, Florida',
 'Brookhaven, Georgia',
 'Plainfield, New Jersey',
 'Grand Island, Nebraska',
 'Palm Desert, California',
 'Huntersville, North Carolina',
 'Tigard, Oregon',
 'Lenexa, Kansas',
 'Saginaw, Michigan',
 'Kentwood, Michigan',
 'Doral, Florida',
 'Apple Valley, Minnesota',
 'Grapevine, Texas',
 'Aliso Viejo, California',
 'Sammamish, Washington',
 'Casa Grande, Arizona',
 'Pinellas Park, Florida',
 'Troy, New York',
 'West Sacramento, California',
 'Burien, Washington',
 'Commerce City, Colorado',
 'Monroe, Louisiana',
 'Cerritos, California',
 'Downers Grove, Illinois',
 'Coral Gables, Florida',
 'Wilson, North Carolina',
 'Niagara Falls, New York',
 'Poway, California',
 'Edina, Minnesota',
 'Cuyahoga Falls, Ohio',
 'Rancho Santa Margarita, California',
 'Harrisburg, Pennsylvania',
 'Huntington, West Virginia',
 'La Mirada, California',
 'Cypress, California',
 'Caldwell, Idaho',
 'Logan, Utah',
 'Galveston, Texas',
 'Sheboygan, Wisconsin',
 'Middletown, Ohio',
 'Murray, Utah',
 'Roswell, New Mexico',
 'Parker, Colorado',
 'Bedford, Texas',
 'East Lansing, Michigan',
 'Methuen, Massachusetts',
 'Covina, California',
 'Alexandria, Louisiana',
 'Olympia, Washington',
 'Euclid, Ohio',
 'Mishawaka, Indiana',
 'Salina, Kansas',
 'Azusa, California',
 'Newark, Ohio',
 'Chesterfield, Missouri',
 'Leesburg, Virginia',
 'Dunwoody, Georgia',
 'Hattiesburg, Mississippi',
 'Roseville, Michigan',
 'Bonita Springs, Florida',
 'Portage, Michigan',
 'St. Louis Park, Minnesota',
 'Collierville, Tennessee',
 'Middletown, Connecticut',
 'Stillwater, Oklahoma',
 'East Providence, Rhode Island',
 'Lawrence, Indiana',
 'Wauwatosa, Wisconsin',
 'Mentor, Ohio',
 'Ceres, California',
 'Cedar Hill, Texas',
 'Mansfield, Ohio',
 'Binghamton, New York',
 "Coeur d'Alene, Idaho",
 'San Luis Obispo, California',
 'Minot, North Dakota',
 'Palm Springs, California',
 'Pine Bluff, Arkansas',
 'Texas City, Texas',
 'Summerville, South Carolina',
 'Twin Falls, Idaho',
 'Jeffersonville, Indiana',
 'San Jacinto, California',
 'Madison, Alabama',
 'Altoona, Pennsylvania',
 'Columbus, Indiana',
 'Beavercreek, Ohio',
 'Apopka, Florida',
 'Elmhurst, Illinois',
 'Maricopa, Arizona',
 'Farmington, New Mexico',
 'Glenview, Illinois',
 'Cleveland Heights, Ohio',
 'Draper, Utah',
 'Lincoln, California',
 'Sierra Vista, Arizona',
 'Lacey, Washington',
 'Biloxi, Mississippi',
 'Strongsville, Ohio',
 'Barnstable Town, Massachusetts',
 'Wylie, Texas',
 'Sayreville, New Jersey',
 'Kannapolis, North Carolina',
 'Charlottesville, Virginia',
 'Littleton, Colorado',
 'Titusville, Florida',
 'Hackensack, New Jersey',
 'Newark, California',
 'Pittsfield, Massachusetts',
 'York, Pennsylvania',
 'Lombard, Illinois',
 'Attleboro, Massachusetts',
 'DeKalb, Illinois',
 'Blacksburg, Virginia',
 'Dublin, Ohio',
 'Haltom City, Texas',
 'Lompoc, California',
 'El Centro, California',
 'Danville, California',
 'Jefferson City, Missouri',
 'Cutler Bay, Florida',
 'Oakland Park, Florida',
 'North Miami Beach, Florida',
 'Freeport, New York',
 'Moline, Illinois',
 'Coachella, California',
 'Fort Pierce, Florida',
 'Smyrna, Tennessee',
 'Bountiful, Utah',
 'Fond du Lac, Wisconsin',
 'Everett, Massachusetts',
 'Danville, Virginia',
 'Keller, Texas',
 'Belleville, Illinois',
 'Bell Gardens, California',
 'Cleveland, Tennessee',
 'North Lauderdale, Florida',
 'Fairfield, Ohio',
 'Salem, Massachusetts',
 'Rancho Palos Verdes, California',
 'San Bruno, California',
 'Concord, New Hampshire',
 'Burlington, Vermont',
 'Apex, North Carolina',
 'Midland, Michigan',
 'Altamonte Springs, Florida',
 'Hutchinson, Kansas',
 'Buffalo Grove, Illinois',
 'Urbandale, Iowa',
 'State College, Pennsylvania',
 'Urbana, Illinois',
 'Plainfield, Illinois',
 'Manassas, Virginia',
 'Bartlett, Illinois',
 'Kearny, New Jersey',
 'Oro Valley, Arizona',
 'Findlay, Ohio',
 'Rohnert Park, California',
 'Westfield, Massachusetts',
 'Linden, New Jersey',
 'Sumter, South Carolina',
 'Wilkes-Barre, Pennsylvania',
 'Woonsocket, Rhode Island',
 'Leominster, Massachusetts',
 'Shelton, Connecticut',
 'Brea, California',
 'Covington, Kentucky',
 'Rockwall, Texas',
 'Meridian, Mississippi',
 'Riverton, Utah',
 'St. Cloud, Florida',
 'Quincy, Illinois',
 'Morgan Hill, California',
 'Warren, Ohio',
 'Edmonds, Washington',
 'Burleson, Texas',
 'Beverly, Massachusetts',
 'Mankato, Minnesota',
 'Hagerstown, Maryland',
 'Prescott, Arizona',
 'Campbell, California',
 'Cedar Falls, Iowa',
 'Beaumont, California',
 'La Puente, California',
 'Crystal Lake, Illinois',
 'Fitchburg, Massachusetts',
 'Carol Stream, Illinois',
 'Hickory, North Carolina',
 'Streamwood, Illinois',
 'Norwich, Connecticut',
 'Coppell, Texas',
 'San Gabriel, California',
 'Holyoke, Massachusetts',
 'Bentonville, Arkansas',
 'Florence, Alabama',
 'Peachtree Corners, Georgia',
 'Brentwood, Tennessee',
 'Bozeman, Montana',
 'New Berlin, Wisconsin',
 'Goose Creek, South Carolina',
 'Huntsville, Texas',
 'Prescott Valley, Arizona',
 'Maplewood, Minnesota',
 'Romeoville, Illinois',
 'Duncanville, Texas',
 'Atlantic City, New Jersey',
 'Clovis, New Mexico',
 'The Colony, Texas',
 'Culver City, California',
 'Marlborough, Massachusetts',
 'Hilton Head Island, South Carolina',
 'Moorhead, Minnesota',
 'Calexico, California',
 'Bullhead City, Arizona',
 'Germantown, Tennessee',
 'La Quinta, California',
 'Lancaster, Ohio',
 'Wausau, Wisconsin',
 'Sherman, Texas',
 'Ocoee, Florida',
 'Shakopee, Minnesota',
 'Woburn, Massachusetts',
 'Bremerton, Washington',
 'Rock Island, Illinois',
 'Muskogee, Oklahoma',
 'Cape Girardeau, Missouri',
 'Annapolis, Maryland',
 'Greenacres, Florida',
 'Ormond Beach, Florida',
 'Hallandale Beach, Florida',
 'Stanton, California',
 'Puyallup, Washington',
 'Pacifica, California',
 'Hanover Park, Illinois',
 'Hurst, Texas',
 'Lima, Ohio',
 'Marana, Arizona',
 'Carpentersville, Illinois',
 'Oakley, California',
 'Huber Heights, Ohio',
 'Lancaster, Texas',
 'Montclair, California',
 'Wheeling, Illinois',
 'Brookfield, Wisconsin',
 'Park Ridge, Illinois',
 'Florence, South Carolina',
 'Roy, Utah',
 'Winter Garden, Florida',
 'Chelsea, Massachusetts',
 'Valley Stream, New York',
 'Spartanburg, South Carolina',
 'Lake Oswego, Oregon',
 'Friendswood, Texas',
 'Westerville, Ohio',
 'Northglenn, Colorado',
 'Phenix City, Alabama',
 'Grove City, Ohio',
 'Texarkana, Texas',
 'Addison, Illinois',
 'Dover, Delaware',
 'Lincoln Park, Michigan',
 'Calumet City, Illinois',
 'Muskegon, Michigan',
 'Aventura, Florida',
 'Martinez, California',
 'Greenfield, Wisconsin',
 'Apache Junction, Arizona',
 'Monrovia, California',
 'Weslaco, Texas',
 'Keizer, Oregon',
 'Spanish Fork, Utah',
 'Beloit, Wisconsin',
 'Panama City, Florida'
]