REACTIONS = [
    'i cant think about anything else',
    'i cant stop watching',
    'its honestly fucked',
    'everyone here is pissed',
    'everyone here is stoked',
    'everyone here is just vibing',
    'im salty af',
    'people are pretty fucking salty',
    'im losing my mind',
    'everyone here is losing their minds',
    'people are losing their goddamn minds',
    'its an absolute trainwreck',
    'its absolute flames',
    'its honestly fucking lit',
    'its lit',
    'its fucking lit',
    'folks here are heated',
    'im fucking heated',
    'it doesnt help that im high as fuck',
    'it doesnt help that im high as balls',
    'i think a fight is about to break out',
    'people are throwing hands',
    'people are pissed',
    'everyones fucking',
    'people are fucking',
    'a rave just broke out',
    'im about to rage quit',
    'im fucking dead',
    'im dead',
    'im wrecked',
    'everyone is dying',
    'im dying',
    'my hole is a jalapeño now',
    'everyone is super thiqqy stupid thiqqy',
    'everyone is pulling out',
    'nobody\'s buying it',
    'everyone\s in my ass',
    'everyone\s in my ass about it',
    'everyone is straight hating on my ass',
    'everyone hates my ass',
    'im honestly fucked up',
    'everyone\'s fucked up',
    'now im getting fucking pierced',
    'everyones getting pierced',
    'everyones benching their thiqqs',
    'people are going in',
    'im getting in on it',
    'everyones getting involved',
    'i cant resist',
    'i lost a fucking benjamin',
    'i lost another fucking benjamin',
    'my ass is getting beat',
    ''
]