REASONS = [
    'is a bish',
    'is drinkin fodies',
    'is broke af',
    'is super thiqqy stupid thiqqy',
    'whips ass',
    'is dead',
    'was the first to get pierced',
    'is a previously pierced',
    'is on espn',
    'is too thiqq',
    'is thiqq af',
    'is ass',
    'is vetoing my ass',
    'is my good botch',
    'is pulling out all the time',
    'is a soggy bottoms bitch',
    'is winning a global award',
    'is the asian homie at lloyd',
    'is fully tucked',
    'is catching a ride from eugene',
    'is clam stew',
    'is a contender',
    'is on a 4 mickey monday',
    'is literally a topic',
    'is probably the weakest',
    'is actually wild',
    'is the fleecer and the shit',
    'is stretchemmm x2',
    'is cheddd 🧀 🧀 🧀',
    'is taking them drapes for a walk',
    'is mud wrestling a stripper',
    'is down for nipple piercings next year instead of belly',
    'is trying to accommodate everyone',
    'is a category 5 coming your way shmoop',
    'isnt lit',
    'got hurt in the pit',
    'is a looby dooby doin me dirty',
    'is more like clickbait than anything else',
    'is taking vegas',
    'is at the titty bar with walsh',
    'is firing your ass',
    'is giving shoutouts to the whole squad',
    'is vicks vapor rub',
    'has a big hog',
    'is always fucking hurt',
    'needs pics',
    'is vetoing everything',
    'is loving the production',
    'is hot af',
    'is pretty fucking salty',
    'is trash',
    'is complete trash',
    'is absolute trash',
    'is getting fingerbanged',
    'is hittin rock bottom',
    'is chilling in the pit',
    'is in the pit as we speak',
    'is like squirmit the frog',
    'is not playoffs level',
    'is squirting away in the chat',
    'is lost in the pit',
    'is getting tatted',
    'is in my ass',
    'is inside my ass',
    'is all the way inside my ass'
]