MEMBER_RESPONSES = [
    'lolll ya boi BBR_MEMBER ! ! rock bottom ! !',
    'if i could like squirmit the frog as much as BBR_MEMBER i would def get fucked by the rams d',
    '💯 anyone else want that ship besides BBR_MEMBER',
    '😳 espn : BBR_MEMBER likely out for the season',
    'youre chilling BBR_MEMBER so take your kids to salt disney',
    'my fave volleyball duo : kerri walsh and BBR_MEMBER',
    'that s my boiiiii whoop whoop',
    'good to hear that too god damnit i got 7th ... im pretty fucking salty BBR_MEMBER',
    'really loving the looks of this shit , BBR_MEMBER if you didnt know my other teams name is ya boy',
    'BBR_MEMBER i cancelled the trade , planet girth changed my mind',
    'ooh yeah , a great paragraph from BBR_MEMBER would fuckin do me',
    'you can all be my bottoms ! i dont remember lol',
    'lol BBR_MEMBER the only things guaranteed in life are death and death',
    'just got even more stressed today . anyone near a computer that can log BBR_MEMBER the fuck on',
    'thats some lishful there BBR_MEMBER',
    'gotcha. goddammit. i am really taking LS to fucking BBR_MEMBER goddamn',
    'congrats BBR_MEMBER ! ! ! !  the constant gardner i ’m loving this',
    'BBR_MEMBER stranded on waivers island out here but I did update my mac book to mac chaos mojave 10.14.6 so we lit',
    'wow BBR_MEMBER driving all 5 cars that ran over the lake show',
    'now thats some good bbr roasting by an open fire 😂 😂 wmfllllgggggg lolol i cant get pierced bro',
    'you invited an outsider to join. meanwhile BBR_MEMBER simply mentionns thiqq and everyone loses their minds',
    'yea BBR_MEMBER I had fun battling with you this week. 2 tds baby',
    'frankkkk the tankkkkk lollll BBR_MEMBER is 6 - 88 im not vetoing that shit',
    'need pics need pics need pics',
    'chyaaaa shenault me timbers! absolutely do not love to see it',
    'obviously BBR_MEMBER. there are only about 1000 messages in my ass right now',
    'fuck off BBR_MEMBER i love you',
    'cmon weve all been part of that hairy pussy lets just bet on BBR_MEMBER dangle',
    'the most overrated tight end in the draft order is BBR_MEMBER',
    'i like it more than ctrl - salt - delete, shout out to BBR_MEMBER for having scobee dick',
    'lets just clear the air BBR_MEMBER, i am eating ass',
    'unbelievable BBR_MEMBER, and you have the nipple ring? it turned green today',
    'henry ruggsmuncher should have changed name to vicks vapor rub',
    'brutal ! epic ! haha shit not even worried about the fleece BBR_MEMBER',
    'why BBR_MEMBER? lol i see a 7 am flight that could get you drunk but shoulda woodsa coulda',
    'lmaoooo a deep depression! ! another L for BBR_MEMBER !',
    'shoutout to my recent mediocrity',
    'lol get walsh on the phone and tell him were all in the building',
    'lol taking a bbr bro soon 😘 dont worry BBR_MEMBER',
    'i like lurk nowitski better, nice job BBR_MEMBER',
    'lmfaooo broooooooo 🤣 🤣 🤣 🤣',
    'you couldve drafted more thick dicks tbh BBR_MEMBER',
    'hes trash BBR_MEMBER lol. hes badminton. no ! hes fencing lol',
    '❤ ️ BBR_MEMBER lollll 😂 😂 😂 i ’m aware of human tight ends',
    'BBR_MEMBER i wanna bet 50 on them firing your ass yesterday',
    'BBR_MEMBER. its broadcasted in spanish so no, dick',
    'BBR_MEMBER you down to hit vegas august 19th weekend for your bday ? thatll be some some etsy dude',
    'lit my roommates for sure gonna fleece you BBR_MEMBER!',
    '😂 😂 😂 BBR_MEMBER lolllll you need to get pierced this year tbh',
    '🙄 🙄 🙄 ✏ ️ 🍆 BBR_MEMBER i would just sayin',
    'BBR_MEMBER just send me the old dangle',
    'good ol college parties ... ill hopefully be there . rome was our inaugural pierced location',
    'im here boi bring the puss !',
    'fuckin BBR_MEMBER!! so lucky',
    'im gonna change your name to lil lishy the content fishy BBR_MEMBER ! ! you like that ass?',
    'we should just txt him cause BBR_MEMBER probably will get the bbr',
    'im down BBR_MEMBER! lets fucking go stupid riccy',
    'dont want to blow your mind BBR_MEMBER but your team is ass',
    '1 fodie down and i still have a hell of a redbox lineup. Get fucked BBR_MEMBER!',
    'if anyone needs a cute bbr to play I have a BBR_MEMBER ass',
    'BBR_MEMBER! ! apple need to sponsor that ass! ! fuck! ! !',
    'fuck the damn packers ! !',
    'BBR_MEMBER squirting through the chat . true professional',
    'lol BBR_MEMBER did u keep ur jewelry to frame on mount bbr',
    'BBR_MEMBER missed his curfew last night so hes pretty much fucked',
    'BBR_MEMBER you gotta pay 4 that classic disney + drip',
    'BBR_MEMBER all eyes on you 👀 for some clarification here i ’d prefer to have that ass',
    'BBR_MEMBER wow ... yikes',
    'BBR_MEMBER theres a category 5 coming your way shmoop',
    'sounds like BBR_MEMBER wants in, we can put em on blast ?',
    'keep calm and sweat on, propose a bet and ill take it BBR_MEMBER',
    'I should prolly start gettin into it to someone other than BBR_MEMBER or walsh',
    'BBR_MEMBER doin usual BBR_MEMBER things lol',
    'check my snap chat BBR_MEMBER 😎 😎 😎 we fucked ? ?',
    'well im for sure fucked this sunday',
    'dont think i m a try to accommodate everyone BBR_MEMBER love it hahahaha',
    'nice doin business with you BBR_MEMBER',
    'fuck you BBR_MEMBER ... funny too cuz  lady fog horn raced two races earlier and won haha fuck ...',
    'it ’s a hopeless game we play haha were fucked BBR_MEMBER',
    'BBR_MEMBER its bbr not npr, who the fuck is down for nipple piercings next year instead of belly ?',
    'i dont even need to draft well BBR_MEMBER. just a little shade for the ride',
    'hahaha BBR_MEMBER your proposals are such trade rapes ca nt do it. if you dont want my thiqq boy just say so',
    'i already fell in love with strippers once BBR_MEMBER, even the worlds greatest warriors lose a battle every now and then',
    'asquirmative',
    'update : almost tore my mcl',
    'great BBR_MEMBER that ’s goal 1 . i just said get fucked',
    'wow lol clambi clam margera space clam clam bam thank you mam also when was the last time anyone cleaned their belly button',
    'official: BBR_MEMBER will you be my aaron hernandez',
    'shocker another punt jesus both these teams sucks ass battle of the ass',
    'i bet BBR_MEMBER woulda taken that bet on stripper mud wrestling ',
    'BBR_MEMBER, again. that may be ticonderoga , but the girth has left the building',
    'so BBR_MEMBER... most people stay away from 3 rb committees lol',
    'batchley !',
    'ill get a belly update when you take that drape for a walk BBR_MEMBER',
    'cheddd 🧀 🧀 🧀 thanks BBR_MEMBER ! and the fast track to the needlejuice dang outs',
    'lmao ! ! ! ! ! BBR_MEMBER im dead',
    'lol BBR_MEMBER will be my little sobrina picking names venmo me $',
    'its all on me baby lets fucking go stupid riccy nice job last week BBR_MEMBER',
    'BBR_MEMBER let me put a shotgun or beer chug on tonight\'s game ? loser has to be at ladds at 930',
    'a fresh wound for BBR_MEMBER?? sign me up',
    'BBR_MEMBER you are out of your belly piercing mind',
    'cmon BBR_MEMBER ! the suspense is killing me lol of course youre playing squirm edwards',
    'my ass hole gaping',
    'go ahead and give us another double barrel 🤣 🤣 🤣',
    'ok BBR_MEMBER, but loser has to sit in monday’s " god knows " corner lol',
    'BBR_MEMBER had to turn off mute cause im fuckin hard',
    'shout out to walsh calling BBR_MEMBER a wench',
    'wowowowowow u get better and i play some ass but i agree BBR_MEMBER lmao',
    'youre a happy meal, i would like some voodoo shit i m feeling thiqq today',
    'the irony of a pencil thin like BBR_MEMBER talking shit ',
    'hahaha BBR_MEMBER! ! ! ! lookin like a dill(y) for one how about a league wide shotgun',
    'dang BBR_MEMBER if you did nt know ... i fucking hate this sport',
    'yea but you have 512 fucking points on your bench BBR_MEMBER!!! goddammit lil kupp of stills water ... no bubbles',
    'as a bottom dweller myself, not fluffing yourself up is the shirtest way to go BBR_MEMBER',
    'now im for sure missing the playoffs BBR_MEMBER, incredible effort sir',
    'just adjusted and wtf the app is just torching me now goddammit fucking fuck',
    'the best part is when shit starts to go off on my bench. fucking stench goddamn',
    'i just got ousted from the playoffs so BBR_MEMBER imma take you out bruh! nothin but love everyone ’s been fleeced',
    'lol yeah dude i was literally a topic for weeks',
    'lmao!!!! yo the horse race thing is how we get big headed ... just my theory',
    'BBR_MEMBER just following you into your bathroom dude ^^ that man is a father 😂 😂',
    '4 mickey monday ? damnnn , we feeling a little far fetched BBR_MEMBER',
    'stakes are too high when ur names commish squirma ! ! collusion ! ! !',
    '? ? lol haha im feeling pretty good about getting my first pierce BBR_MEMBER',
    'im fucked up, BBR_MEMBER',
    'stupid little flamer!!! fuck!! me!!',
    'auto drafting ... eat that ass ! !',
    'i will be there BBR_MEMBER we fucked up',
    '! ! ! should be a bbr first and BBR_MEMBER just put me in the fridge',
    'BBR_MEMBER i smell bbr hole  😂',
    'its just live all year around flames. dont look at my phone , i think kruegz is gon nalose',
    'lmfao what does that mean ? ? i thought i won',
    'my two starting rbs for the next month are fucking dead ? ?',
    'haha shout out to BBR_MEMBER your team is garbage',
    'dilly dilly i had the under im fucked',
    'sorry BBR_MEMBER lollll hahaha. just dont believe youll find a chick with huge tits',
    'im a big sunday guy so still feeling good about it',
    'BBR_MEMBER tryin to sell high on either of the 2 aaron ’s in his ass',
    '👏 👏 👏 really appreciate that play by play BBR_MEMBER',
    'little lish bish thinnbalina 😂 😂 😂 ',
    'a win without a flex?? i think thats weak BBR_MEMBER. youve got a redzone bone !!!',
    'update : im draft driving lol hold on',
    'eyawwwwww better get that sack boy eyawwww',
    'its so fucked that the waiver wire thiqqness has dried up in the past 3 weeks',
    'commish lolll gtfo what rules can we enact to get pierced at the beginning of the season',
    'damn do n’t vontaze me bro lol',
    '😂 i ca n’t wait to draft haha call me a winner boy',
    'shout out to me. secretly actually want the leagues top ass',
    'my team looks poised to explode for 75 points in 4 games this year . kind of fucked',
    'goddamnit . glad you re having fun BBR_MEMBER cause im not',
    'shit shit shit the mormon stabernacle choir wants to fuck',
    'no i dont have a final tomorrow.. for sure would get waxed',
    '😂 😂 😂 😂 😂 BBR_MEMBER lolll',
    '👏 👏 👏 BBR_MEMBER really appreciate that ass 😂 😂 ',
    '😂 ☝ 🏽 lol im dying BBR_MEMBER 😂 😂 😂 ',
    'eyawwwwww BBR_MEMBER if i do say so myself',
    'ok BBR_MEMBER as long as you whip ass later',
    'my thiqqies are thiqqy thiqq thiqq all up in that ass',
    'honestly you could use a good name change BBR_MEMBER. How about pencil dicks 👏 👏',
    'BBR_MEMBER , how does it feel to leave work and i ’m right there',
    '💃 🧂 just spreading the salt how do you do',
    'lolll i love when you get nominated BBR_MEMBER 🤝 thumbs in butts',
    'honestly though how many missed messages are in my ass right now',
    'i love being the first to get pierced ! the thiqqy ! weeliiih ahh fuck i am fucked',
    'chill ! i mean im not really down but its chill',
    'lolllllllll i saw the espn guys say that one is cleared from all salt. obviously I dont buy it',
    'im fucked play BBR_MEMBER next week',
    'breaking : i just want more ass for the jewelry BBR_MEMBER',
    'go ahead and veto my ass BBR_MEMBER',
    'quite indeed my good botch',
    'wow my thins are for sure setting the drenchmark this weekend',
    'impressive display BBR_MEMBER 💯 💯',
    'BBR_MEMBER im changing your name to brick boii so get the fuck over here',
    'BBR_MEMBER im changing your name to a gift from god ! i love it',
    '😂 😂 BBR_MEMBER is as fuck fuck shit fuck ! !',
    'if you have n’t seen the subway commercials . . . bro',
    'thank god scott hanson a savage yassss bish',
    'i won a global award today which was quite the ass tasting as you know BBR_MEMBER',
    'thank you BBR_MEMBER!',
    'BBR_MEMBER im changing your name to ass ass garoppoflowin 🐐',
    'bro the asian homie at lloyd i cant wait to see him',
    'shout out to the group . really wanna try and stop the fake news',
    'the bbr gods. . . all about dangle precedents. . . and cheddd 🧀 🧀 🧀 ',
    'BBR_MEMBER bruh ! ! obviously not getting a w congrats on your roster',
    '^ confirmed no , ur team ... well and truly fucked',
    'fuck my life .... i am a little tuesday update for the league',
    'hmmm hes definitely not hotter but maybe sluttier 😂 😂 😂',
    'BBR_MEMBER i thought i changed your name to the dangle submarine',
    'catch a ride from eugene it searches all the flights at once. my thiqqies will come through',
    'i mean health is wealth BBR_MEMBER you need that ass',
    'the gallery 😂 😂 😂 im dying',
    'breaking : you can get hiv and scabies if you dangle on your defense',
    'flames just do nt look at my crib, anyone in pdx wants to wax this bitch? ?',
    'season 5 : dexter mcfourty changed name to randall slobb 😂',
    'ok saline dion lol',
    'update : my ass is fucked',
    'BBR_MEMBER trying to pull off a huge scandal  ... but yea ill change',
    'i ’ll call the homie his home dropped 40 points last week',
    'just following in your lackluster footsteps BBR_MEMBER 😘 hearts all around',
    'BBR_MEMBER strikes again ! 🔥 🔥 most valuable belly my hole is a jalapeño now',
    'ok thats fine lets gooooo ! and i " act crazy " lol',
    'BBR_MEMBER im changing your name to tummy trademark 🤤',
    'one sec, draft driving',
    'lolll BBR_MEMBER they caught me at lloyd center im fucked',
    'lol my bad BBR_MEMBER but to be fair i have thiqqies',
    'uh jacksonville is lit for 2pac but espn tech support is pro biggie',
    'lollll lmao i ’m at work during the draft imma one up BBR_MEMBER youre always involved in trade rape',
    'haha damn. indica? sativa?',
    'i ’m too fragile to bet em ! crank crank ! hahaha fucking love that',
    'i ’m rooting for you BBR_MEMBER ! ugh i always forget to change what really matters',
    'nice . BBR_MEMBER missed another field goal . that s some booty',
    'oh nice . BBR_MEMBER makes a benjamin and now everyone makes valid points',
    'or what ? bbr pic ? thats what i thought BBR_MEMBER',
    'kim jung actually could nt care less, just accept it',
    'what is the status of the cameras at the store i need to set my lineup',
    'alright let ’s fucking gooooo congrats BBR_MEMBER !',
    'meanwhile BBR_MEMBER is busy benching himself',
    'wowwwww setting the drenchmark drench wet no comparison 💯',
    'BBR_MEMBER im changing your name to thiqq flosskowski. my thiqq of course',
    'my only rbs now are blacked out 😂 😂',
    'fuck my fucking pencil squad',
    'lollll fleeced BBR_MEMBER',
    'BBR_MEMBER im changing your name to tugs bunny',
    '😂 wowzers BBR_MEMBER channeling your inner squirma on this fine trade rape tuesday proposal',
    'sounds good BBR_MEMBER? i ’ll take it deep flesh mode',
    'we might as well BBR_MEMBER lol lish is just a picture of cj anderson! lolll fucking bang',
    'we\'ll see, only problem is i always take veteran qbs in the waiver rules and get properly fucked',
    '? um ya',
    'this year , i work in every department BBR_MEMBER',
    'BBR_MEMBER is an honorable man, doesn’t even know the belly count',
    'this game is so whack .. : at least let me leave',
    'lmfao he knows it\'s a bold strategy cotton ! BBR_MEMBER shall we carpool?',
    'puss pic ! ! i just call him premium',
    'and b dubs pre pre bbr! ! ! we actually met the ceo of gucci and his ass fired my ass yesterday',
    '😂 😂 my girlfriend just noticed that my team needs some facial punishment',
    'lit! ! sept first is about 6 hours long too many fucking commercials',
    'he\'s definitely the bbr closeup king, frank the wife must be after both goff and cooks',
    'yeeeeessssss well played mr . xantastic baller so dumb . super chill thanks for the fifty BBR_MEMBER',
    'fuck ! ! ! fuck ! ! !',
    'happy new year from miami ! ! ! ! ! ! ! i just creamed',
    'rctid ! ! ! ! i hate my life',
    'gail the snail do over. need pics',
    'amazing love it ! where dat peppa at tho',
    'update : i didnt have to hear about that',
    'emannual mudiay every week ( top 15 receiver)',
    'fuck i forgot my saline at home',
    'life is a saturday ... eyawwwww that bbr is looking like marc davis long lost son',
    'tomorrow separates the pencil dicks from the thicks touché touché botches touché indeed botch touché botch',
    'gimme all the john hardbaughd # bde',
    'the seasons been cray already ! ! ! ! ! ! ! ! ! i won ! 😂 👌 #anticipated',
    'BBR_MEMBER straight fleecing the bbr squaw > dani dustmuffin',
    'hmm BBR_MEMBER, sounds like a guaranteed infection but there are a lot of bosses. did n\'t spill a drop this time 😂 😂airlines just forcing the homies to take ls this weekend ? ?',
    'lmao BBR_MEMBER your new nick is literally just kyle fuckin rudolph',
    'give me a sweet lickery kiss BBR_MEMBER !!',
    'damn the navel cave diggers came to play',
    'the chat ! i wonder if they would pierce the squirma',
    'let ’s dumb it down. im getting head with the bbr wish list : ( 1 carry , 0 yds )',
    'almost as embarrassing as these election results wow 😳 proof BBR_MEMBER hates trading',
    'man i used to say that. BBR_MEMBER is about to post some shit right now',
    'nah youre definitely guilty of some shady shit BBR_MEMBER sorry 😂 😂 ',
    'i know BBR_MEMBER! honestly such a good look lol',
    'that was a nasty hangover, its hard enough when we take ls christ lolllll',
    'i dont believe anyone cares about the playoffs 😂 just dont get pierced! ! !',
    'the fear is real once again lol the only thing saving me is fucking 🔥',
    'like holy shit i have all 4 patriots running backs this year 🙃 🙃',
    'jah feel jah feel jah feel jah feel jah feel',
    'i feel violated u wore a condom right BBR_MEMBER?',
    '😂 lishful thinking BBR_MEMBER we def need to involve vegas',
    'ive eased into 2 acquisitions who are you offering iv lubed up 2',
    'we live in a society . 😂 😂 👏 🏻 im getting shit on . bring fresh belly blood',
    'you fools always come through for me hahaha',
]

PLAYER_RESPONSES = [
    'yea, NFL_PLAYER is definitely fingerbanged',
    'looking good to me.. NFL_PLAYER! NFL_PLAYER !',
    'fleeced wow what a fleece. Fuckin NFL_PLAYER',
    'hey BBR_MEMBER how do u feel that one time you benched NFL_PLAYER and got shit on 😂 😂',
    'BBR_MEMBER? NFL_PLAYER is about to drop 69 points lol',
    'hot take 🔥 🔥 🌊 🌊 ! somehow he whips dat thiqqness NFL_PLAYER eatin fo sho',
    'yaaaaaasssssss ! ! ! ! ! ! hoping for a NFL_PLAYER tut hey hey',
    'holy fuck NFL_PLAYER in the league should be sponsored by tums',
    'NFL_PLAYER answer for your crimes! i ’ll move on. bitch',
    'dude i got hot for NFL_PLAYER for about a week its fucked',
    'loving the production from NFL_PLAYER',
    'NFL_PLAYER wants to make a lish foundation game time boys',
    'sco NFL_PLAYER!!!! 😟 or not lol',
    'heres a moment: when NFL_PLAYER get more snaps, we get more money',
    'should be a nice handcuff for NFL_PLAYER ur gucci',
    'we were in oliver thurns bathroom off division and NFL_PLAYER came in and cracked my ass open',
    'i like him but he for sure gets hurt and NFL_PLAYER gets bageled if that happens',
    'NFL_PLAYER 😂 lolll there we go good shit. hey BBR_MEMBER throw me a trade offer slut',
    'we all know NFL_PLAYER is a slut vulching all them tutties',
    'i heard BBR_MEMBER had sex with NFL_PLAYER and i said lol',
    'big 🍆 NFL_PLAYER ! ! ! keep watching those projections wow BBR_MEMBER you got me hard',
    'bench NFL_PLAYER then too , even with all the spam this morning his '
    'thiqqness is not playoffs level',
    'so chill eyaw ! ill be so lit like how i ’m in on my dog after NFL_PLAYER gets his',
    'I like NFL_PLAYER quite a bit. even if you dont wow, such a fucking stocking stuffer ! ! ! !',
    'BBR_MEMBER come join me . i feel your pain there ! NFL_PLAYER is trash',
    'hola! NFL_PLAYER changed his name to dangleberries i hate this',
    'yo. seeing NFL_PLAYER out there is working for me',
    'NFL_PLAYER. wow. my ass!!!',
    '😂 BBR_MEMBER you just did n’t want me to swoop NFL_PLAYER',
    'lol NFL_PLAYER is whack as fuck',
    'NFL_PLAYER was drafted .... hot garbage charky baby',
    'the NFL_PLAYER injury hurts , BBR_MEMBER batch what are you talking about gtfo',
    'wow NFL_PLAYER tho lfg yesss ! another auto draft team in bbr, call me mr . tummyness winner hands',
    'fucking NFL_PLAYER ..... hunting for my ass',
    'NFL_PLAYER is more like clickbait than anything else. and im definitely not '
    'one of ur notifications dumbass',
    'NFL_PLAYER on the block',
    'fuckkkkkk so whack when the fuck is a tie better than a torn achilles for NFL_PLAYER',
    'NFL_PLAYER on the bench! the fuck are you thinking',
    'NFL_PLAYER is a bum BBR_MEMBER but I would hit him up for ass at least',
    'BBR_MEMBER is deff doing butt stuff with NFL_PLAYER this weekend while my ff team takes another l',
    'im still interested in NFL_PLAYER ? ? ? wtf is wrong with me',
    'NFL_PLAYER is a power bottom lmao put some respeck on that 😂',
    'BBR_MEMBER take an offer for NFL_PLAYER if ya can cause i hate you starting his ass',
    'lolll looby dooby NFL_PLAYER dewing me dirty damn',
    'NFL_PLAYER just isnt lit he got hurt in the pit',
    'NFL_PLAYER lookin explosive af 😂 are you okay BBR_MEMBER',
    'honestly after NFL_PLAYER shits the bed first week id be down for whatever',
    'NFL_PLAYER is working with a delivery service in my ass',
    'good stuff from NFL_PLAYER. love watching football players punch each other '
    'honestly NFL_PLAYER shouldnt be on the same team as my opinions',
    'nah i have faith in NFL_PLAYER looks like ... a very enticing fuck',
    '😎 🏌 🏻\u200d ♂ ️ lollll i wanna get that shit on with NFL_PLAYER',
    'NFL_PLAYER could do the same shit every year, ive cleared out a few blowjobs already',
    'NFL_PLAYER is no splashed potatoes 🥔 to the bench ! ! !',
    'NFL_PLAYER looks like such a queef ... but he did go beast mode on his last tug',
    'NFL_PLAYER sucks for opportunity i need a streetsweeper out chea',
    'BBR_MEMBER are you hating NFL_PLAYER being on your own supply',
    'NFL_PLAYER is dry mother fucking piece of shit what happened to him ?',
    "my rbs were wrecked but NFL_PLAYER's thick hog has given me life",
    'BBR_MEMBER 😂 😂 😂 😂 😂 NFL_PLAYER ? i ’ve seen him',
    'is NFL_PLAYER about to get some penetration in? no ...',
    'i ’ll be there about 115 lets just see NFL_PLAYER throw tugs',
    'no i m not jah feelin NFL_PLAYER',
    '💩 dude same thing get NFL_PLAYER on the ballot',
    'the saltiest of posts 😂 😂 it does make up for NFL_PLAYER so.. we lit',
    '? ? NFL_PLAYER . Bro ! classic i would trade any of my thiqqs . whoever',
    'another big performance from BBR_MEMBER ! ! ! ! ! NFL_PLAYER fucks',
    '! stretchemmm x2 ! ! ! ! go ducks cant believe i dropped NFL_PLAYER',
    'you check this chat ... group therapy for NFL_PLAYER',
    'all im saying is dont do it in the tunnel with NFL_PLAYER',
    'ay BBR_MEMBER, signed and sealed. NFL_PLAYER is like the shittier version of danny woodhead',
    'NFL_PLAYER .. its every fuckin sunday with this shit',
    'the fleecer and the shit is real i was trying to beautiful mind my way through this NFL_PLAYER performance',
    "😂 NFL_PLAYER is 6'3 maybe , and that ’s a whole schpiel",
    'fuck that sucks for NFL_PLAYER . and my belly?!?',
    'take me back to portland tomorrow , fuck ! hahha NFL_PLAYER sucking it',
    'NFL_PLAYER is an emergency . fuck canned beans , this shit sucks!!!!',
    'fucking fuck what\'s happening on waivers . right after picking up NFL_PLAYER too',
    'stfu fucking garbage NFL_PLAYER getting dropped first thing in the morning',
    'BBR_MEMBER you told me to trade NFL_PLAYER ! ! ! !',
    'lol NFL_PLAYER is about to ruin the whole season',
    'BBR_MEMBER has scored 110 pts today meaning he definitely has NFL_PLAYER in his stable',
    'NFL_PLAYER?? please ink the deal BBR_MEMBER!',
    'batchley ! NFL_PLAYER fucks!',
    'NFL_PLAYER not killing it so y’ all can take him this season . #foreverscarred',
    'holy fuck NFL_PLAYER.. hey BBR_MEMBER, you wanna score a few and bring that ass down . where u at playa ?',
    'suck this drenchcoat birch drench * * * can NFL_PLAYER just show up tonight fuck',
    'lolll i ca nt blame NFL_PLAYER i respect the drip too much. to my chagrin',
    'NFL_PLAYER is probably the weakest thing ive ever been ok with',
    'hmmmm interesting fleece. although NFL_PLAYER feels more slated as a self - fulfleecing prophecy for me but i ’ve also been so nasty',
    'i already am a contender me giving you NFL_PLAYER would make you lose even more bitch',
    'see this NFL_PLAYER fool on memphis shorts ? delishous content here planet lish it keeps him warm in the winter',
    'internet gettin wild on NFL_PLAYER today . just the right amount of fuck lol',
    'yupppppp one more fg baby NFL_PLAYER is an absolute toss up. codeine zuerlean we lit',
    '🤤 jesus please send NFL_PLAYER to the university of pouregon',
    'NFL_PLAYER, a legendary both sides of the fence fuccboi',
    'damnnn . everyone puttin money on NFL_PLAYER now huh',
    'im just saying lmfao ... how lucky can one guy be ... fucking NFL_PLAYER',
    'NFL_PLAYER runs a classic route to danglin',
    'the most overrated tight end in life but in fantasy.. is NFL_PLAYER really not following through wtf',
    ' 😂 ☝ 🏽 lol NFL_PLAYER likely tore acl too . all things sucking right now',
    'damn. NFL_PLAYER looks like he has the worst liver ever',
    'yes NFL_PLAYER is super thiqqy stupid thiqqy lol im too high lol',
    'lol NFL_PLAYER is gonna dust me either way. im about to get dan baileyed and ive never even heard of that',
    'wow thats wack . NFL_PLAYER on IR cause of shotguns in the pit ? ? ?',
    'fr we all know you hate NFL_PLAYER BBR_MEMBER',
    'NFL_PLAYER isnt going anywhere he a super thiqqy stupid thiqqy',
    'shoutout to me for benching NFL_PLAYER in my other league 😂 😂',
    'theres still hope! two thoughts: NFL_PLAYER is fucking',
    'wow ya boy NFL_PLAYER created new poll: would you say you mustache?',
    'sorry BBR_MEMBER. NFL_PLAYERs value just went up haha im smackin asses fuff sho',
    'nah i d be willing to bend over backwards and give NFL_PLAYER the old fml',
    'clam stew is more valuable than NFL_PLAYER',
    'NFL_PLAYERs best weeks were on your team fuckkkkkkkkkkkkkkkkkkkk',
    'lets go NFL_PLAYER ! had no choice but to be honest',
    'i see you ’re schwarmin ’ up to NFL_PLAYER 😘 😘 ',
    'with NFL_PLAYER it gets better , so i vote for the drenchest puns',
    'NFL_PLAYER changed name to jesus christ hahaha BBR_MEMBER you like that',
    'fuck NFL_PLAYER went from having a dad to not fucking . yikes',
    'this NFL_PLAYER is really going to be the last thing in my ass',
    'i fucking hate NFL_PLAYER the danglo - saxon',
    'all i need is a wr talent and rb talent and wr talent NFL_PLAYER on the block',
    'hes actually not thick honestly NFL_PLAYER is not thick at all',
    'yessss BBR_MEMBER lmfao lets go NFL_PLAYER sodium dream stupid little little salt 🙀 🙀 🙀 🙀 🙀',
    'you better pray that NFL_PLAYER gets at least one needle i believe so yes',
    'NFL_PLAYER ! ! ! bron has these refs scamming jesus',
    'the whole league is not ok with NFL_PLAYER',
    "lol don't you say his whore ass name lol seriously ! ! ! ! ! fuck NFL_PLAYER",
    "i'm starting NFL_PLAYER this weekend... fuck ...",
    'NFL_PLAYER is getting beat up .... do n’t want it to be our virgin bbr bearer',
    'lollll also that\'s on him . maybe NFL_PLAYER should work at the dalvation army ? ? ?',
    'i will vouch for that birch , NFL_PLAYER is passed out',
    'that\'s fucked up BBR_MEMBER did you see NFL_PLAYER has another warrant out for 4 months ... gets my vote',
    'nothing feels better than NFL_PLAYER broke ass scoring huge empty tuts i love it',
    'over the last 3 weeks NFL_PLAYER has averaged a solid 48 fucking pts',
    'NFL_PLAYER is so fucked fuckkkkk. so ready for some fantasy drama',
    'god damnit this bitch aight. who wants NFL_PLAYER',
    'I think NFL_PLAYERs goal in life is to ruin mine'
 ]