MEMBER_RESPONSES = [
    'lolll ya boi BBR_MEMBER squirtin through ! !',
    'ya boy squirmit the frog frog frog',
    'breaking : BBR_MEMBER is squirming through the chat',
    'my fave volleyball duo : xannys and that ahh',
    'really loving the looks of this shit BBR_MEMBER!',
    'ooh yeah , a great paragraph from BBR_MEMBER would fuckin do me',
    'lollll BBR_MEMBER the only things guaranteed in life are ya boy',
    'congrats BBR_MEMBER ! ! ! !  the constant gardner i ’m loving this',
    'chyaaaa shenault me timbers! BBR_MEMBER in the ass !',
    '🙄 🙄 🙄 ✏ ️ 🍆 BBR_MEMBER i would',
    'BBR_MEMBER just send me the old dangle',
    'we fucking minshew mania this morning chats off mute love me some free moneyz',
    'by far thickest dick on my squad so thick fucking love that guy',
    'the j pebble is not amused get out of the bbr gutter we can do all things through christ',
    'yeeeeeessssss ! ! ! ! ! ! ! ! ! ! ! i\'m definitely losing to bry',
    'hey samantha , are you still in class ?',
    'for more scrill lol that\'s how 10th stays in 10th . i ’d rather ride that horse to hopefully 3 championships',
    'https://v.groupme.com/16191637/2019-09-01t17:12:06z/451b3748.320x568r.mp4 hahahaha one last thing - greg ’s been yelling spread the ched ',
    'tragic carpet slide changed name to linty fresh breath changed name to beyond scarred straight changed name to yikers island polls are tight',
    'poll \' when should we stick it in max \' has expired',
    'i swooped the panthis and they copped me a cool 4 points so ... loll ... well 😂 😂 😂',
    'huge bbr dick oh shit ya boy gagz in second seems like that would be crazy',
    'lmfao happy nye body shots   https://v.groupme.com/16191637/2020-01-01t06:51:52z/5db97339.568x320r.mp4 lolll',
    'still bangin father frank fuck yessssssss frankkkk the tankkkkk lollll frank is actually the bbr king lol ! !',
    'jah feel ... who u want for him ? not jah feelin . sorry b. ingram gon na be splittin time and dez too prone to injury . i never pussed out .',
    'raiders d looking savage ... words i never thought i would say',
    'can\'t win em all . three would be greedy frank the tiny tank goes down big dicks in the playoffs',
    'got suspended for fighting year of the thiqq thiqqqqqqqq tyreek what a freak ! that\'s so gofful',
    'oh nice . walsh missed another field goal .',
    'ass talk thursdays ftw ! lmao " sliding out on the low" ...',
    'just got my first trade rape offer of the morning . anyone want to top that ? yachty on the block',
    'yessssss i propose the following , please edit or amend wherever you see fit : 730pm : shotgun upon arrival',
    'lmao my desperate ass just picked him lol did n’t mean to send the luggage pic lolll yessss',
    'whoa whoa whoa i never said i was keeping it in lol fucking edison getting lit as a pioneer you\'re a pioneer',
    'pay the consequences karma ’s a bitch and then gets kneed in the head and neck area',
    'orlando is a hot bed of pussy for sure 😎 this guys a legend https://youtu.be/coyhsywrrqi',
    'i know . i ’m just super depeche mode i honestly do n’t care . there ’s no pic after all',
    'karma ’s a bitch and usually comes in the ass',
    'lol but make sure to wash you hands first before rubbing the scar .... when shit hits the fan , just rub that bbr scar',
    'i ’m gon na do 50 spit ups a day rock liking his own “ i m there ” comment is what it ’s like for a girl when guys asks for nudes all the time . this is almost more fucked',
    'trash , trash and more trash for a quality qb ? no thanks',
    'hey d ! thanks for that conviction',
    'i ’m partying still ! ! ! send a full vid or it did n’t happen',
    'i think i was   hacked',
    'damn lol yeah , it ’s about eating ass . thougt you ’d like it more if you were nervous',
    'should i be religious ? like ... why a loss ? right now ?',
    'no face ? bbr pics only i do n\'t know that the odds are fuckworthy',
    'should i propose or are we switching back to 0.5 pt ppr ? need to know',
    'motorboat some tits while we find out lish',
    'no one else cares about your self - fleece doing your best colorado buffs impersonation jah feel',
    'i\'m gon na be so pissed if i actually pull out a win i do what i can do lol',
    'i am outraged with a capital outie that view looks nice though ! dammmn what the actual fuck . 😂 😂',
    'sports emmy is in the mail today from my bank because they over charged me ! ya boi ai n’t married',
    'he ’s up on the block if anyone wants you guys see jets are trying to move bell ? ( would n\'t)',
    'who ’s got a nice thiqq receiver for me ? ?',
    'bbot gif rene is taking an l',
    'you know this lol i hate this game . just saying looking for a low key doris lurke',
    'good to hear that too ... im pretty fucking salty BBR_MEMBER',
    'lolllll if you didnt know my other teams name is curtains and drapes',
    'BBR_MEMBER i cancelled the trade , planet girth changed my mind',
    'you can all be my bottoms ! i dont remember lol',
    'just got even more stressed today . anyone near a computer that can log BBR_MEMBER the fuck on',
    'thats some real lishful bishful BBR_MEMBER',
    'update : taking LS to BBR_MEMBER',
    'BBR_MEMBER stranded on waivers island out here but I did update my mac book to mac chaos mojave 10.14.6 so we lit',
    'wow BBR_MEMBER driving all 5 cars that ran over the lake show',
    'now thats some good bbr roasting by an open fire 😂 😂 wmfllllgggggg lolol i cant get pierced bro',
    'you invited an outsider to join. meanwhile BBR_MEMBER simply mentionns thiqq and everyone loses their minds',
    'frankkkk the tankkkkk lollll BBR_MEMBER is 6 - 88 im not vetoing that shit',
    'need pics need pics need pics',
    'absolutely do not love to see it',
    'obviously BBR_MEMBER. there are only about 1000 messages in my ass right now',
    'BBR_MEMBER i love you',
    'the most overrated tight end in the draft order is BBR_MEMBER',
    'ya boooaaaooyyy shout out to BBR_MEMBER',
    'they fired my ass yesterday for having scobee dick 🤣 🤣',
    'lets just clear the air BBR_MEMBER, i am eating ass',
    'unbelievable BBR_MEMBER, and you have the nipple ring? mine turned green today',
    'brutal ! epic ! haha shit not even worried about the fleece BBR_MEMBER',
    'why BBR_MEMBER? lol i see a 7 am flight that could get you drunk but shoulda woodsa coulda',
    'lmaoooo a deep depression! ! another L for BBR_MEMBER !',
    'shoutout to my recent mediocrity',
    'lol get walsh on the phone and tell him were all in the building',
    'i like lurk nowitski better, nice job BBR_MEMBER',
    'lmfaooo broooooooo 🤣 🤣 🤣 🤣',
    'i just shotgunned back to back thick dicks BBR_MEMBER',
    '❤ ️ BBR_MEMBER lollll 😂 😂 😂 i ’m aware of human tight ends',
    'lit my roommates for sure gonna fleece you BBR_MEMBER!',
    '😂 😂 😂 BBR_MEMBER lolllll you need to get pierced this year tbh',
    'good ol college parties ... ill hopefully be there . rome was our inaugural pierced location',
    'im here boi bring the puss !',
    'fuckin BBR_MEMBER!! so lucky',
    'im gonna change your name to lil lishy the content fishy BBR_MEMBER ! ! you like that ass ? ? ?',
    'we should just txt him cause BBR_MEMBER probably will get the bbr',
    'im down BBR_MEMBER! lets fucking go stupid riccy',
    'dont mean to blow your mind BBR_MEMBER but im 2 fodies down already',
    '1 fodie down and i still have a hell of a redbox lineup. Get fucked BBR_MEMBER!',
    'a cute BBR_MEMBER ass 😎 😎 😎',
    'BBR_MEMBER! ! apple need to sponsor that ass! ! fuck! ! !',
    'BBR_MEMBER squirting through the chat . true professional',
    'lol BBR_MEMBER .. go climb mount bbr',
    'BBR_MEMBER missed his curfew last night so hes pretty much fucked',
    'BBR_MEMBER you gotta pay 4 that classic disney + drip',
    'BBR_MEMBER all eyes on you 👀 for some clarification here i ’d prefer to have that ass',
    'BBR_MEMBER wow ... yikes',
    'BBR_MEMBER theres a category 5 coming your way shmoop',
    'sounds like BBR_MEMBER wants in, we can put em on blast ?',
    'keep calm and sweat on, propose a bet and ill take it BBR_MEMBER',
    'I should prolly start gettin into it to someone other than BBR_MEMBER or walsh',
    'check my snap chat BBR_MEMBER 😎 😎 😎',
    'dont think i m a try to accommodate everyone BBR_MEMBER love it hahahaha',
    'nice doin business with you BBR_MEMBER',
    'fuck you BBR_MEMBER ... funny too cuz  lady fog horn raced two races earlier and won haha fuck ...',
    'it ’s a hopeless game we play haha were fucked BBR_MEMBER',
    'BBR_MEMBER its bbr not npr, who the fuck is down for nipple piercings next year instead of belly ?',
    'i dont even need to draft well BBR_MEMBER. just a little shade for the ride',
    'hahaha BBR_MEMBER my thiqq boy is firing on all cylinders',
    'i already fell in love with strippers once BBR_MEMBER, even the worlds greatest warriors lose a battle every now and then',
    'asquirmative',
    'update : almost tore my mcl',
    'great BBR_MEMBER that ’s goal 1 . i just said get fucked',
    'wow lol clambi clam margera space clam clam bam thank you mam also when was the last time anyone cleaned their belly button',
    'official: BBR_MEMBER will you be my aaron hernandez',
    'i bet BBR_MEMBER woulda taken that bet on stripper mud wrestling ',
    'BBR_MEMBER, again. that may be ticonderoga , but the girth has left the building',
    'so BBR_MEMBER... most people stay away from 3 rb committees lol',
    'batchley !',
    'ill get a belly update when you take that drape for a walk BBR_MEMBER',
    'cheddd 🧀 🧀 🧀 thanks BBR_MEMBER ! and the fast track to the needlejuice dang outs',
    'lmao ! ! ! ! ! BBR_MEMBER im dead',
    'lol BBR_MEMBER will be my little sobrina picking names venmo me $',
    'its all on me baby lets fucking go stupid riccy nice job last week BBR_MEMBER',
    'BBR_MEMBER let me put a shotgun or beer chug on tonight\'s game ? loser has to be at ladds at 930',
    'a fresh wound for BBR_MEMBER?? sign me up',
    'cmon BBR_MEMBER ! the suspense is killing me lol of course youre playing squirm edwards',
    'my ass hole gaping',
    'how bout you go ahead and give us another double barrel there BBR_MEMBER 🤣 🤣 🤣',
    'ok BBR_MEMBER, but loser has to sit in monday’s " god knows " corner lol',
    'BBR_MEMBER had to turn off mute cause im fuckin hard',
    'shout out to walsh calling BBR_MEMBER a wench',
    'wowowowowow u get better and i play some ass but i agree BBR_MEMBER',
    'the irony of a pencil thin like BBR_MEMBER talking shit ',
    'hahaha BBR_MEMBER! ! ! ! lookin like a dill(y) for your ass',
    'dang BBR_MEMBER if you did nt know ... i fucking hate this sport',
    'yea but you have fucking points on your bench BBR_MEMBER!!! goddammit lil kupp of stills water ... no bubbles',
    'as a bottom dweller myself, not fluffing yourself up is the shirtest way to go BBR_MEMBER',
    'now im for sure missing the playoffs BBR_MEMBER, incredible effort sir',
    'just adjusted and wtf the app is just torching me now goddammit fucking fuck',
    'the best part is when shit starts to go off on my bench. fucking stench goddamn',
    'i just got ousted from the playoffs so BBR_MEMBER imma take you out bruh! nothin but love everyone ’s been fleeced',
    'lol yeah dude i was literally a topic for weeks',
    'lmao!!!! yo the horse race thing is how we get big headed ... just my theory',
    'BBR_MEMBER just following you into your bathroom dude ^^ that man is a father 😂 😂',
    '4 mickey monday ? damnnn , we feeling a little far fetched BBR_MEMBER',
    'stakes are too high when ur names commish squirma ! ! collusion ! ! !',
    '? ? lol haha im feeling pretty good about getting my first pierce BBR_MEMBER',
    'im fucked up, BBR_MEMBER',
    'stupid little flamer!!! fuck!! me!!',
    'auto drafting ... eat that ass ! !',
    'i will be there BBR_MEMBER we fucked up',
    '! ! ! should be a bbr first and BBR_MEMBER just put me in the fridge',
    'BBR_MEMBER i smell bbr hole  😂',
    'its just live all year around flames. dont look at my phone',
    'my two starting rbs for the next month are fucking dead ? ?',
    'haha shout out to BBR_MEMBER your team is garbage',
    'dilly dilly ! ! boooaaoooaaaooooaaaoooaaaoooooaooooy',
    'sorry BBR_MEMBER lollll hahaha',
    'im a big sunday guy so still feeling good about it',
    'BBR_MEMBER tryin to sell high on either of the 2 aaron ’s in his ass',
    'little lish bish thinnbalina 😂 😂 😂 fishy lishy 😂 😂 😂',
    'a win without a flex?? i think thats weak BBR_MEMBER. youve got a redzone bone !!!',
    'update : im draft driving lol hold on',
    'eyawwwwww better get that sack boy eyawwww',
    'its so fucked that the waiver wire thiqqness has dried up in the past 3 weeks',
    'commish lolll gtfo what rules can we enact to get pierced at the beginning of the season',
    'damn do n’t vontaze me bro lol',
    '😂 i ca n’t wait to draft haha call me a winner boy',
    'shout out to me. secretly actually want the leagues top ass',
    'my team looks poised to explode for 75 points in 4 games this year . kind of fucked',
    'goddamnit . glad you re having fun BBR_MEMBER cause im not',
    'shit shit shit the mormon stabernacle choir wants to fuck',
    'no i dont have a final tomorrow.. for sure would get waxed',
    '😂 😂 😂 😂 😂 BBR_MEMBER lolll',
    '👏 👏 👏 BBR_MEMBER really appreciate that ass 😂 😂 ',
    '😂 ☝ 🏽 lol im dying BBR_MEMBER 😂 😂 😂 ',
    'eyawwwwww BBR_MEMBER if i do say so myself',
    'ok BBR_MEMBER as long as you whip ass later',
    'my thiqqies are thiqqy thiqq thiqq all up in that ass',
    'honestly you could use a good name change BBR_MEMBER. How about pencil dicks 👏 👏',
    'BBR_MEMBER , how does it feel to leave work and i ’m right there',
    '💃 🧂 just spreading the salt how do you do',
    'lolll i love when you get nominated BBR_MEMBER 🤝 thumbs in butts',
    'honestly though how many missed messages are in my ass right now',
    'i love being the first to get pierced ! the thiqqy ! weeliiih ahh fuck i am fucked',
    'chill ! i mean im not really down but its chill',
    'lolllllllll i saw the espn guys say that one is cleared from all salt. obviously I dont buy it',
    'im fucked play BBR_MEMBER next week',
    'breaking : BBR_MEMBER just vetoed my ass',
    'go ahead and veto my ass BBR_MEMBER',
    'quite indeed my good botch',
    'wow my thins are for sure setting the drenchmark this weekend',
    'impressive display BBR_MEMBER 💯 💯',
    'BBR_MEMBER im changing your name to brick boii so get the fuck over here',
    'BBR_MEMBER im changing your name to a gift from god ! i love it',
    '😂 😂 BBR_MEMBER is as fuck fuck shit fuck ! !',
    'if you have n’t seen the subway commercials . . . bro',
    'thank god scott hanson a savage yassss bish',
    'i won a global award today which was quite the ass tasting as you know BBR_MEMBER',
    'thank you BBR_MEMBER!',
    'BBR_MEMBER im changing your name to ass ass garoppoflowin 🐐',
    'bro the asian homie at lloyd i cant wait to see him',
    'shout out to the group . really wanna try and stop the fake news',
    'the bbr gods have spoken and im well and truly fucked',
    '^ confirmed no , ur team ... well and truly fucked',
    'fuck my life .... i am a little tuesday update for the league',
    'breaking : i thought i changed your name to the dangle submarine',
    'catch a ride from eugene it searches all the flights at once. my thiqqies will come through',
    'i mean health is wealth BBR_MEMBER you need that ass',
    'the gallery 😂 😂 😂 im dying',
    'breaking : you can get hiv and scabies if you dangle on your defense',
    'flames just do nt look at my crib, anyone in pdx wants to wax this bitch? ?',
    'season 5 : dexter mcfourty changed name to randall slobb 😂',
    'ok saline dion lol',
    'schefter : my asshole is gaping',
    'BBR_MEMBER trying to pull off a huge scandal  ... but yea ill change',
    'i ’ll call the homie his home dropped 40 points last week',
    'just following in your lackluster footsteps BBR_MEMBER 😘 hearts all around',
    'BBR_MEMBER strikes again ! 🔥 🔥 most valuable belly my hole is a jalapeño now',
    'ok thats fine lets gooooo ! and i " act crazy " lol',
    'one sec, draft driving',
    'haha damn. indica? sativa?',
    'i ’m too fragile to bet em ! crank crank ! hahaha fucking love that',
    'i ’m rooting for you BBR_MEMBER ! rip that ass boiii',
    'nice . BBR_MEMBER missed another field goal . that s some booty',
    'oh nice . BBR_MEMBER makes a benjamin and now everyone makes valid points',
    'or what ? bbr pic ? thats what i thought BBR_MEMBER',
    'kim jung actually could nt care less, just accept it',
    'what is the status of the cameras at the store i need to set my lineup',
    'alright let ’s fucking gooooo congrats BBR_MEMBER !',
    'meanwhile BBR_MEMBER is busy benching himself',
    'wowwwww setting the drenchmark drench wet no comparison 💯',
    'BBR_MEMBER im changing your name to thiqq flosskowski. my thiqq of course',
    'my only rbs now are blacked out 😂 😂',
    'fuck my fucking pencil squad',
    'lollll fleeced BBR_MEMBER',
    'BBR_MEMBER im changing your name to tugs bunny',
    '😂 wowzers BBR_MEMBER can we get a shotgun',
    'sounds good BBR_MEMBER? i ’ll take it deep flesh mode',
    'we might as well BBR_MEMBER lol lish is just a picture of cj anderson! lolll fucking bang',
    'we\'ll see, only problem is i always take veteran qbs in the waiver rules and get properly fucked',
    '? um ya. nice to see BBR_MEMBER doing BBR_MEMBER things',
    'BBR_MEMBER is an honorable man, doesn’t even know the belly count',
    'this game is so whack .. : at least let me leave',
    'lmfao he knows it\'s a bold strategy cotton ! BBR_MEMBER shall we carpool?',
    'puss pic ! ! i just call him premium',
    'and b dubs pre pre bbr! ! ! we actually met the ceo of gucci and his ass fired my ass yesterday',
    '😂 😂 my girlfriend just noticed that my team needs some facial punishment',
    'lit! ! sept first is about 6 hours long too many fucking commercials',
    'he\'s definitely the bbr closeup king, frank the wife must be after both goff and cooks',
    'yeeeeessssss well played mr . xantastic baller so dumb . super chill thanks for the fifty BBR_MEMBER',
    'fuck ! ! ! fuck ! ! !',
    'happy new year from miami ! ! ! ! ! ! ! i just creamed',
    'rctid ! ! ! ! i hate my life',
    'gail the snail do over. need pics',
    'amazing love it ! where dat peppa at tho',
    'update : i didnt have to hear about that',
    'emannual mudiay every week ( top 15 receiver)',
    'fuck !!! BBR_MEMBER my butt chugs !! the algo ! !',
    'life is a saturday ... eyawwwww that bbr is looking like marc davis long lost son',
    'tomorrow separates the pencil dicks from the thicks touché touché botches touché indeed botch touché botch',
    'gimme all the john hardbaughd # bde',
    'the seasons been cray already ! ! ! ! ! ! ! ! ! i won ! 😂 👌 #anticipated',
    'BBR_MEMBER straight fleecing the bbr squaw > dani dustmuffin',
    'hmm BBR_MEMBER, sounds like a guaranteed infection but there are a lot of bosses. did n\'t spill a drop this time 😂 😂airlines just forcing the homies to take ls this weekend ? ?',
    'lmao BBR_MEMBER your new nick is literally just kyle fuckin rudolph',
    'give me a sweet lickery kiss BBR_MEMBER !!',
    'damn the navel cave diggers came to play',
    'the chat ! i wonder if they would pierce the squirma',
    'let ’s dumb it down. im getting head with the bbr wish list : ( 1 carry , 0 yds )',
    'almost as embarrassing as these election results wow 😳 proof BBR_MEMBER hates trading',
    'man i used to say that. BBR_MEMBER is about to post some shit right now',
    'Got yaboooaooooyyyyy BBR_MEMBER 😂 😂 ',
    'i know BBR_MEMBER! honestly such a good look lol',
    'i dont believe anyone cares about the playoffs 😂 the fear is real once again lol the only thing saving me is fucking',
    'like holy shit i have all 4 patriots running backs this year 🙃 🙃',
    'jah feel jah feel feel jah feel jah feel jah feel',
    'i feel violated u wore a condom right BBR_MEMBER?',
    '😂 lishful thinking BBR_MEMBER we def need to involve vegas',
    'ive eased into 2 acquisitions who are you offering iv lubed up 2',
    'we live in a society . 😂 😂 👏 🏻 im getting shit on . bring fresh belly blood',
    'you fools always come through for me hahaha',
    'chya ed sheering over here, developing our own fleece scale',
    'more worried about your dick than your bbr BBR_MEMBER',
    'brother ! ! ! got love for you even BBR_MEMBER though you wo n’t even take contact . i would nut',
    'schefter : ya boy is exancipated 😂 🔥 💯 👌 ',
    'brooooo i have enough beef to cook dinner',
    'update : fantasy is live ! ! from the guys who brought you chris brown',
    'how do you feel my yeast mode pain . well played belly boys lishkey on the beat',
    '😂 😂 see above pic of your chick licking whip cream out of that tiny tiny',
    'cheeky boi! look at rosters guys not records',
    'let’s slay ball right after if that does n’t sound falawful',
    'yams in that ass ... if hes on your roster then i dig the enthusiasm',
    'hard to even contemplate . hope you ’re the size of an era  👌 ',
    'i really like it already ! did anyone watch the ducks game',
    'the only notifications on my phone for like 5 years running have been ass',
    '“ the autumn wind is a meltdown of the lish',
    'we smoke ? all im saying , i offer better trades than is ibm watson ! !',
    'a kangaroo race ? can you get a dangle without risn of infection ? props no matter what',
    'group chat never stops .... year around flames dont feel great no sir hahahaha',
    'just send me your thiqqest wideout and i ’ll take the stuffing',
    'such a pencilitis piece of shit',
    'i love that you fools always come through where y’ all starting ? https://www.talkbasket.net/54299-jimmy-butler-im-taking-a-fcking-shower-i-cant-wash-my-ass we fucking',
    'the finest BBR_MEMBER! but are you sure stretchem',
    'i mean zevior what did ze do ? who even cares at this point its complete ass',
    '🏌 🏻‍ ♂ ️ damn it ! fucccccck i ca n\'t , just livestream the whole day bitch',
    'got a little morton ’s midway majesty for ya',
    '? lollll do n\'t we do a league where last place has to take trav out',
    'lol i ’m so juiced right now ! ! ! ! ! ! ! ! wow instant bbr classic',
    'thick .',
    'juicy ... jerry juicy really loving the looks of this',
    'BBR_MEMBER im changing your name to bill walton commentates a basketball game',
    'tough scene and you counter by claiming you ’re 6 - 0 lol',
    'the full sheep fleece in effect rikki thiqqi tavi comish',
    'vincent cam gogh strikes again ! new orleans d again ! unreal lol',
    'goskoski gags !',
    'first round pencil thins made fun of me for drafting a thiqq receiver 😂 😂',
    'wow trade rape me and get some haribo tummy bears. shout out to marlon mack ’s achilles',
    'lmao the salt of the girth has left the shaft unlike bananas in pajamas aka i still feel nothing',
    'absolute scenes oh wow 💕 thoughts and prayers',
    'crushing it lol i feel like i m blacking out in the teal ? lol dr . zoooooos ! the gods are against me',
    'the real thin shady lookin thicky ! pats get 1 more w 😂 😂 😂 rene , do n’t clench',
    'we lit . most valuable belly my hole is ready',
    'next monday BBR_MEMBERs gettin pierced . location tbd . fuck comcast ! ! !',
    'BBR_MEMBER is torching the chat 😂 😂 😂 😂 😂 let that be a lesson',
    'hot take 🔥 🔥 🌊 🌊 ! somehow BBR_MEMBER whips dat thiqqness',
    'yea, BBR_MEMBER is definitely fingerbanged',
    'looking good to me.. BBR_MEMBER! BBR_MEMBER !',
    'fleeced wow what a fleece. Fuckin BBR_MEMBER',
    'hey BBR_MEMBER remember that one time you benched my ass and got shit on 😂 😂',
    'go up the stairs to the 5th floor hit knot springs when you get here there is a chance you ’d have to have sex with this person to get in',
    'yes i am sad . must be rough having your bench draped in thiqqness BBR_MEMBER',
    'just had a look at BBR_MEMBER roster again . so fucking girthy',
    'BBR_MEMBER you irked you did n\'t eat the gilly weed and start him ? gill the thrill !',
    'i mean he\’s a modern day breida kahlo i think we \'re better off banking on brian heartline and buck allen falling down',
    'if we know ur name in this chat you fucked up lolll',
    'this is my casino .... thought i was gon na get it done all year for ya i\'m all for big tits powerball',
    'i ’ll even throw in olsen BBR_MEMBER wanna ride it all night long ! ! life is a highway',
    'lmao rather it be you than most in this group BBR_MEMBER . what a beautiful night . thanks for the fifty',
    'what ’s in store? lol huge loss . league goes on . bring fresh belly blood',
    'love ittttttt ca n’t draw it up any better ! ! ! 4 virgin bellies ',
    'my mans tryna pump n dump the chat lol',
    'lolllll 😂 salt 😤 😤 😤 😤',
    'there is a winner ? what a guy . ca n\'t escape this guy eyaw next year next year jesus next year',
    'ca n\'t wait til 10 years from now when everyone\'s picture is a picture',
    'oh im getting some youtube notifications ? solid',
    'we betting talking and not backing it up? classic you',
    'my bench is full of pencil dicks i just need the thickness to keep my number 2 spot 😂 😂 😂',
    'BBR_MEMBER i got some flames you wo n\'t be controversial at all !',
    'he was healthy and on the ground. super hole sunday ! !',
    'kittles “ taste the receptions ” nuclear families typically have 1 - 2 kittles ah kittle sticks',
    'well cam newton just tested positive too lol as someone who has hiv , you ’d probably want to wear a condom right ?',
    'first game is falcons eagles - saw that and popped a full chub your god damn right i am this bb is ready for the season',
    '😂 😂 glad you ’re feeling confident BBR_MEMBER',
    '😂 😂 stretching it BBR_MEMBER . go 5 yards and i\'ll risk it',
    'currently taking a 90 pt l ...',
    'BBR_MEMBER answer for your crimes! i ’ll move on. bitch',
    'loving the production from BBR_MEMBER',
    'holy fuck BBR_MEMBER, the league should be sponsored by tums',
    'we were in oliver thurns bathroom off division and BBR_MEMBER came in and cracked my ass open',
    'hey BBR_MEMBER throw me a trade offer slut',
    'big 🍆 BBR_MEMBER ! ! !',
    'keep watching those projections wow BBR_MEMBER you got me hard',
    'I like BBR_MEMBER quite a bit. even if you dont wow, such a fucking stocking stuffer ! ! ! !',
    'fucking BBR_MEMBER ..... hunting for my ass',
    'BBR_MEMBER runs a classic route to danglin 😂 😂 ',
    'yessss BBR_MEMBER lmfao lets go sodium dream stupid little little salt 🙀 🙀 🙀 🙀 🙀',
    'hey BBR_MEMBER, you wanna score a few and bring that ass down . where u at playa ?',
    'lol BBR_MEMBER is gonna dust me either way. im about to get dan baileyed and ive never even heard of that',
    'fuckkkkkkkkkkkkkkk BBR_MEMBER . he ’s fucking fire cherry birch cream lol birch cream ! ! !',
    'bottom power power bottom lmao put some respeck on that bottom good man nothing wrong with being on bottom',
    'fuck the cowboys ready to whoop that yoda bb',
    'how many hours did you spend in there that \'s fucking lit ! ! !',
    'hahaha touché ! ! well played BBR_MEMBER . a nice bottle of cab there yes',
    'trust the process . trying to weed out that kinda negativity and see whose tryna get wet',
    'greg ’s squad is real temporary greg ’s squad is non consensual can you stop with the all caps 🧢',
    'd , i m a need valentina to get on the phone with mike t and tell him to suck it up later this is a meltdown of epic proportions',
    'squad will be down with the thickness again soon " you\'ve been chopped " acquisition kitchen',
    'if douches eat dat azzz gurr ... i \'m trippin yea , fsure !',
    'crab legs with a vintage sack lolll too thiqq love a low key thiqqness',
    'bro i got waxed by 2 trades this week . i think your definitely on the short list for the same reason - walsh ’s weekly secondaries please',
    'incredible content BBR_MEMBER . pit loved it little macy ’s day floater in the shot',
    'trade talk monday let ’s go BBR_MEMBER ! 10 more points ya boy is flaming hot fuck',
    'teal 4sure teal deal done real deal teal is in we are thinking teal vote for teal or purple bbr ? ? ?',
    'lol my fave character from westworld is maeve aka xandi newton lolll we got xanley steemer up in here',
    'get out of his xanny slumber so we can relive some blazers losses ? lol https://twitter.com/seeratsohi/status/1240359989740355584?s=19',
    'clam . i would start squeezing your abdominals because in about a month they will be the subject of extensive footage at a mall in portland clam newton ! ! ! !,'
    'yes ! man i wish i was pondering this',
    'never had a losing record in bbr .. floating like a bellyfish out to sea, back from the beach',
    'i ’m driving back from the coast now . eta 4 pm so take some rxtra shots and delay things !',
    'i have a banging headache and the light hurts',
    'muscle hamster looking litty we muhfuggin inkin gurr we out here inking ass gurr ! we inked gurr done been inked 🍆',
    'i \'m draft driving lol this is rough ... piercing * * # wantthepiercinh # draftingdrunk',
    'you would you stupid lil floutie',
    'hungry rosenbagger ? bring in henry rowengartner !',
    '• just liked my own post in a classic plot twist. love everything about this BBR_MEMBER ! just incredible 👏'
]

PLAYER_RESPONSES = [
    'BBR_MEMBER? NFL_PLAYER is about to drop 69 points lol',
    'hot take 🔥 🔥 🌊 🌊 ! somehow he whips dat thiqqness NFL_PLAYER eatin fo sho',
    'yaaaaaasssssss ! ! ! ! ! ! hoping for a NFL_PLAYER tut hey hey',
    'holy fuck NFL_PLAYER in the league should be sponsored by tums',
    'dude i got hot for NFL_PLAYER for about a week its fucked',
    'NFL_PLAYER wants to make a lish foundation game time boys',
    'sco NFL_PLAYER!!!! 😟 or not lol',
    'heres a moment: when NFL_PLAYER get more snaps, we get more money',
    'should be a nice handcuff for NFL_PLAYER ur gucci',
    'i like him but he for sure gets hurt and NFL_PLAYER gets bageled if that happens',
    'NFL_PLAYER 😂 lolll there we go good shit. hey BBR_MEMBER throw me a trade offer slut',
    'we all know NFL_PLAYER is a slut vulching all them tutties',
    'i heard BBR_MEMBER had sex with NFL_PLAYER and i said lol',
    'bench NFL_PLAYER then too , even with all the spam this morning his '
    'thiqqness is not playoffs level',
    'BBR_MEMBER come join me . i feel your pain there ! NFL_PLAYER is trash',
    'hola! NFL_PLAYER changed his name to dangleberries i hate this',
    'yo. seeing NFL_PLAYER out there is working for me',
    'NFL_PLAYER. wow. my ass!!!',
    '😂 BBR_MEMBER you just did n’t want me to swoop NFL_PLAYER',
    'lol NFL_PLAYER is whack as fuck',
    'NFL_PLAYER was drafted .... hot garbage charky baby',
    'the NFL_PLAYER injury hurts , BBR_MEMBER batch what are you talking about gtfo',
    'wow NFL_PLAYER tho lfg yesss ! another auto draft team in bbr, call me mr . tummyness winner hands',
    'NFL_PLAYER is more like clickbait than anything else. and im definitely not '
    'one of ur notifications dumbass',
    'NFL_PLAYER on the block',
    'fuckkkkkk so whack when the fuck is a tie better than a torn achilles for NFL_PLAYER',
    'NFL_PLAYER on the bench! the fuck are you thinking',
    'NFL_PLAYER is a bum BBR_MEMBER but I would hit him up for ass at least',
    'BBR_MEMBER is deff doing butt stuff with NFL_PLAYER this weekend while my ff team takes another l',
    'im still interested in NFL_PLAYER ? ? ? wtf is wrong with me',
    'NFL_PLAYER is a power bottom lmao put some respeck on that 😂',
    'BBR_MEMBER take an offer for NFL_PLAYER if ya can cause i hate you starting his ass',
    'lolll looby dooby NFL_PLAYER dewing me dirty damn',
    'NFL_PLAYER just isnt lit he got hurt in the pit',
    'honestly after NFL_PLAYER shits the bed first week id be down for whatever',
    'NFL_PLAYER is working with a delivery service in my ass',
    'good stuff from NFL_PLAYER. love watching football players punch each other '
    'honestly NFL_PLAYER shouldnt be on the same team as my opinions',
    'nah i have faith in NFL_PLAYER looks like ... a very enticing fuck',
    '😎 🏌 🏻\u200d ♂ ️ lollll i wanna get that shit on with NFL_PLAYER',
    'NFL_PLAYER could do the same shit every year, ive cleared out a few blowjobs already',
    'NFL_PLAYER is no splashed potatoes 🥔 to the bench ! ! !',
    'NFL_PLAYER looks like such a queef ... but he did go beast mode on his last tug',
    'NFL_PLAYER sucks for opportunity i need a streetsweeper out chea',
    'BBR_MEMBER are you hating NFL_PLAYER being on your own supply',
    'NFL_PLAYER is dry mother fucking piece of shit what happened to him ?',
    "my rbs were wrecked but NFL_PLAYER's thick hog has given me life",
    'BBR_MEMBER 😂 😂 😂 😂 😂 NFL_PLAYER ? i ’ve seen him',
    'is NFL_PLAYER about to get some penetration in? no ...',
    'i ’ll be there about 115 lets just see NFL_PLAYER throw tugs',
    'no i m not jah feelin NFL_PLAYER',
    '💩 dude same thing get NFL_PLAYER on the ballot',
    'the saltiest of posts 😂 😂 it does make up for NFL_PLAYER so.. we lit',
    '? ? NFL_PLAYER . Bro ! classic i would trade any of my thiqqs . whoever',
    'another big performance from BBR_MEMBER ! ! ! ! ! NFL_PLAYER fucks',
    '! stretchemmm x2 ! ! ! ! go ducks cant believe i dropped NFL_PLAYER',
    'you check this chat ... group therapy for NFL_PLAYER',
    'all im saying is dont do it in the tunnel with NFL_PLAYER',
    'ay BBR_MEMBER, signed and sealed. NFL_PLAYER is like the shittier version of danny woodhead',
    'NFL_PLAYER .. its every fuckin sunday with this shit',
    'the fleecer and the shit is real i was trying to beautiful mind my way through this NFL_PLAYER performance',
    "😂 NFL_PLAYER is 6'3 maybe , and that ’s a whole schpiel",
    'fuck that sucks for NFL_PLAYER . and my belly?!?',
    'take me back to portland tomorrow , fuck ! hahha NFL_PLAYER sucking it',
    'NFL_PLAYER is an emergency . fuck canned beans , this shit sucks!!!!',
    'fucking fuck what\'s happening on waivers . right after picking up NFL_PLAYER too',
    'stfu fucking garbage NFL_PLAYER getting dropped first thing in the morning',
    'BBR_MEMBER you told me to trade NFL_PLAYER ! ! ! !',
    'lol NFL_PLAYER is about to ruin the whole season',
    'NFL_PLAYER is his own stable',
    'NFL_PLAYER?? please ink the deal BBR_MEMBER!',
    'batchley ! NFL_PLAYER fucks!',
    'NFL_PLAYER not killing it so y’ all can take him this season . #foreverscarred',
    'holy fuck NFL_PLAYER.. hey BBR_MEMBER, you wanna score a few and bring that ass down . where u at playa ?',
    'suck this drenchcoat birch drench * * * can NFL_PLAYER just show up tonight fuck',
    'lolll i ca nt blame NFL_PLAYER i respect the drip too much. to my chagrin',
    'NFL_PLAYER is probably the weakest thing ive ever been ok with',
    'hmmmm interesting fleece. although NFL_PLAYER feels more slated as a self - fulfleecing prophecy for me but i ’ve also been so nasty',
    'i already am a contender me giving you NFL_PLAYER would make you lose even more bitch',
    'see this NFL_PLAYER fool on memphis shorts ? delishous content here planet lish it keeps him warm in the winter',
    'internet gettin wild on NFL_PLAYER today . just the right amount of fuck lol',
    'yupppppp one more fg baby NFL_PLAYER is an absolute toss up. codeine zuerlean we lit',
    '🤤 jesus please send NFL_PLAYER to the university of pouregon',
    'NFL_PLAYER, a legendary both sides of the fence fuccboi',
    'damnnn . everyone puttin money on NFL_PLAYER now huh',
    'im just saying lmfao ... how lucky can one guy be ... fucking NFL_PLAYER',
    'the most overrated tight end in life but in fantasy.. is NFL_PLAYER really not following through wtf',
    ' 😂 ☝ 🏽 lol NFL_PLAYER likely tore acl too . all things sucking right now',
    'damn. NFL_PLAYER looks like he has the worst liver ever',
    'yes NFL_PLAYER is super thiqqy stupid thiqqy lol im too high lol',
    'lol NFL_PLAYER is gonna dust me either way. im about to get dan baileyed and ive never even heard of that',
    'wow thats wack . NFL_PLAYER on IR cause of shotguns in the pit ? ? ?',
    'fr we all know you hate NFL_PLAYER BBR_MEMBER',
    'NFL_PLAYER isnt going anywhere he a super thiqqy stupid thiqqy',
    'shoutout to me for benching NFL_PLAYER in my other league 😂 😂',
    'theres still hope! two thoughts: NFL_PLAYER is fucking',
    'wow ya boy NFL_PLAYER created new poll: would you say you mustache?',
    'sorry BBR_MEMBER. NFL_PLAYERs value just went up haha im smackin asses fuff sho',
    'nah i d be willing to bend over backwards and give NFL_PLAYER the old fml',
    'clam stew is more valuable than NFL_PLAYER',
    'NFL_PLAYERs best weeks were on your team fuckkkkkkkkkkkkkkkkkkkk',
    'lets go NFL_PLAYER ! had no choice but to be honest',
    'i see you ’re schwarmin ’ up to NFL_PLAYER 😘 😘 ',
    'with NFL_PLAYER it gets better , so i vote for the drenchest puns',
    'NFL_PLAYER changed name to jesus christ hahaha BBR_MEMBER you like that',
    'fuck NFL_PLAYER went from having a dad to not fucking . yikes',
    'this NFL_PLAYER is really going to be the last thing in my ass',
    'i fucking hate NFL_PLAYER the danglo - saxon',
    'all i need is a wr talent and rb talent and wr talent NFL_PLAYER on the block',
    'hes actually not thick honestly NFL_PLAYER is not thick at all',
    'yessss BBR_MEMBER lmfao lets go NFL_PLAYER sodium dream stupid little little salt 🙀 🙀 🙀 🙀 🙀',
    'you better pray that NFL_PLAYER gets at least one needle i believe so yes',
    'NFL_PLAYER ! ! ! bron has these refs scamming jesus',
    'the whole league is not ok with NFL_PLAYER',
    "lol don't you say his whore ass name lol seriously ! ! ! ! ! fuck NFL_PLAYER",
    "i'm starting NFL_PLAYER this weekend... fuck ...",
    'NFL_PLAYER is getting beat up .... do n’t want it to be our virgin bbr bearer',
    'lollll also that\'s on him . maybe NFL_PLAYER should work at the dalvation army ? ? ?',
    'i will vouch for that birch , NFL_PLAYER is passed out',
    'that\'s fucked up BBR_MEMBER did you see NFL_PLAYER has another warrant out for 4 months ... gets my vote',
    'nothing feels better than NFL_PLAYER broke ass scoring huge empty tuts i love it',
    'over the last 3 weeks NFL_PLAYER has averaged a solid 48 fucking pts',
    'NFL_PLAYER is so fucked fuckkkkk. so ready for some fantasy drama',
    'god damnit this bitch aight. who wants NFL_PLAYER',
    'I think NFL_PLAYERs goal in life is to ruin mine',
    'fuckkkkkkkkkkkkkkk NFL_PLAYER . he ’s fucking fire cherry birch cream lol birch cream ! ! !',
    'why ? ? ? lol fuck you NFL_PLAYER fucking fuck face',
    'indeed . j - rock circa 2017 no one wants that smoke smokahontas'
 ]