STALLERS = [
    'one sec ...',
    'hmm not sure,',
    'gimme a moment ..',
    'my bad,',
    'sorry,',
    'thats a tough one,',
    'fuck, sorry,',
    'shit, sorry,',
    'one moment please,',
    'hold on,',
    'umm,',
    'hard to say,',
    'cant say,',
    'cant think right now,',
    'hold please,',
    'no idea,',
    'hmmm.. sorry,',
    'cant think about that right now,',
    'eyawwwwww,',
    'chyaaaa,',
    'ummmmmm,',
    'uhhhhh,',
    'sorry one sec,',
    'hold up,',
    'wait up,',
]