STALLERS = [
    'one sec ... shit,',
    'hmm not sure, damn,',
    'gimme a moment .. ugh,',
    'one minute, oh, wow,',
    'oh shit hold on,',
    'thats a tough one,',
    'fuck, sorry,',
    'shit, sorry,',
    'one moment please,',
    'hold on,',
    'umm,',
    'hard to say,',
    'cant say,',
    'cant think right now,',
    'hold please,',
    'no idea,',
    'hmmm.. hard to say,',
    'cant think about that right now,',
    'eyawwwwww,',
    'chyaaaa,',
    'ummmmmm,',
    'uhhhhh,',
    'one sec,',
    'one sec, ah shit,',
    'hold up,',
    'wait up,',
    'wait up, wtf,',
    'just a sec,',
    'just a moment,',
    'ah fuck,',
    'ah fuck, hold on,',
    'shittt, one sec,',
    'goddammit, one sec,'
    'one sec, fuck,',
    'ahhhhhhhh shit,',
    'oh man,',
    'chyaaaaa, one sec,',
    'eyawwwww, one sec,',
    'brb,',
    'gotta go,',
    'sorry gotta go,',
    'sorry brb,',
    'umm, one moment please,',
    'whoa, hold on a sec,',
    'ahh shit, umm,',
    'well, ahh fuck, ',
    'ah shit wtf,',
    'cant think right now, fuckin',
    'oh wtf,',
    'bro wtf,',
    'you gotta be kidding me',
    'are you shitting me',
    'man, wtf,',
    'chyaaaa, oh fuck,',
    'ummmmmm, wtf,',
    'jesus christo,',
    'jesus,',
    'christ,',
]