STALLERS = [
    'one sec ...',
    'hmm not sure,',
    'gimme a moment ..',
    'one minute,',
    'oh shit hold on,',
    'thats a tough one,',
    'fuck, sorry,',
    'shit, sorry,',
    'one moment please,',
    'hold on,',
    'umm,',
    'hard to say,',
    'cant say,',
    'cant think right now,',
    'hold please,',
    'no idea,',
    'hmmm.. hard to say,',
    'cant think about that right now,',
    'eyawwwwww,',
    'chyaaaa,',
    'ummmmmm,',
    'uhhhhh,',
    'one sec,',
    'hold up,',
    'wait up,',
    'just a sec,',
    'just a moment,',
    'ah fuck,',
    'ah fuck, hold on,',
    'shittt, one sec,',
    'goddammit, one sec,'
    'one sec, fuck,',
    'ahhhhhhhh shit,',
    'oh man,',
    'chyaaaaa, one sec,',
    'eyawwwww, one sec,',
    'brb,',
    'gotta go,',
    'sorry gotta go,',
    'sorry brb,',
]