SUFFIXES = [
    'lets gooooo!',
    'scoducks',
    'lol',
    'it gets better',
    'better get that ass',
    'we gucci',
    'we lit',
    'we lit!',
    'we litty gurl',
    'wmflg',
    'wmflggg',
    'lets shotgun',
    'id bet on that',
    'you sound salty lol',
    'broo',
    'bro.',
    'my bro',
    'my good bitch',
    'in the ass',
    'but why',
    'king!',
    'it slaps',
    'a real slapper',
    'lets go!',
    'flames',
    'we flames',
    'so yea',
    'fuck!',
    'stupid little flamer',
    'stupid little riccy',
    'flamer!!',
    'lmao',
    'lmao',
    'fuckin lmao',
    'lol',
    'lolll',
    'fuckin lol',
    'loll',
    'bish',
    'ya bish',
    'botch',
    'batchley',
    'fuckin lol dude',
    'fuckin lol',
    'shit slaps tbh',
    'if i do say so myself',
    'fleeced',
    'fucking fleeced',
    'that\'s some booty',
    'complete booty',
    'not thick at all',
    'not thick',
    'thick!',
    'thiqq',
    'thicc',
    'thiqq boy',
    'fucking thiqq!',
    'yuuuge lol',
    'something to ponder',
    'you 👏 love 👏 to 👏 see 👏 it 👏',
    'the effort is treal',
    'its actually pancake thin',
    'blackballed for life',
    'brady on the block',
    'stupid lil floutie',
    'so fucking girthy',
    'pencil dicks',
    'may the bbr gods have mercy',
    'yeboay',
    'yeboaoy',
    'yebooaaooy',
    'ya boy',
    'lets fucking bang!',
    'rip that ass boii',
    'quite indeed my good botch',
    'dilly dilly!',
    'im so fucked up lol',
    'lmao!'
    'fuck the cowboys',
    'bbr pic?',
    'yikes'
]