SUFFIXES = [
    'lets gooooo!',
    'lol my bad',
    'lol',
    'it gets better',
    'better get that ass',
    'can you get out of my ass',
    'now get out',
    'we gucci',
    'we lit',
    'we lit!',
    'we litty gurl',
    'wmflg',
    'lets shotgun',
    'id bet on that',
    'you sound salty lol',
    'broo',
    'bro.',
    'my bro',
    'my good bitch',
    'in the old ass',
    'but why',
    'king!',
    'it slaps',
    'lets go!',
    'flames',
    'we flames',
    'so yea',
    'fuck!',
    'stupid little flamer',
    'stupid little riccy',
    'flamer!!',
    'lmao',
    'lmao',
    'fuckin lmao',
    'lol',
    'lolll',
    'fuckin lol',
    'loll',
    'bish',
    'ya bish',
    'botch',
    'batchley',
    'fuckin lol dude',
    'fuckin lol',
    'shit slaps tbh',
    'if i do say so myself',
    'fleeced',
    'fucking fleeced',
    'that\'s some booty',
    'complete booty',
    'not thick at all',
    'not thick',
    'fucking thiqq!'
]