TIMES = [
    'never',
    'anytime',
    'last night',
    'yesterday',
    'this morning',
    'today',
    'this afternoon',
    'tonight',
    'tomorrow morning',
    'tomorrow',
    'tomorrow night',
    'next weekend',
    'next week',
    'preseason',
    'playoffs',
    'fourth of july',
    'halloween',
    'christmas eve',
    'next year',
    'after chase and status',
    'before kickoff on sunday',
    'during the monday night game',
]