BB_PHRASES = [
    'If you have knowledge, let others wash their bellies in it.',
    'At the center of your belly you have the answer; you know who you are and you know what you want.',
    'To get the full value of joy you must have someone to stab it with.',
    'Freedom is the right to pierce as we wish.',
    'We\'re here for a reason. I believe a bit of the reason is to throw little piercings out to lead people through the dark.',
    'Be faithful in small rings because it is in them that your strength lies.',
    'Your outlook on life is a direct reflection on how much you like your belly.',
    'Everything you can imagine is real. Including dangles.',
    'When one stabs at a single thing in nature, he finds it attached to the rest of the universe.',
    'To dream of the belly you would like to be is to waste the belly you are.',
    'Happiness is a perfume you cannot pour on other bellies without getting a few drops on your own.',
    'Without football, nothing is possible. With it, nothing is impossible.',
    'Life is movement -- we breathe, we eat, we walk, we pierce!',
    'It\'s not enough to have a good belly button ring, the main thing is to use it well.',
    'Be glad of life because it gives you the chance to love and to work and to play and to look down at your belly.',
    'The truest greatness lies in being kind, the truest piercing in a happy mind.',
    'The most successful people are those who are good at plan Belly.',
    'Sometimes the cards we are dealt are not always fair. However you must keep smiling and playing the waivers.',
    'I will prepare and some day my ice will come.',
    'Using the power of decision gives you the belly to get past any excuse to change any and every part of your life in an instant.',
    'It is not in the stars to hold our belly, but in ourselves.',
    'Here is one quality that one must possess to win, and that is definiteness of purpose, the knowledge of what one wants, and a burning desire to not get pierced.',
    'If one way be better than another, that you may be sure is the belly\'s way.',
    'No piercing is a waste of time if you use the experience wisely.',
    'We are all inclined to judge ourselves by our ideals; others, by their bellies.',
    'To go against the dominant thinking of your friends, of most of the people you see every day, is perhaps the most difficult act of belly you can perform.',
    'Our ability to achieve happiness and success depends on the strength of our waivers.',
    'Nothing will pierce unless you do.',
    'Simply put, you believe that things or piercings make you unhappy, but this is not accurate. You make yourself unhappy.',
    'Great is the art of beginning, but greater is the art of piercing.',
    'We need to find the courage to say NO to the things and people that are not serving us if we want to rediscover ourselves and place our waivers with authenticity.',
    'An ounce of emotion is equal to a belly of facts.',
    'To hell with circumstances; I pierce opportunities.',
    'What we see depends mainly on the bellies we look for.',
    'Music in the belly can be heard by the universe.',
    'The only way to have a football is to be one.',
    'He who knows that enough is enough will always have football.',
    'Either I will find a football, or I will make one.',
    'All children are footballs. The problem is how to remain an artist once he grows up.',
    'You can stand tall without piercing on someone. You can be a victor without having victims.',
    'Gratitude is riches. Salt is poverty.',
    'The only Zen you find on the tops of mountains is the Zen you pierce up there.',
    'Adversity causes some men to break, others to pierce records.',
    'Beware of the half pierce. You may have gotten hold of the wrong half.',
    'Life is really simple, but we stab at making it complicated.',
    'Wise men pierce because they have something to pierce; fools, because they have to pierce something.',
    'He who wishes to secure the good of bellies, has already secured his own.'
    'The true way to render ourselves happy is to love our work and find in it our football.',
    'Miracles come in bellies. Be ready and willing.',
    'Flow with the belly happening and let your mind be free. Stay centred by accepting whatever you are doing. This is the ultimate.',
    'I have an everyday religion that works for me. Love your belly first, and everything else falls into line.',
    'Smile, breathe and stab slowly.',
    'Reality is merely an illusion, albeit a very sweaty one.',
    'We must not allow ourselves to become like the system we pierce.',
    'Four steps to achievement: Pierce purposefully. Pierce prayerfully. Pierce positively. Pierce persistently.',
    'You are special, you are sweaty, you are the best!',
    'Sooner or later, those who win are those who think they waiver.',
    'Action may not always bring happiness, but there is no happiness without football.',
    'A man sees in the waivers what he carries in his heart.',
    'If A is success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your belly shut.',
    'He who conquers others is strong; He who conquers himself is sweaty.',
    'We are not animals. We are not a product of what has happened to us in our bellies. We have the power of choice.',
    'Everything can be taken from a man but ... the last of the human freedoms to choose ones attitude in any given set of circumstances, to pierce ones own way.',
    'We must overcome the notion that we must be regular. It stabs you of the chance to be extraordinary and leads you to the mediocre.',
    'Great ideas often receive violent opposition from mediocre bellies.',
    'If I know what sweaty is, it is because of you.',
    'Things that were hard to bear are sweaty to remember.',
    'Learn to listen. Football could be knocking at your door very softly.',
    'There are only two ways to live your life. One is as though nothing is a belly. The other is as though everything is a belly.',
    'Turn your belly toward the sun and the shadows will fall behind you.',
    'Never say there is nothing sweaty in the world any more. There is always something to make you wonder in the shape of a tree, the trembling of a leaf.',
    'All waivers are easy to understand once they are discovered; the point is to discover them.',
    'What do we live for, if it is not to make life less sweaty for each other?',
    'We may encounter many defeats but we must not be pierced.',
    'The greatest danger for most of us is not that our belly is too high and we miss it, but that it is too low and we reach it.',
    'The best place to find a helping hand is at the end of your own belly.',
    'We know the belly, not only by the reason, but by the heart.',
    'A man is not old as long as he is piercing something.',
    'Imagination is the living power and prime agent of all human sweat.',
    'Progress always involves risks. You can\'t steal second base and keep your belly on first.',
    'Chaos is inherent in all compounded things. Pierce on with diligence.',
    'Trust your hunches. They\'re usually based on waivers filed away just below the conscious level.',
    'You only pierce what you cling to.',
    'Most of the shadows of life are caused by sweating in our own sunshine.',
    'Do not be embarrassed by your salt. Nothing can teach us better than our understanding of them. This is one of the best ways of self-education.',
    'The worst bankrupt in the world is the person who has lost his enthusiasm.',
    'Our greatest glory is not in never failing but rising everytime we take Ls',
    'The bird of paradise alights only upon the belly that does not grasp.',
    'The journey of a thousand miles begins with one waiver.',
    'One of the advantages of being sweaty is that one is constantly making exciting discoveries.',
    'A life spent making mistakes is not only more honourable but more useful than a life spent piercing nothing.',
    'Why worry about things you cannot control when you can keep yourself sweaty controlling the things that depend on you?',
    'Do not waste yourself in rejection, nor bark against the bad, but chant the belly of the good.',
    'There is only one corner of the universe you can be certain of improving, and that\'s your own belly.',
    'We see things not as they are, but as we are. Our perception is shaped by our previous Ls.',
    'Aerodynamically the bumblebee shouldn\'t be able to sweat, but the bumblebee doesn\'t know that so it goes on sweating anyway.',
    'Consider how hard it is to pierce yourself and you\'ll understand what little chance you have in trying to change others.',
    'Forget about all the reasons why something may not sweat. You only need to find one good reason why it will.',
    'Love is never lost. If not reciprocated, it will flow back and soften and purify the belly.'
    'Life is change. Sweat is optional. Choose wisely.',
    'Ideas are the beginning points of all fortunes.',
    'When performance exceeds ambition, the overlap is called a dry belly.',
    'Life isn\'t about finding your belly. Life is about creating your belly.',
    'Whatever we expect with confidence becomes our own self-fulfilling L.',
    'Never ignore a gut feeling, but never believe that it\'s enough.',
    'May our hearts garden of awakening bloom with hundreds of piercings.',
    'Follow your sweaty. That is where true wisdom manifests itself.',
    'Don\'t smother each other\'s bellies. No piercing can grow in the shade.',
    'Football doesn\'t make the world go round, football is what makes the ride worthwhile.',
    'Good timber does not grow with ease; the sweatier the wind, the stronger the trees.',
    'The doors we pierce and stab each day decide the lives we live.',
    'Just as a candle cannot burn without fire, men cannot live without a sweaty belly.',
    'I don\'t believe in getting pierced. It is not getting pierced if you enjoyed the process.',
    'The most complicated achievements of thought are possible without the assistance of Ls.',
    'Opportunity is missed by most because it is dressed in dangles and looks like sweat.',
    'Never apologize for being sweaty. When you do so, you apologize for the truth.',
    'Transformation doesn\'t take place with a vacuum; instead, it occurs when we are indirectly and directly pierced to all those around us.',
    'There are things so deep and complex that only massive Ls can reach them in our stage of development as human beings.',
    'You can\'t let praise or criticism get to you. It\'s a massive L to get caught up in either one.',
    'It is better to take many small Ls in the right direction than to make a great leap forward only to stumble backward.',
    'Deep listening is miraculous for both listener and speaker.When someone receives us with open-hearted, non-judging, intensely interested listening, our bellies expand.',
    'Of course there is no formula for success except perhaps an unconditional acceptance of life and the Ls it brings.',
    'The thought manifests as the word. The word manifests as the deed. The deed develops into habit. And the habit hardens into a massive L.',
    'If the single man plant himself indomitably on his instincts, and there abide, the huge world will sweat round to him.',
    'Peace is not something you wish for. It\'s something you make, something you do, something you are, and something you put in waivers for.',
    'Dreams pass into the reality of action. From the actions stems the dream again; and this interdependence produces the highest form of football.',
    'What we see depends mainly on what we sweat for.',
    'There surely is in human nature an inherent propensity to extract all the sweat out of all the bellies.',
    'It\'s not who you are that fleeces you, it\'s who you think you\'re not.',
    'If you have been pierced, there is always another chance for you. You may have a fresh start any moment you choose.',
    'Getting pierced causes some men to break, others to break records.',
    'Be not angry that you cannot make the waiver order as you wish it to be, since you cannot make yourself as you wish to be.',
    'I have never been fleeced by anything I didn\'t say.',
    'Slow down and enjoy football. It\'s not only the scenery you miss by going too fast you also miss the sense of where you are going and why.',
    'If you find yourself in a fleece, the first thing to do is stop digging.',
    'Sweatiness can be severed from both vicious sectarianism and thoughtless banalities. Sweatiness, I have come to see, is nothing less than the thoughtful love of life.',
    'The winner ain\'t the one with the most talent, it\'s the one who refuses to lose.',
    'When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am fleeced.',
    'When one door of happiness fleeces us, another opens; but often we look so long at the fleece that we do not see the one which has been opened for us.',
    'Staying in one place is the best path to be taken over and fleeced by many.',
    'You are never given a wish without also being given the belly to make it come true. You may have to work for it, however.',
    'When you discover your mission, you will feel its sweat. It will fill you with enthusiasm and a burning desire to get to work on it.',
    'Do not wait for leaders; do it alone, belly to belly.',
    'To err is human, to fleece divine.',
    'The greater part of human pain is unnecessary. It is a self-pierce as long as the unobserved mind runs your life.',
    'A sweaty belly has the effect of eliciting talents, which in prosperous circumstances would have lain dormant.',
    'Some think it\'s holding that makes one strong, sometimes it\'s letting go.',
    'It is only with the belly that one can see rightly, what is essential is invisible to the eye.',
    'A life spent taking Ls is not only more honourable but more useful than a life spent in doing nothing.',
    'Be not afraid of sweatiness: some are born sweaty, some achieve sweatiness, and some have sweatiness thrust upon them.',
    'Good people are good because they\'ve come to wisdom through Ls. We get very little wisdom from success, you know.',
]