BB_PHRASES = [
    'If you have knowledge, let others wash their bellies in it.',
    'At the center of your being you have the answer; you know who you are and you know what you want. To be pierced.',
    'To get the full value of joy you must have someone to stab it with.',
    'Freedom is the right to live as we wish.',
    'We\'re here for a reason. I believe a bit of the reason is to throw little belly button piercings out to lead people through the dark.',
    'Be faithful in small rings because it is in them that your strength lies.',
    'Your outlook on life is a direct reflection on how much you like your belly.',
    'Everything you can imagine is real. Including dangles.',
    'When one tugs at a single thing in nature, he finds it attached to the rest of the BBR universe.',
    'To dream of the belly you would like to be is to waste the belly you are.',
    'Happiness is a perfume you cannot pour on other bellies without getting a few drops on your own.',
    'Without football, nothing is possible. With it, nothing is impossible.',
    'Life is movement -- we breathe, we eat, we walk, we pierce!',
    'It\'s not enough to have a good belly button ring, the main thing is to use it well.',
    'Be glad of life because it gives you the chance to love and to work and to play and to look down at your belly.',
    'The truest greatness lies in being kind, the truest piercing in a happy mind.',
    'The most successful people are those who are good at plan Belly.',
    'Sometimes the cards we are dealt are not always fair. However you must keep smiling and playing the waivers.',
    'I will prepare and some day my ice will come.',
    'Using the power of decision gives you the belly to get past any excuse to change any and every part of your life in an instant.',
    'It is not in the stars to hold our belly, but in ourselves.',
    'Here is one quality that one must possess to win, and that is definiteness of purpose, the knowledge of what one wants, and a burning desire to not get pierced.',
    'If one way be better than another, that you may be sure is the belly\'s way.',
    'No piercing is a waste of time if you use the experience wisely.',
    'We are all inclined to judge ourselves by our ideals; others, by their bellies.',
    'To go against the dominant thinking of your friends, of most of the people you see every day, is perhaps the most difficult act of belly you can perform.',
    'Our ability to achieve happiness and success depends on the strength of our waivers.',
    'Nothing will pierce unless you do.',
    'Simply put, you believe that things or piercings make you unhappy, but this is not accurate. You make yourself unhappy.',
    'Great is the art of beginning, but greater is the art of piercing.',
    'We need to find the courage to say NO to the things and people that are not serving us if we want to rediscover ourselves and place our waivers with authenticity.',
    'An ounce of emotion is equal to a belly of facts.',
    'To hell with circumstances; I pierce opportunities.',
    'What we see depends mainly on the bellies we look for.',
    'Music in the belly can be heard by the universe.',
    'The only way to have a football is to be one.',
    'He who knows that enough is enough will always have football.',
    'Either I will find a football, or I will make one.',
    'All children are footballs. The problem is how to remain an artist once he grows up.',
    'You can stand tall without piercing on someone. You can be a victor without having victims.',
    'Gratitude is riches. Salt is poverty.',
    'The only Zen you find on the tops of mountains is the Zen you pierce up there.',
    'Adversity causes some men to break, others to pierce records.',
    'Beware of the half pierce. You may have gotten hold of the wrong half.',
    'Life is really simple, but we stab at making it complicated.',
    'Wise men pierce because they have something to pierce; fools, because they have to pierce something.',
    'He who wishes to secure the good of bellies, has already secured his own.'
    'The true way to render ourselves happy is to love our work and find in it our football.',
    'Miracles come in bellies. Be ready and willing.',
    'Flow with the belly happening and let your mind be free. Stay centred by accepting whatever you are doing. This is the ultimate.',
    'I have an everyday religion that works for me. Love your belly first, and everything else falls into line.',
    'Smile, breathe and stab slowly.',
    'Reality is merely an illusion, albeit a very sweaty one.',
    'We must not allow ourselves to become like the system we pierce.',
    'Four steps to achievement: Pierce purposefully. Pierce prayerfully. Pierce positively. Pierce persistently.',
    'You are special, you are sweaty, you are the best!',
    'Sooner or later, those who win are those who think they waiver.',
    'Action may not always bring happiness, but there is no happiness without football.',
    'A man sees in the waivers what he carries in his heart.',
    'If A is success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your belly shut.',
    'He who conquers others is strong; He who conquers himself is sweaty.',
    'We are not animals. We are not a product of what has happened to us in our bellies. We have the power of choice.',
    'Everything can be taken from a man but ... the last of the human freedoms to choose ones attitude in any given set of circumstances, to pierce ones own way.',
    'We must overcome the notion that we must be regular. It stabs you of the chance to be extraordinary and leads you to the mediocre.',
    'Great ideas often receive violent opposition from mediocre bellies.',
    'If I know what sweaty is, it is because of you.',
    'Things that were hard to bear are sweaty to remember.',
    'Learn to listen. Football could be knocking at your door very softly.',
    'There are only two ways to live your life. One is as though nothing is a belly. The other is as though everything is a belly.'
]