RESPONSES = [
    'lolll ya boi BBR_MEMBER is hittin rock bottom this morning',
    'if i could like squirmit the frog as much as BBR_MEMBER i would',
    'BBR_MEMBER i know you do a little puff puff pass, its kind of fucked up imo',
    '💯 anyone else want that ship besides BBR_MEMBER',
    'what BBR_MEMBER? i honestly feel like its your call',
    '😳 espn : BBR_MEMBER fingerbanged some 22 year old in the pool party',
    'youre chilling BBR_MEMBER so take your kids to salt disney',
    'ay BBR_MEMBER keep it clean bro',
    'i yelled fuck as loud as i could lol. NFL_PLAYER is fingerbanged',
    'NFL_PLAYER probably 3 bottles of pinot deep lol absolute savagery ! ! !',
    'a great player for sure fuck loll .. NFL_PLAYER can pummel',
    'NFL_PLAYER is the second coming of spike lees douchebaggery super fandom',
    'BBR_MEMBER can we open a bar called “ wet ones ” btw',
    'my fave volleyball duo : kerri walsh and BBR_MEMBER',
    'that s my boiiiii whoop whoop',
    'fuck NFL_PLAYER no way no money is tight right now fuckin christ',
    'haha should probably change my name to infector gadget the immaculate'
    'who is looking good to me.. NFL_PLAYER! NFL_PLAYER for prez !',
    'fleeced wow what a fleece. Fuckin NFL_PLAYER',
    'im done thinking about a NFL_PLAYER / BBR_MEMBER fleecing',
    'you could double team a chick with only BBR_MEMBER all the same',
    'BBR_MEMBER, if you will, butter my ass and pick a lick your poison. losers',
    'BBR_MEMBER? NFL_PLAYER is about to drop 69 points lol',
    'we out here ! ! in other news NFL_PLAYER is trash',
    'hot take 🔥 🔥 🌊 🌊 ! somehow he whips dat thiqqness NFL_PLAYER eatin fo sho',
    'yaaaaaasssssss ! ! ! ! ! ! hoping for a NFL_PLAYER tut hey hey',
    'good to hear that too god damnit i got 7th ... im pretty fucking salty BBR_MEMBER',
    'really loving the looks of this shit , BBR_MEMBER if you didnt know my other teams name is ya boy',
    'BBR_MEMBER i cancelled the trade , planet girth changed my mind',
    'ooh yeah , a great paragraph from BBR_MEMBER would fuckin do me',
    'you can all be my bottoms ! i dont remember lol',
    'holy fuck NFL_PLAYER in the league should be sponsored by tums',
    'lol BBR_MEMBER the only things guaranteed in life are death and death',
    'NFL_PLAYER answer for your crimes! i ’ll move on. bitch',
    'for sure hahahahaha literally thats not the first time BBR_MEMBER has seen his wife',
    'just got even more stressed today . anyone near a computer that can log BBR_MEMBER the fuck on',
    'we got some real lishful thinking here',
    'gotcha. goddammit. i am really taking LS to fucking BBR_PLAYER goddamn',
    'congrats BBR_MEMBER ! ! ! !  the constant gardner i ’m loving this',
    'dude i got hot for NFL_PLAYER for about a week its fucked',
    'BBR_MEMBER stranded on waivers island out here but I did update my mac book to mac chaos mojave 10.14.6 so we lit',
    'wow BBR_MEMBER driving all 5 cars that ran over the lake show',
    'loving the production from NFL_PLAYER, he is now sir rock cock',
    'now thats some good bbr roasting by an open fire 😂 😂 wmfllllgggggg lolol i cant get pierced bro',
    'you invited an outsider to join. meanwhile BBR_MEMBER simply mentionns thiqq and everyone loses their minds',
    'BBR_MEMBER has NFL_PLAYER still whose balling and so i will keep casting ! BBR_MEMBER ! NFL_PLAYER ! ! ! !',
    'NFL_PLAYER wants to make a lish foundation, game time boys',
    'sco NFL_PLAYER!!!! 😟 or not lol',
    'yea BBR_MEMBER I had fun battling with you this week. 2 tds baby',
    'frankkkk the tankkkkk lollll BBR_MEMBER is 6 - 88 im not vetoing that shit',
    'lollll i just got ass fucked by BBR_MEMBER dilly dilly how many drunk driving accidents is that even',
    'by the way commish whats our troll policy, BBR_MEMBER is winless and fucking our asses',
    'heres a moment: when NFL_PLAYER get more snaps, we get more money',
    'need pics need pics need pics',
    'i wanna change my name to antonio bitch',
    'baybeee shenault me timbers! love it! im good now peace botch',
    'bullshit NFL_PLAYER honestly go fuck yourself',
    'obviously BBR_MEMBER. there are 1000 messages in my ass right now',
    'the cunt punt the twat swat the hammer jammer',
    'sounds good looks like we got a blockbuster trade offer fuck you BBR_MEMBER i love you',
    'eating a bag of dicks should be a nice handcuff for NFL_PLAYER',
    'cmon weve all been part of that hairy pussy lets just bet on BBR_MEMBER dangle',
    'it was in oliver thurns bathroom off division and the bills mafia came in and smoked it',
    'the most overrated tight end in the draft order is BBR_MEMBER',
    'i like him but he for sure gets hurt and NFL_PLAYER gets bageled if that happens',
    'i like it more than ctrl - salt - delete, shout out to BBR_MEMBER for having scobee dick',
    'lets just clear the air BBR_MEMBER, the new rookies in your avatar are sucking big time',
    'NFL_PLAYER 😂 lolll there we go good shit. hey BBR_MEMBER throw me a trade offer slut',
    'we all know NFL_PLAYER is a slut vulching all them tutties',
    'unbelievable BBR_MEMBER, and you have the nipple ring? it turned green today',
    'once i heard BBR_MEMBER had sex with NFL_PLAYER i said lol',
    'big 🍆 NFL_PLAYER ! ! ! keep watching those projections wow BBR_MEMBER you got me hard',
    'henry ruggsmuncher should have changed name to vicks vapor rub',
    'brutal ! epic ! haha shit not even worried about the fleece BBR_MEMBER',
    'BBR_MEMBER was there for me but i need an rb2 so fuck that',
    'why BBR_MEMBER? lol i see a 7 am flight that could get you drunk but shoulda woodsa coulda',
    'chyaaaa i do believe thats a deep depression for you! ! hope you eat shit BBR_MEMBER ! ya boi out here ballin',
    'not for me personally but I guess you like him BBR_MEMBER? its basically a lot of soul searching and a couple fuccboi classics',
    'that looks amazing wow fuck u BBR_MEMBER my video is lagged',
    'have you seen BBR_MEMBERs team ? id be more into a risky tuggy',
    'BBR_MEMBER - congrats on your recent mediocrity . only three things guaranteed in life and theyre in my whip',
    'lol projected at 178 smh, lmao n o w hes feeling confident. get BBR_MEMBER on the phone',
    'lol taking a bbr bro soon 😘 dont worry BBR_MEMBER',
    'i like lurk nowitski better, nice job BBR_MEMBER',
    'lmfaooo broooooooo 🤣 🤣 🤣 🤣 i applaud the new avatar BBR_MEMBER',
    'BBR_MEMBER can we get a shoutout to the squad ? you couldve drafted more thick dicks tbh',
    'hes trash BBR_MEMBER lol. hes badminton. no ! hes fencing lol',
    '❤ ️ BBR_MEMBER lollll 😂 😂 😂 i ’m aware of human tight ends',
    'bench NFL_PLAYER then too , even with all the spam this morning his thiqqness is not playoffs level',
    'BBR_MEMBER i wanna bet 50 on them firing your ass yesterday',
    'BBR_MEMBER. its broadcasted in spanish so no, dick',
    'BBR_MEMBER you down to hit vegas august 19th weekend for your bday ? thatll be some some etsy dude',
    'so chill eyaw ! ill be so lit like how i ’m in on my dog after NFL_PLAYER gets his',
    'lit my roommates for sure gon na fleece you BBR_MEMBER!',
    '😂 😂 😂 BBR_MEMBER lolllll you need to get pierced this year tbh',
    'so i went t the titty bar with waksh and BBR_MEMBER, maybe NFL_PLAYER lol',
    'I like NFL_PLAYER quite a bit. even if you dont wow, such a fucking stocking stuffer ! ! ! !',
    '🙄 🙄 🙄 ✏ ️ 🍆 BBR_MEMBER i would just sayin',
    'BBR_MEMBER just send me some trash piece of fucking shit already',
    'BBR_MEMBER come join me . i feel your pain there ! NFL_PLAYER is trash',
    'hola! NFL_PLAYER changed his name to dangleberries i hate this',
    'good ol college parties ... ill hopefully be there . rome was our inaugural pierced location',
    'ya boy NFL_PLAYER been booked. yuppppp bbr takes vegas ! bring the puss ! we lit !',
    'yo. seeing NFL_PLAYER out there is working for me',
    'NFL_PLAYER. wow. my ass!!!',
    'NFL_PLAYER looks legit. god damnit why do i play scrubs just to see if they remember how to get pierced',
    'eyawww how you like that ! NFL_PLAYER with a live tug',
    '😂 BBR_MEMBER you just did n’t want me to swoop NFL_PLAYER',
    'fuckin BBR_MEMBER you changed the groups avatar again and i really don’t want to start',
    'lol NFL_PLAYER is whack as fuck',
    'NFL_PLAYER was drafted .... hot garbage charky baby',
    'im gonna change your name to chef buoyantardee BBR_MEMBER how you like that ass',
    'the NFL_PLAYER injury hurts , BBR_MEMBER batch what are you talking about gtfo',
    'wow NFL_PLAYER tho lfg yesss ! another auto draft team in bbr, call me mr . tummyness winner hands',
    'fucking NFL_PLAYER ..... hunting for my ass',
    'we should just txt him cause BBR_MEMBER probably will get the bbr',
    'NFL_PLAYER is more like clickbait than anything else. and im definitely not one of ur notifications dumbass',
    'NFL_PLAYER is on the block i hope ur happy',
    'BBR_MEMBER it changes everyday, and you dont call them stupid or ugly. thats rough i just call them bad',
    'giving NFL_PLAYER the start next week is crack in my ass',
    'fuckkkkkk so whack when the fuck is a tie better than a torn achilles for NFL_PLAYER',
    'BBR_MEMBER ur projected for 80 points lol, for sure lets fucking go stupid riccy',
    '😟 BBR_MEMBER - NFL_PLAYER and the falcons have their heads in your ass',
    'nothing easy this season . this might be ur best bet to win BBR_MEMBER',
    'NFL_PLAYER on the bench! the fuck are you thinking',
    'dont want to blow your mind BBR_MEMBER but your team is ass',
    'NFL_PLAYER is a bum BBR_MEMBER but I would hit him up for ass at least',
    '1 fodie down and i still have a hell of a redbox lineup. Get fucked BBR_MEMBER!',
    'if anyone needs a cute bbr to play I have a BBR_MEMBER ass',
    '💪 shout out to BBR_MEMBER with another massive L. ive said it before, apple need to sponsor that ass',
    'BBR_MEMBER is deff doing butt stuff with NFL_PLAYER this weekend while my ff team takes another l',
    'fuck the damn packers ! ! might just buy a big bottle of shampoo so they dont get BBR_MEMBER',
    'im still interested in NFL_PLAYER ? ? ? wtf is wrong with me',
    'BBR_MEMBER squirting through the chat . true professional',
    'lol BBR_MEMBER did u keep ur jewelry to frame on mount bbr',
    'NFL_PLAYER is a power bottom lmao put some respeck on that 😂',
    'BBR_MEMBER take an offer for NFL_PLAYER if ya can cause i hate you starting his ass',
    'BBR_MEMBER missed his curfew last night so hes pretty much fucked',
    'BBR_MEMBER you gotta pay 4 that classic disney + drip',
    'lolll looby dooby NFL_PLAYER dewing me dirty damn',
    'BBR_MEMBER all eyes on you 👀 for some clarification here i ’d prefer to have the ass',
    'NFL_PLAYER just isnt lit he got hurt in the pit',
    'NFL_PLAYER lookin explosive af 😂 are you okay BBR_MEMBER',
    'herps ? just a clap here and there but really that works for BBR_MEMBER',
    'honestly after NFL_PLAYER shits the bed first week id be down for whatever',
    'hows ur bb feelin BBR_MEMBER?',
    'NFL_PLAYER is working with a delivery service in my ass',
    'good stuff from NFL_PLAYER. love watching football players punch each other in the helmet after a 10 hour flight',
    'honestly NFL_PLAYER shouldnt be on the same team as my opinions',
    'nah i have faith in NFL_PLAYER looks like ... a very enticing fuck',
    'BBR_MEMBER wow ... im down by your roster i dunno if youve seen it but yikes',
    'BBR_MEMBER theres a category 5 coming your way shmoop',
    'sounds like BBR_MEMBER wants in, we can put em on blast ?',
    '😎 🏌 🏻‍ ♂ ️ lollll i wanna get that shit on with NFL_PLAYER',
    'keep calm and sweat on, propose a bet and ill take it BBR_MEMBER',
    'NFL_PLAYER could do the same shit every year, ive cleared out a few blowjobs already',
    'NFL_PLAYER is no splashed potatoes 🥔 to the bench ! ! !',
    'I should prolly start gettin into it to someone other than BBR_MEMBER or walsh',
    'fuck i forgot im playing you this week ... luckily BBR_MEMBER doin usual BBR_MEMBER things',
    'its on my snap chat BBR_MEMBER 😎 😎 😎  but it ’s crazy how that can just get you pierced now??',
    'NFL_PLAYER looks like such a queef ... but he did go beast mode on his last tug',
    'NFL_PLAYER sucks for opportunity i need a streetsweeper out chea',
    'BBR_MEMBER are you hating NFL_PLAYER being on your own supply',
    'NFL_PLAYER is dry mother fucking piece of shit what happened to him ?',
    'knowing i ’m for sure fucked i ’m down to order a midget whore for you BBR_MEMBER',
    'my rbs were wrecked but NFL_PLAYER\'s thick hog has given me life',
    'dont think i m a try to accommodate everyone BBR_MEMBER love it hahahaha',
    'update : still no BBR_MEMBER ! ! ! ! ! nice doin business with you botch',
    'fuck you BBR_MEMBER ... funny too cuz  lady fog horn raced two races earlier and won haha fuck ...',
    'it ’s a hopeless game we play haha were fucked BBR_MEMBER',
    'BBR_MEMBER its bbr not npr, who the fuck is down for nipple piercings next year instead of belly ?',
    'BBR_MEMBER 😂 😂 😂 😂 😂 NFL_PLAYER ? i ’ve seen him',
    'is NFL_PLAYER about to get some penetration in? no ...',
    'i ’ll be there about 115 lets just see NFL_PLAYER throw tugs',
    'always been that way you have both running backs in that game so stupid can someone check on BBR_MEMBER i beat that ass',
    'no i m not jah feelin NFL_PLAYER',
    'lol why ? PLAYER_NAME was born on 9/11',
    'i dont even need to draft well BBR_MEMBER. just a little shade for the ride',
    'hahaha BBR_MEMBER your proposals are such trade rapes ca nt do it. if you dont want my thiqq boy just say so',
    'i already fell in love with strippers once BR_MEMBER, even the worlds greatest warriors lose a battle every now and then',
    '💩 dude same thing get NFL_PLAYER on the ballot',
    'asquirmative ❤ ️ 🍽 if i lose , you pay 30 if you lose i tap',
    'BBR_MEMBER you ’re okay man. update : almost tore my mcl',
    'great BBR_MEMBER that ’s goal 1 . i just said get fucked',
    'wow lol clambi clam margera space clam clam bam thank you mam also when was the last time anyone cleaned their belly button',
    'official: BBR_PLAYER will you be my aaron hernandez',
    'shocker another punt jesus both these teams sucks ass battle of the ass',
    'i bet BBR_MEMBER woulda taken that bet on stripper mud wrestling ',
    'were gon na suck again lol the saltiest of posts 😂 😂 makes up for NFL_PLAYER so.. lit',
    'BBR_MEMBER, again. that may be ticonderoga , but the girth has left the bbr gods in an L',
    'so BBR_MEMBER... most people stay away from 3 rb committees lol',
    'batchley ! NFL_PLAYER or julio jones ... what a question',
    'ill get a belly update when you take that drape for a walk BBR_MEMBER',
    'cheddd 🧀 🧀 🧀 thanks BBR_MEMBER ! and the fast track to the needlejuice dang outs',
    '? ? NFL_PLAYER . Bro ! classic i would trade any of my thiqqs . whoever',
    'lmao ! ! ! ! ! what the fuck happened to me BBR_MEMBER',
    'another big performance from BBR_MEMBER ! ! ! ! ! NFL_PLAYER fucks',
    '! stretchemmm x2 ! ! ! ! go ducks cant believe i dropped NFL_PLAYER',
    'you check this chat ... group therapy for NFL_PLAYER',
    'all im saying is dont do it in the tunnel with NFL_PLAYER',
    'lol BBR_MEMBER will be my little sobrina picking names venmo me $',
    'damn BBR_MEMBER. bet youre bummed to be matched up against a d that can give curtains negative points',
    'ay BBR_MEMBER, signed and sealed. NFL_PLAYER is like the shittier version of danny woodhead',
    'for NFL_PLAYER this seems to happen every fuckin sunday',
    '! ! ! ! ! ! NFL_PLAYER for a torn acl too . just thinking about it rather than just coasting in the Ls',
    'the fleecer and the shit is real i was trying to beautiful mind my way through this NFL_PLAYER performance',
    '😂 NFL_PLAYER is 6\'3 maybe , and that ’s a whole schpiel',
    'its all on me baby lets fucking go stupid riccy nice job last week BBR_MEMBER',
    'fuck that sucks for NFL_PLAYER . and my belly?!?',
    'BBR_MEMBER let me put a shotgun or beer chug on tonight\'s game ? loser has to be at ladds at 930',
    'take me back to portland tomorrow , fuck ! hahha NFL_PLAYER sucking it',
    'NFL_PLAYER is an emergency . fuck canned beans , this shit sucks!!!!',
    'fucking fuck what\'s happening on waivers . right after picking up NFL_PLAYER too',
    'BBR_MEMBER you ate everyone ’s chicken sandos so fucked',
    'a fresh wound for BBR_MEMBER?? sign me up you ass',
    'BBR_MEMBER you are out of your belly piercing mind',
    'cmon BBR_MEMBER ! the suspense is killing me lol of course youre playing squirm edwards',
    'fuck this week why is my ass hole gaping',
    'stfu fucking garbage NFL_PLAYER getting dropped first thing in the morning',
    'pull the trigger on another double barrel 🤣 🤣 🤣 shout out to BBR_MEMBER on that ain’t my first',
    'BBR_MEMBER you told me to trade NFL_PAYER WTF ! ! ! !',
    'lol NFL_PLAYER is about to ruin the whole season',
    'ok BBR_MEMBER, but loser has to sit in monday’s " god knows " corner lol',
    'BBR_MEMBER had to turn off mute cause im fuckin hard',
    'shout out to walsh calling BBR_MEMBER a wench',
    'wowowowowow u get better and i play some ass but i agree BBR_MEMBER lmao',
    'youre a happy meal, i would like some voodoo shit i m feeling thiqq today 69min till kickoff',
    'the irony of a pencil thin like BBR_MEMBER talking shit ',
    'BBR_MEMBER has scored 110 pts today meaning he definitely has NFL_PLAYER in his stable',
    'NFL_PLAYER?? please ink the deal BBR_MEMBER!',
    'hahaha BBR_MEMBER! ! ! ! lookin like a dill(y) for one how about a league wide shotgun',
    'dang BBR_MEMBER if you did nt know ... i fucking hate this sport',
    'batchley ! NFL_PLAYER id get in on that shit 😂',
    'yea but you have 512 fucking points on your bench BBR_MEMBER!!! goddammit lil kupp of stills water ... no bubbles',
    'as a bottom dweller myself, not fluffing yourself up is the shirtest way to go BBR_MEMBER',
    'NFL_PLAYER not killing it so y’ all can take him this season . # foreverscarred',
    'now see if anyone wants to fux with a trade !!! im projected to tie ! somehow ...',
    'now im for sure missing the playoffs BBR_MEMBER, incredible effort sir',
    'just adjusted and wtf the app is just torching me now goddammit fucking fuck',
    'its actually wild lmfao can we get some pre pierce interview action with BBR_MEMBER?',
    'the best part is when shit starts to go off on my bench. fucking stench goddamn',
    'i just got ousted from the playoffs so BBR_MEMBER imma take you out bruh! nothin but love everyone ’s been fleeced',
    'holy fuck NFL_PLAYER hey BBR_MEMBER, you wanna score a few and bring that ass down . where u at playa ?',
    'suck this drenchcoat birch drench * * * can NFL_PLAYER just show up tonight fuck',
    'lolll i ca nt blame NFL_PLAYER i respect the drip too much. to my chagrin',
    'shout out to faded me on that one lol',
    'lol yeah dude i was literally a topic for weeks',
    'NFL_PLAYER is probably the weakest thing ive ever been good with',
    'lmao!!!! yo the horse race thing is how we get big headed ... just my theory',
    'BBR_MEMBER just following you into your bathroom dude ^^ that man is a father 😂 😂',
    '4 mickey monday ? damnnn , we feeling a little far fetched BBR_MEMBER',
    'hmmmm interesting fleece. although NFL_PLAYER feels more slated as a self - fulfleecing prophecy for me but i ’ve also been so nasty',
    'truuuueee hahahaha tell that to 7 interceptions NFL_PLAYER threw last week so good thing I just traded him',
    'true BBR_MEMBER but max is about to have dennis’ed ur bish ass',
    '3 weeks until NFL_PLAYER jags off',
    'i already am a contender me giving you NFL_PLAYER would make you lose even more bitch',
    'i would appreciate it all previously pierced could bench their thiqqs',
    '? ? lol haha im feeling pretty good about getting my first pierce BBR_MEMBER',
    'yeah thats fucked BBR_MEMBER',
    'stupid little flamer!!! fuck!! me!!',
    'auto drafting ... gon na win it all',
    'i will be there BBR_MEMBER we fucked up',
    'see this NFL_PLAYER fool on memphis shorts ? delishous content here planet lish it keeps him warm in the winter',
    '! ! ! should be a bbr first and BBR_MEMBER just put me in the fridge',
    'BBR_MEMBER i smell bbr hole  😂',
    'its just live all year around flames. dont look at my phone , i think kruegz is gon nalose',
    'bbr squaw BBR_MEMBER you are gonna be a dangle as soon as possible , since we and other healthcare boys are live',
    'internet gettin wild on NFL_PLAYER today . just the right amount of fuck lol',
    'oh yea , i ’m in that pool . id be chatting right now. i bet BBR_MEMBER doesnt even know how it goes to ot',
    'lmfao what does that mean i already won ? ? lol chyaaaaa i have no confidence but it ’s just a bunch of haters in the end',
    'yupppppp one more fg baby NFL_PLAYER is an absolute toss up. codeine zuerlean',
    'my two starting wrs for the next month are shit and fuck',
    'amazing to see 3 previously pierced in contention for yet another falcons dub. that includes you BBR_MEMBER',
    'haha shout out to BBR_MEMBER your team is garbage',
    'dilly dilly i had the under im fucked',
    '🤤 jesus please send NFL_PLAYER to the university of pouregon',
    'sorry BBR_MEMBER lollll hahaha. just do nt believe youll find a chick with huge tits',
    'im a big sunday guy so still feeling good about it',
    'NFL_PLAYER, a legendary both sides of the fence fuccboi',
    'BBR_MEMBER tryin to sell high on either of the 2 aaron ’s in his ass',
    'damnnn . everyone puttin money on NFL_PLAYER now huh',
    '👏 👏 👏 really appreciate that play by play BBR_MEMBER',
    'little lish bish thinnbalina be slurpin down that oregon rail',
    'a win without a flex?? i think thats weak BBR_MEMBER. youve got a redzone bone ! ! !',
    'im just saying lmfao ... how lucky can one guy be ... fucking NFL_PLAYER',
    'a classic route to danglin and im out 200 just like that',
    'im draft driving lol hold on'
]