MEMBERS = [
    'bk',
    'D',
    'lish',
    'cam',
    'shanye',
    'walsh',
    'trav',
    'vino',
    'ne',
    'j-rock',
    'justin',
    'jerad',
    'g-lish',
    'shane',
    'ren',
    'rene',
    'commish',
    'clambino',
    'walshy'
]


PLAYERS = [
    'ezekiel elliott',
    'tyreek hill',
    'mark andrews',
    'john brown',
    'jamison crowder',
    'allen robinson',
    'robert tonyan',
    'cam newton',
    'jason sanders',
    'younghoe koo',
    'nick chubb',
    'adam thielen',
    'justin herbert',
    'dalvin cook',
    'ronald jones',
    'julio jones',
    'james conner',
    'jonathan taylor',
    'cooper kupp',
    'dj chark jr.',
    'deshaun watson',
    'derrick henry',
    'randy bullock',
    't.j. hockenson',
    'josh jacobs',
    'russell wilson',
    'adrian peterson',
    'rodrigo blankenship',
    'justin jefferson',
    'matthew stafford',
    'robby anderson',
    'darrell henderson jr.',
    'laviska shenault jr.',
    'j.d. mckissic',
    't.y. hilton',
    'michael thomas',
    'travis kelce',
    'patrick mahomes',
    'mark ingram ii',
    'robbie gould',
    'sammy watkins',
    'jimmy graham',
    'brandin cooks',
    'christian mccaffrey',
    'kenyan drake',
    'davante adams',
    'odell beckham jr.',
    "le'veon bell",
    'kareem hunt',
    'terry mclaurin',
    'julian edelman',
    'alvin kamara',
    'george kittle',
    'jason myers',
    'deandre hopkins',
    'chris carson',
    'leonard fournette',
    'dk metcalf',
    'tom brady',
    'jerry jeudy',
    'aaron rodgers',
    'devonta freeman',
    'dk swetcalf',
    'bill belichick',
    'greg holsen',
    'rich flair',
    'scott frost'
]


OTHERS = [
    'my uncle',
    'my dad',
    'my older brother',
    'the ceo of gucci',
    'lil yachty',
    'Juicy Josh Scrillipman',
    'Damian Lillard',
    'Shaq',
    'Fred Skinstone',
    'Stabo Swinney',
    'Lindsey Buckingham'
    'jesus',
    'the space guttle',
    'indica williams',
    'mr . xantastic'
]

ALL_PEOPLE = MEMBERS + PLAYERS + OTHERS
