MEMBERS = [
    'bk',
    'D',
    'lish',
    'cam',
    'shanye',
    'walsh',
    'trav',
    'vino',
    'ne',
    'j-rock',
    'justin',
]


PLAYERS = [
    'ezekiel elliott',
    'tyreek hill',
    'mark andrews',
    'john brown',
    'jamison crowder',
    'allen robinson',
    'deebo samuel',
    'robert woods',
    'mike davis',
    'robert tonyan',
    'cam newton',
    'travis fulgham',
    'jason sanders',
    'darius slayton',
    'younghoe koo',
    'clyde edwards-helaire',
    'nick chubb',
    'adam thielen',
    'dj moore',
    'darren waller',
    'phillip lindsay',
    'latavius murray',
    'ceedee lamb',
    'henry ruggs iii',
    'justin tucker',
    'nyheim hines',
    'lamar jackson',
    'evan engram',
    'jamaal williams',
    'justin herbert',
    'dalvin cook',
    'ronald jones',
    'julio jones',
    'james conner',
    'jonathan taylor',
    'cooper kupp',
    'dj chark jr.',
    'deshaun watson',
    "d'ernest johnson",
    'derrick henry',
    'james white',
    'alexander mattison',
    'randy bullock',
    'chase claypool',
    't.j. hockenson',
    'josh jacobs',
    'russell wilson',
    'adrian peterson',
    'chris godwin',
    'rodrigo blankenship',
    'justin jefferson',
    'chase edmonds',
    'russell gage',
    'matthew stafford',
    'eric ebron',
    'mike evans',
    'zach ertz',
    'devin singletary',
    'sterling shepard',
    'robby anderson',
    'darrell henderson jr.',
    'laviska shenault jr.',
    'j.d. mckissic',
    't.y. hilton',
    'michael thomas',
    'travis kelce',
    'todd gurley ii',
    'patrick mahomes',
    'mark ingram ii',
    "d'andre swift",
    'stefon diggs',
    'devante parker',
    'antonio gibson',
    'robbie gould',
    'sammy watkins',
    'jimmy graham',
    'brandin cooks',
    'christian mccaffrey',
    'kenyan drake',
    'davante adams',
    'odell beckham jr.',
    "le'veon bell",
    'kareem hunt',
    'terry mclaurin',
    'julian edelman',
    'keenan allen',
    'joshua kelley',
    'jonnu smith',
    'tee higgins',
    'mason crosby',
    'alvin kamara',
    'george kittle',
    'kenny golladay',
    'calvin ridley',
    'juju smith-schuster',
    'a.j. green',
    'david montgomery',
    'will fuller v',
    'zack moss',
    'matt ryan',
    'sony michel',
    'tyler boyd',
    'jerick mckinnon',
    'ben roethlisberger',
    'jason myers',
    'deandre hopkins',
    'chris carson',
    'leonard fournette',
    'dk metcalf',
    'scotty miller',
    'myles gaskin',
    'greg zuerlein',
    'damien harris',
    'gardner minshew ii',
    "la'mical perine",
    'noah fant',
    'austin hooper',
    'austin ekeler',
    'joe mixon',
    'amari cooper',
    'melvin gordon iii',
    'tyler lockett',
    'raheem mostert',
    'jarvis landry',
    'tom brady',
    'jerry jeudy',
    'aaron rodgers',
    'zane gonzalez',
    'devonta freeman',
    'dalton schultz',
    'dk swetcalf',
    'bill belichick',
    'greg holsen',
    'lil yachty',
]


OTHERS = [
    'my uncle',
    'my dad',
    'my older brother',
    'the ceo of gucci',
]

ALL_PEOPLE = MEMBERS + PLAYERS + OTHERS
