ANTICIPATION_PREFIXES = [
    'one sec ... shit',
    'hmm not sure, damn',
    'gimme a moment .. ugh',
    'one minute, oh, wow',
    'oh shit hold on',
    'thats a tough one',
    'fuck, sorry',
    'shit, sorry',
    'one moment please',
    'hold on',
    'umm',
    'hard to say',
    'cant say',
    'cant think right now',
    'hold please',
    'no idea',
    'hmmm.. hard to say',
    'cant think about that right now',
    'eyawwwwww',
    'chyaaaa',
    'ummmmmm',
    'uhhhhh',
    'one sec',
    'one sec, ah shit',
    'hold up',
    'wait up',
    'wait up, wtf',
    'just a sec',
    'just a moment',
    'ah fuck',
    'ah fuck, hold on',
    'shittt, one sec',
    'goddammit, one se,'
    'one sec, fuck',
    'ahhhhhhhh shit',
    'oh man',
    'chyaaaaa, one sec',
    'eyawwwww, one sec',
    'brb',
    'gotta go',
    'sorry gotta go',
    'sorry brb',
    'umm, one moment please',
    'whoa, hold on a sec',
    'ahh shit, umm',
    'well, ahh fuck,',
    'ah shit wtf',
    'cant think right now',
    'oh wtf',
    'bro',
    'ah man you gotta be kidding me',
    'ah man are you shitting me',
    'man, wtf',
    'chyaaaa, oh fuck',
    'ummmmmm, wtf',
    'jesus christo',
    'jesus',
    'christ',
    'shit, shit',
    'fuck, shit',
    'ah shit, sorry',
    'goddammit, shit',
    'damnit',
]

ANTICIPATIONS = [
    'im feeling a little nervous about it',
    'im stoked to see it happen',
    'im not at all excited about it',
    'i don\'t think he can pull it off',
    'it\'s gonna be a shitshow',
    'honestly im scared',
    'i feel like im about to get fleeced',
    'honestly feel like im about to get fleeced',
    'honestly im for it',
    'im honestly down',
    'i cant believe it',
    'theres just no way',
    'everyones telling him not to',
    'everyones egging him on',
    'nobodys pleased',
    'people honestly just look pissed',
    'honestly people here just look annoyed',
    'im trying to ghost outta here',
    'im just trying to ghost',
    'im trying to dip',
    'can someone come pick me up',
    'somebody come swoop my ass',
    'im trying to get in on it',
    'im gonna put it on snapchat',
    'i dont think im gonna survive',
    'i just dont see how its gonna work',
    'everyones getting their phones out lol',
    'everyones going on IG live',
    'and nobodys making eye contact with him lol',
    'and everyones staring',
    'nobody here seems to give a shit',
    'and nobody here even seems to care',
    'and tbh im not sure what that means'
]

CURRENT_PREFIXES = [
    'hold please,',
    'one sec,',
    'hold on,',
    'wait a sec,',
    'hold up,',
    'just a moment,',
    'gimme a sec,',
    'gimme a moment here,',
]

REACTION_PREFIXES = [
    'well',
    'all i know is ',
    'basically ',
    'even though everyone was like no, ',
    'well, basically ',
    'fucking ',
    'even though everyone was beggin him not to, ',
    'despite everyone telling him not to, ',
    'well, fuckin',
    'fuckin ',
    'dude..',
    'dude.. fucking',
    'bro,',
    'bro...',
    'bro, fucking',
    'lets just say',
    'predictably,',
]

REACTIONS = [
    'i cant think about anything else',
    'everything here is just honestly fucked',
    'now everyone here is pissed',
    'now everyone here is stoked',
    'now everyone here is just vibing',
    'im salty af',
    'people are pretty fucking salty',
    'im losing my mind',
    'now everyone here is losing their minds',
    'people are losing their goddamn minds',
    'its an absolute trainwreck',
    'its absolute flames',
    'its honestly fucking lit',
    'we lit',
    'its fucking lit',
    'folks here are heated',
    'im fucking heated',
    'it doesnt help that im high as fuck',
    'it doesnt help that im high as balls',
    'i think a fight is about to break out',
    'people are throwing hands',
    'people are pissed',
    'now everyones fucking',
    'people are fucking',
    'a rave just broke out',
    'im about to rage quit',
    'im fucking dead',
    'im dead',
    'im wrecked',
    'now everyone is dying',
    'im dying',
    'now my hole is a jalapeño',
    'now everyone is leaving',
    'nobody\'s buying it',
    'now everyone\'s in my ass',
    'now everyone\'s in my ass about it',
    'now everyone is straight hating on my ass',
    'now everyone hates my ass',
    'im honestly fucked up',
    'now everyone\'s fucked up',
    'now im getting fucking pierced',
    'now everyones getting pierced',
    'now everyones benching their thiqqs',
    'people are going in',
    'im getting in on it too',
    'now everyones getting involved',
    'im out another benjamin',
    'im out another fucking benjamin',
    'my ass is getting beat',
    'my ass is absolutely fucked',
    'apparently now im scott hansens backup tomorrow',
    'now im stuck in the dangle submarine',
    'ive got a global award',
    'im fucking waxing',
    'now im getting fucking dusted',
    'now im getting absolutely dusted',
    'they vetoed my ass',
    'im honestly scared',
    'im honestly not feeling it anymore',
    'now everyones putting in waiver claims',
    'my belly is forever tainted',
    'now im fucking ruined',
    'now everyones raging',
    'my ass is so fucked',
    'everyones saying christmas came early',
    'everyones sending me trash trades',
    'im higher than ive ever been in my life',
    'i think im blacked',
    'im so fucking high dude',
    'im a little dazed',
    'im a little bit dazed',
    'im fucked up',
    'i just gotta get the fuck out of here',
    'im none too happy about it',
    'now everyones fucking celebrating',
    'now everyones celebrating',
    'now im on a no fly list',
    'my ass is drenched',
    'nobodys happy about it',
]